.class public final enum LCUk;
.super Ljava/lang/Enum;
.source "SourceFile"

# interfaces
.implements LI58;


# annotations
.annotation system Ldalvik/annotation/Signature;
    value = {
        "Ljava/lang/Enum<",
        "LCUk;",
        ">;",
        "LI58;"
    }
.end annotation


# static fields
.field public static final enum A0:LCUk;
    .annotation runtime Lcom/google/gson/annotations/SerializedName;
        value = "AUTOGENERATED"
    .end annotation
.end field

.field public static final enum B0:LCUk;
    .annotation runtime Lcom/google/gson/annotations/SerializedName;
        value = "MY_STORY_VARIANT"
    .end annotation
.end field

.field public static final synthetic C0:[LCUk;

.field public static final enum X:LCUk;
    .annotation runtime Lcom/google/gson/annotations/SerializedName;
        value = "SHOW"
    .end annotation
.end field

.field public static final enum Y:LCUk;
    .annotation runtime Lcom/google/gson/annotations/SerializedName;
        value = "IMPALA"
    .end annotation
.end field

.field public static final enum Z:LCUk;
    .annotation runtime Lcom/google/gson/annotations/SerializedName;
        value = "THIRD_PARTY_APP"
    .end annotation
.end field

.field public static final enum b:LCUk;
    .annotation runtime Lcom/google/gson/annotations/SerializedName;
        value = "MY"
    .end annotation
.end field

.field public static final enum c:LCUk;
    .annotation runtime Lcom/google/gson/annotations/SerializedName;
        value = "OUR"
    .end annotation
.end field

.field public static final enum d:LCUk;
    .annotation runtime Lcom/google/gson/annotations/SerializedName;
        value = "USER"
    .end annotation
.end field

.field public static final enum e:LCUk;
    .annotation runtime Lcom/google/gson/annotations/SerializedName;
        value = "BRAND"
    .end annotation
.end field

.field public static final enum f:LCUk;
    .annotation runtime Lcom/google/gson/annotations/SerializedName;
        value = "AD"
    .end annotation
.end field

.field public static final enum g:LCUk;
    .annotation runtime Lcom/google/gson/annotations/SerializedName;
        value = "DYNAMIC"
    .end annotation
.end field

.field public static final enum h:LCUk;
    .annotation runtime Lcom/google/gson/annotations/SerializedName;
        value = "GROUP"
    .end annotation
.end field

.field public static final enum i:LCUk;
    .annotation runtime Lcom/google/gson/annotations/SerializedName;
        value = "PROMOTED_STORY"
    .end annotation
.end field

.field public static final enum j:LCUk;
    .annotation runtime Lcom/google/gson/annotations/SerializedName;
        value = "LIVE_STREAMING"
    .end annotation
.end field

.field public static final enum k:LCUk;
    .annotation runtime Lcom/google/gson/annotations/SerializedName;
        value = "DISCOVER"
    .end annotation
.end field

.field public static final enum t:LCUk;
    .annotation runtime Lcom/google/gson/annotations/SerializedName;
        value = "PUBLISHER"
    .end annotation
.end field

.field public static final enum y0:LCUk;
    .annotation runtime Lcom/google/gson/annotations/SerializedName;
        value = "MIXED"
    .end annotation
.end field

.field public static final enum z0:LCUk;
    .annotation runtime Lcom/google/gson/annotations/SerializedName;
        value = "COMMUNITY"
    .end annotation
.end field


# instance fields
.field public final a:I


# direct methods
.method static constructor <clinit>()V
    .locals 21

    .line 1
    new-instance v0, LCUk;

    .line 2
    .line 3
    const-string v1, "MY"

    .line 4
    .line 5
    const/4 v2, 0x0

    .line 6
    invoke-direct {v0, v1, v2, v2}, LCUk;-><init>(Ljava/lang/String;II)V

    .line 7
    .line 8
    .line 9
    sput-object v0, LCUk;->b:LCUk;

    .line 10
    .line 11
    new-instance v1, LCUk;

    .line 12
    .line 13
    const-string v3, "OUR"

    .line 14
    .line 15
    const/4 v4, 0x1

    .line 16
    invoke-direct {v1, v3, v4, v4}, LCUk;-><init>(Ljava/lang/String;II)V

    .line 17
    .line 18
    .line 19
    sput-object v1, LCUk;->c:LCUk;

    .line 20
    .line 21
    new-instance v3, LCUk;

    .line 22
    .line 23
    const-string v5, "USER"

    .line 24
    .line 25
    const/4 v6, 0x2

    .line 26
    invoke-direct {v3, v5, v6, v6}, LCUk;-><init>(Ljava/lang/String;II)V

    .line 27
    .line 28
    .line 29
    sput-object v3, LCUk;->d:LCUk;

    .line 30
    .line 31
    new-instance v5, LCUk;

    .line 32
    .line 33
    const-string v7, "BRAND"

    .line 34
    .line 35
    const/4 v8, 0x3

    .line 36
    invoke-direct {v5, v7, v8, v8}, LCUk;-><init>(Ljava/lang/String;II)V

    .line 37
    .line 38
    .line 39
    sput-object v5, LCUk;->e:LCUk;

    .line 40
    .line 41
    new-instance v7, LCUk;

    .line 42
    .line 43
    const-string v9, "AD"

    .line 44
    .line 45
    const/4 v10, 0x4

    .line 46
    invoke-direct {v7, v9, v10, v10}, LCUk;-><init>(Ljava/lang/String;II)V

    .line 47
    .line 48
    .line 49
    sput-object v7, LCUk;->f:LCUk;

    .line 50
    .line 51
    new-instance v9, LCUk;

    .line 52
    .line 53
    const-string v11, "DYNAMIC"

    .line 54
    .line 55
    const/4 v12, 0x5

    .line 56
    invoke-direct {v9, v11, v12, v12}, LCUk;-><init>(Ljava/lang/String;II)V

    .line 57
    .line 58
    .line 59
    sput-object v9, LCUk;->g:LCUk;

    .line 60
    .line 61
    new-instance v11, LCUk;

    .line 62
    .line 63
    const-string v13, "GROUP"

    .line 64
    .line 65
    const/4 v14, 0x6

    .line 66
    invoke-direct {v11, v13, v14, v14}, LCUk;-><init>(Ljava/lang/String;II)V

    .line 67
    .line 68
    .line 69
    sput-object v11, LCUk;->h:LCUk;

    .line 70
    .line 71
    new-instance v13, LCUk;

    .line 72
    .line 73
    const-string v15, "PROMOTED_STORY"

    .line 74
    .line 75
    const/4 v14, 0x7

    .line 76
    invoke-direct {v13, v15, v14, v14}, LCUk;-><init>(Ljava/lang/String;II)V

    .line 77
    .line 78
    .line 79
    sput-object v13, LCUk;->i:LCUk;

    .line 80
    .line 81
    new-instance v15, LCUk;

    .line 82
    .line 83
    const-string v14, "LIVE_STREAMING"

    .line 84
    .line 85
    const/16 v12, 0x8

    .line 86
    .line 87
    invoke-direct {v15, v14, v12, v12}, LCUk;-><init>(Ljava/lang/String;II)V

    .line 88
    .line 89
    .line 90
    sput-object v15, LCUk;->j:LCUk;

    .line 91
    .line 92
    new-instance v14, LCUk;

    .line 93
    .line 94
    const-string v12, "DISCOVER"

    .line 95
    .line 96
    const/16 v10, 0x9

    .line 97
    .line 98
    invoke-direct {v14, v12, v10, v10}, LCUk;-><init>(Ljava/lang/String;II)V

    .line 99
    .line 100
    .line 101
    sput-object v14, LCUk;->k:LCUk;

    .line 102
    .line 103
    new-instance v12, LCUk;

    .line 104
    .line 105
    const-string v10, "PUBLISHER"

    .line 106
    .line 107
    const/16 v8, 0xa

    .line 108
    .line 109
    invoke-direct {v12, v10, v8, v8}, LCUk;-><init>(Ljava/lang/String;II)V

    .line 110
    .line 111
    .line 112
    sput-object v12, LCUk;->t:LCUk;

    .line 113
    .line 114
    new-instance v10, LCUk;

    .line 115
    .line 116
    const-string v8, "SHOW"

    .line 117
    .line 118
    const/16 v6, 0xb

    .line 119
    .line 120
    invoke-direct {v10, v8, v6, v6}, LCUk;-><init>(Ljava/lang/String;II)V

    .line 121
    .line 122
    .line 123
    sput-object v10, LCUk;->X:LCUk;

    .line 124
    .line 125
    new-instance v8, LCUk;

    .line 126
    .line 127
    const-string v6, "IMPALA"

    .line 128
    .line 129
    const/16 v4, 0xc

    .line 130
    .line 131
    invoke-direct {v8, v6, v4, v4}, LCUk;-><init>(Ljava/lang/String;II)V

    .line 132
    .line 133
    .line 134
    sput-object v8, LCUk;->Y:LCUk;

    .line 135
    .line 136
    new-instance v6, LCUk;

    .line 137
    .line 138
    const-string v4, "THIRD_PARTY_APP"

    .line 139
    .line 140
    const/16 v2, 0xd

    .line 141
    .line 142
    invoke-direct {v6, v4, v2, v2}, LCUk;-><init>(Ljava/lang/String;II)V

    .line 143
    .line 144
    .line 145
    sput-object v6, LCUk;->Z:LCUk;

    .line 146
    .line 147
    new-instance v4, LCUk;

    .line 148
    .line 149
    const-string v2, "MIXED"

    .line 150
    .line 151
    move-object/from16 v17, v6

    .line 152
    .line 153
    const/16 v6, 0xe

    .line 154
    .line 155
    invoke-direct {v4, v2, v6, v6}, LCUk;-><init>(Ljava/lang/String;II)V

    .line 156
    .line 157
    .line 158
    sput-object v4, LCUk;->y0:LCUk;

    .line 159
    .line 160
    new-instance v2, LCUk;

    .line 161
    .line 162
    const-string v6, "COMMUNITY"

    .line 163
    .line 164
    move-object/from16 v18, v4

    .line 165
    .line 166
    const/16 v4, 0xf

    .line 167
    .line 168
    invoke-direct {v2, v6, v4, v4}, LCUk;-><init>(Ljava/lang/String;II)V

    .line 169
    .line 170
    .line 171
    sput-object v2, LCUk;->z0:LCUk;

    .line 172
    .line 173
    new-instance v6, LCUk;

    .line 174
    .line 175
    const-string v4, "AUTOGENERATED"

    .line 176
    .line 177
    move-object/from16 v19, v2

    .line 178
    .line 179
    const/16 v2, 0x10

    .line 180
    .line 181
    invoke-direct {v6, v4, v2, v2}, LCUk;-><init>(Ljava/lang/String;II)V

    .line 182
    .line 183
    .line 184
    sput-object v6, LCUk;->A0:LCUk;

    .line 185
    .line 186
    new-instance v4, LCUk;

    .line 187
    .line 188
    const-string v2, "MY_STORY_VARIANT"

    .line 189
    .line 190
    move-object/from16 v20, v6

    .line 191
    .line 192
    const/16 v6, 0x11

    .line 193
    .line 194
    invoke-direct {v4, v2, v6, v6}, LCUk;-><init>(Ljava/lang/String;II)V

    .line 195
    .line 196
    .line 197
    sput-object v4, LCUk;->B0:LCUk;

    .line 198
    .line 199
    const/16 v2, 0x12

    .line 200
    .line 201
    new-array v2, v2, [LCUk;

    .line 202
    .line 203
    const/16 v16, 0x0

    .line 204
    .line 205
    aput-object v0, v2, v16

    .line 206
    .line 207
    const/4 v0, 0x1

    .line 208
    aput-object v1, v2, v0

    .line 209
    .line 210
    const/4 v0, 0x2

    .line 211
    aput-object v3, v2, v0

    .line 212
    .line 213
    const/4 v0, 0x3

    .line 214
    aput-object v5, v2, v0

    .line 215
    .line 216
    const/4 v0, 0x4

    .line 217
    aput-object v7, v2, v0

    .line 218
    .line 219
    const/4 v0, 0x5

    .line 220
    aput-object v9, v2, v0

    .line 221
    .line 222
    const/4 v0, 0x6

    .line 223
    aput-object v11, v2, v0

    .line 224
    .line 225
    const/4 v0, 0x7

    .line 226
    aput-object v13, v2, v0

    .line 227
    .line 228
    const/16 v0, 0x8

    .line 229
    .line 230
    aput-object v15, v2, v0

    .line 231
    .line 232
    const/16 v0, 0x9

    .line 233
    .line 234
    aput-object v14, v2, v0

    .line 235
    .line 236
    const/16 v0, 0xa

    .line 237
    .line 238
    aput-object v12, v2, v0

    .line 239
    .line 240
    const/16 v0, 0xb

    .line 241
    .line 242
    aput-object v10, v2, v0

    .line 243
    .line 244
    const/16 v0, 0xc

    .line 245
    .line 246
    aput-object v8, v2, v0

    .line 247
    .line 248
    const/16 v0, 0xd

    .line 249
    .line 250
    aput-object v17, v2, v0

    .line 251
    .line 252
    const/16 v0, 0xe

    .line 253
    .line 254
    aput-object v18, v2, v0

    .line 255
    .line 256
    const/16 v0, 0xf

    .line 257
    .line 258
    aput-object v19, v2, v0

    .line 259
    .line 260
    const/16 v0, 0x10

    .line 261
    .line 262
    aput-object v20, v2, v0

    .line 263
    .line 264
    aput-object v4, v2, v6

    .line 265
    .line 266
    sput-object v2, LCUk;->C0:[LCUk;

    .line 267
    .line 268
    return-void
.end method

.method public constructor <init>(Ljava/lang/String;II)V
    .locals 0

    .line 1
    invoke-direct {p0, p1, p2}, Ljava/lang/Enum;-><init>(Ljava/lang/String;I)V

    .line 2
    .line 3
    .line 4
    iput p3, p0, LCUk;->a:I

    .line 5
    .line 6
    return-void
.end method

.method public static valueOf(Ljava/lang/String;)LCUk;
    .locals 1

    .line 1
    const-class v0, LCUk;

    .line 2
    .line 3
    invoke-static {v0, p0}, Ljava/lang/Enum;->valueOf(Ljava/lang/Class;Ljava/lang/String;)Ljava/lang/Enum;

    .line 4
    .line 5
    .line 6
    move-result-object p0

    .line 7
    check-cast p0, LCUk;

    .line 8
    .line 9
    return-object p0
.end method

.method public static values()[LCUk;
    .locals 1

    .line 1
    sget-object v0, LCUk;->C0:[LCUk;

    .line 2
    .line 3
    invoke-virtual {v0}, [LCUk;->clone()Ljava/lang/Object;

    .line 4
    .line 5
    .line 6
    move-result-object v0

    .line 7
    check-cast v0, [LCUk;

    .line 8
    .line 9
    return-object v0
.end method


# virtual methods
.method public final a()I
    .locals 1

    .line 1
    iget v0, p0, LCUk;->a:I

    .line 2
    .line 3
    return v0
.end method
