package defpackage;

import java.util.ArrayList;

/* renamed from: tg7  reason: default package and case insensitive filesystem */
/* loaded from: classes8.dex */
public abstract class AbstractC46709tg7 extends AbstractC12565Tv8 implements InterfaceC9571Pca {
    public Boolean A;
    public Long A0;
    public Boolean A1;
    public Boolean B;
    public Long B0;
    public Boolean B1;
    public String C;
    public Long C0;
    public Boolean C1;
    public String D;
    public Long D0;
    public Boolean D1;
    public String E;
    public Long E0;
    public Boolean E1;
    public Long F;
    public Long F0;
    public Long F1;
    public String G;
    public Long G0;
    public Long G1;
    public Long H;
    public Long H0;
    public String H1;
    public String I;
    public String I0;
    public Long I1;

    /* renamed from: J  reason: collision with root package name */
    public String f268J;
    public String J0;
    public Long J1;
    public String K;
    public String K0;
    public String K1;
    public String L;
    public String L0;
    public String L1;
    public Boolean M;
    public String M0;
    public Boolean M1;
    public Boolean N;
    public String N0;
    public Boolean N1;
    public Boolean O;
    public String O0;
    public String O1;
    public Boolean P;
    public String P0;
    public Boolean P1;
    public Long Q;
    public SL8 Q0;
    public Boolean Q1;
    public EnumC45173sg2 R;
    public Boolean R0;
    public Boolean R1;
    public Boolean S;
    public Long S0;
    public Long S1;
    public Boolean T;
    public Long T0;
    public Boolean T1;
    public Boolean U;
    public Long U0;
    public Boolean U1;
    public Boolean V;
    public String V0;
    public Double V1;
    public String W;
    public Boolean W0;
    public EnumC23513eaj W1;
    public Long X;
    public String X0;
    public String X1;
    public String Y;
    public String Y0;
    public Boolean Y1;
    public Long Z;
    public Long Z0;
    public Boolean Z1;
    public String a0;
    public String a1;
    public C11899Stm a2;
    public Boolean b0;
    public String b1;
    public ArrayList b2;
    public EnumC5668Ixj c0;
    public Boolean c1;
    public Double d0;
    public Boolean d1;
    public Boolean e0;
    public Boolean e1;
    public Boolean f0;
    public Long f1;
    public WVf g;
    public Long g0;
    public Long g1;
    public EnumC54164yXf h;
    public EnumC14830Xkd h0;
    public Boolean h1;
    public Long i;
    public EnumC55795zbg i0;
    public Boolean i1;
    public Long j;
    public Double j0;
    public Boolean j1;
    public Boolean k;
    public KM8 k0;
    public Boolean k1;
    public Boolean l;
    public Long l0;
    public EnumC20071cL8 l1;
    public Long m;
    public Long m0;
    public Long m1;
    public Long n;
    public Long n0;
    public Long n1;
    public Long o;
    public Long o0;
    public Long o1;
    public EnumC42640r1e p;
    public Long p0;
    public Long p1;
    public Boolean q;
    public Long q0;
    public Long q1;
    public Boolean r;
    public Long r0;
    public String r1;
    public Long s;
    public Long s0;
    public String s1;
    public Boolean t;
    public Long t0;
    public String t1;
    public Long u;
    public Long u0;
    public Boolean u1;
    public String v;
    public Long v0;
    public Boolean v1;
    public Long w;
    public Long w0;
    public Boolean w1;
    public Long x;
    public Long x0;
    public Boolean x1;
    public Long y;
    public Long y0;
    public Boolean y1;
    public Long z;
    public Long z0;
    public Boolean z1;

    @Override // defpackage.InterfaceC9571Pca
    public final Double a() {
        return this.V1;
    }

    public final void g(C11899Stm c11899Stm) {
        this.a2 = new C11899Stm(c11899Stm);
    }
}
