package defpackage;

/* renamed from: dLd  reason: default package and case insensitive filesystem */
/* loaded from: classes6.dex */
public final class C21611dLd {
    public static final H9n A;
    public static final H9n A0;
    public static final H9n B;
    public static final H9n B0;
    public static final H9n C;
    public static final H9n C0;
    public static final H9n D;
    public static final H9n D0;
    public static final H9n E;
    public static final H9n E0;
    public static final H9n F;
    public static final H9n F0;
    public static final H9n G;
    public static final H9n G0;
    public static final H9n H;
    public static final C38953ocl H0;
    public static final H9n I;
    public static final C38953ocl I0;

    /* renamed from: J  reason: collision with root package name */
    public static final H9n f170J;
    public static final H9n J0;
    public static final H9n K;
    public static final H9n L;
    public static final H9n M;
    public static final H9n N;
    public static final H9n O;
    public static final H9n P;
    public static final H9n Q;
    public static final H9n R;
    public static final H9n S;
    public static final H9n T;
    public static final H9n U;
    public static final H9n V;
    public static final H9n W;
    public static final H9n X;
    public static final H9n Y;
    public static final H9n Z;
    public static final C38953ocl a;
    public static final H9n a0;
    public static final C38953ocl b;
    public static final H9n b0;
    public static final C38953ocl c;
    public static final H9n c0;
    public static final C38953ocl d;
    public static final H9n d0;
    public static final C38953ocl e;
    public static final H9n e0;
    public static final H9n f;
    public static final H9n f0;
    public static final H9n g;
    public static final H9n g0;
    public static final H9n h;
    public static final H9n h0;
    public static final H9n i;
    public static final H9n i0;
    public static final H9n j;
    public static final H9n j0;
    public static final H9n k;
    public static final H9n k0;
    public static final H9n l;
    public static final H9n l0;
    public static final H9n m;
    public static final H9n m0;
    public static final H9n n;
    public static final H9n n0;
    public static final H9n o;
    public static final H9n o0;
    public static final H9n p;
    public static final H9n p0;
    public static final H9n q;
    public static final H9n q0;
    public static final H9n r;
    public static final H9n r0;
    public static final H9n s;
    public static final H9n s0;
    public static final H9n t;
    public static final H9n t0;
    public static final H9n u;
    public static final H9n u0;
    public static final H9n v;
    public static final H9n v0;
    public static final H9n w;
    public static final H9n w0;
    public static final H9n x;
    public static final H9n x0;
    public static final H9n y;
    public static final H9n y0;
    public static final H9n z;
    public static final H9n z0;

    static {
        XKd xKd = XKd.i;
        C53387y23 c53387y23 = new C53387y23();
        c53387y23.d = 4L;
        int i2 = c53387y23.a;
        c53387y23.e = 2L;
        c53387y23.a = i2 | 12;
        a = new C38953ocl("CHAT_MENTIONS", xKd, c53387y23);
        b = new C38953ocl("SNAPCHAT_PROVIDED_CHAT_WALLPAPER_LIST", C18542bLd.i, new MCj());
        c = new C38953ocl("FF_SMART_CTA_LENS_CONFIGURATION", YKd.i, new C52004x84());
        C17007aLd c17007aLd = C17007aLd.i;
        C54047ySi c54047ySi = new C54047ySi();
        c54047ySi.b = false;
        c54047ySi.a |= 1;
        c54047ySi.c = new int[0];
        C52513xSi c52513xSi = new C52513xSi();
        c52513xSi.b = 0;
        int i3 = c52513xSi.a;
        c52513xSi.c = 0;
        c52513xSi.d = 0;
        c52513xSi.a = i3 | 7;
        c54047ySi.d = c52513xSi;
        d = new C38953ocl("SHARING_DRAWER_CONFIG", c17007aLd, c54047ySi);
        C20076cLd c20076cLd = C20076cLd.i;
        C19859cCl c19859cCl = new C19859cCl();
        c19859cCl.b = false;
        int i4 = c19859cCl.a;
        c19859cCl.c = false;
        c19859cCl.d = 3;
        c19859cCl.e = 0;
        c19859cCl.f = 5;
        c19859cCl.g = 1.5f;
        c19859cCl.a = i4 | 63;
        e = new C38953ocl("TIMEZONE_IN_CHAT_HEADER", c20076cLd, c19859cCl);
        Boolean bool = Boolean.FALSE;
        f = new H9n("STORY_VIEWING_MODULE_ON_FEED", (Object) bool);
        g = new H9n("STREAKS_EXPIRATION_TIMER_V2", (Object) 12);
        h = new H9n("CHAT_TEXT_MESSAGE_PLUGIN", (Object) bool);
        i = new H9n("CHAT_WARMUP_COMPOSER", (Object) bool);
        j = new H9n("CHAT_WARMUP_ON_INFLATION", (Object) bool);
        k = new H9n("ENABLED_DWEB_UPSELL_PLUGIN", (Object) bool);
        l = new H9n("SHOW_CONTACTS_IN_NEW_CHAT", (Object) bool);
        m = new H9n("CHAT_MESSAGE_RELEASE_CHECK", (Object) bool);
        n = new H9n("FORWARDING_IN_CHAT", (Object) bool);
        o = new H9n("FORWARDING_IN_CHAT_CTA", (Object) bool);
        p = new H9n("STREAK_RESTORE_ENABLED", (Object) bool);
        q = new H9n("URL_PREVIEW_SERVICE_REPORT_SENDER_ENABLED", (Object) bool);
        r = new H9n("CHAT_WALLPAPER_IN_APP_REPORT", (Object) bool);
        s = new H9n("CHAT_MEDIA_USE_CONTENTURI", (Object) bool);
        t = new H9n("ENABLE_CBM_FOR_MINORS", (Object) bool);
        u = new H9n("SAVE_STORY_IN_CHAT_ENABLED", (Object) bool);
        v = new H9n("SPOTLIGHT_SHARE_FORWARDING_CTA_ENABLED", (Object) bool);
        w = new H9n("STORY_SHARE_FORWARDING_ENABLED", (Object) bool);
        x = new H9n("ANDROID_CREATE_GROUP_PAGE_V2", (Object) bool);
        y = new H9n("MAP_STORY_SNAP_FORWARDING_ENABLED", (Object) bool);
        z = new H9n("SNAPCHATTER_SHARE_FORWARDING", (Object) bool);
        A = new H9n("PUBLISHER_SNAP_FORWARDING_ENABLED", (Object) bool);
        Boolean bool2 = Boolean.TRUE;
        B = new H9n("FF_SMART_CTA_DTTR_ENABLED", (Object) bool2);
        C = new H9n("FF_SMART_CTA_FULL_CAROUSEL_ENABLED", (Object) bool2);
        D = new H9n("FF_SMART_DELTA_FORCE_ENABLED", (Object) bool);
        E = new H9n("FF_SMART_CTA_TRIGGERS_EXCLUDE_LIST_ANDROID", (Object) "");
        F = new H9n("FORWARDING_PHONE_NUMBERS", (Object) bool);
        G = new H9n("TEXT_FORWARDING_ENABLED", (Object) bool);
        H = new H9n("CHAT_MEDIA_FORWARDING", (Object) bool);
        I = new H9n("VOICE_NOTE_FORWARDING_ENABLED", (Object) bool);
        f170J = new H9n("CHAT_MENTIONS_AUTO_SELECT_EXACT_ENABLED", (Object) bool);
        K = new H9n("SAVED_SNAPS_FORWARDING", (Object) bool);
        L = new H9n("CHAT_PARTICIPANT_FETCH_OPTIMIZATION", (Object) bool);
        M = new H9n("STICKER_FORWARDING_ENABLED", (Object) bool);
        N = new H9n("UNKNOWN_RELEASE_POLICY_KILLSWITCH", (Object) bool);
        O = new H9n("SNAP_PRO_STORY_SHARE_FORWARDING_ENABLED", (Object) bool);
        P = new H9n("bloops_unified_sharing_recipient_forward_enabled", (Object) bool);
        Q = new H9n("bloops_unified_sharing_recipient_forward_with_media_enabled", (Object) bool);
        R = new H9n("STORY_REPLY_DELETED_MEDIA_VIEWING", (Object) bool);
        S = new H9n("STORY_REPLY_MEDIA_DELETION", (Object) bool);
        T = new H9n("EXPRESSIVE_TEXT_GRABBER_THRESHOLD", (Object) Float.valueOf(200.0f));
        U = new H9n("EXPRESSIVE_TEXT_GRABBER_SENSITIVITY", (Object) Float.valueOf(50.0f));
        V = new H9n("CHAT_STICKER_MEMORY_OPTIMIZATION", (Object) bool);
        W = new H9n("MERLIN_SEARCH_ACTION_SUGGESTION", (Object) 0);
        X = new H9n("MESSAGE_LIST_DISABLE_LEFT_SWIPE_INTERCEPT_TOUCH", (Object) bool);
        Y = new H9n("EXPAND_INPUT_WHEN_TYPING", (Object) bool);
        Z = new H9n("STORY_MEDIA_REDOWNLOAD_FIX", (Object) bool);
        Boolean bool3 = Boolean.FALSE;
        a0 = new H9n("WALLPAPER_CAMERAROLL_MEDIA_ACCESS", (Object) bool3);
        b0 = new H9n("SERVER_SENDER_COLOR_CURRENT_USER", (Object) bool3);
        c0 = new H9n("CHAT_WALLPAPER_FOR_EVERYONE", (Object) bool3);
        d0 = new H9n("ENABLE_WHO_CAN_CONTACT_ME_EVERYONE", (Object) bool2);
        e0 = new H9n("CHAT_BACK_ARROW_REVAMP_ANDROID", (Object) bool3);
        f0 = new H9n("ENABLE_TOP_GROUPS", (Object) bool3);
        g0 = new H9n("ENABLE_TOP_GROUPS_EMOJI", (Object) bool3);
        h0 = new H9n("ST_TOP_GROUPS_DISPLAY", (Object) "HIDE");
        i0 = new H9n("UNICON_CHAT_MEDIA_BATCH_PLUGIN", (Object) bool3);
        j0 = new H9n("ENABLE_PLACES_SHARE_FORWARDING", (Object) bool3);
        k0 = new H9n("ENABLE_PLACES_SHARE_FORWARDING_CTA", (Object) bool3);
        l0 = new H9n("ANDROID_SAVED_IN_CHAT_MIGRATE_PLUGIN", (Object) bool3);
        m0 = new H9n("FF_SHORTCUT_SENT", (Object) bool3);
        n0 = new H9n("MESSAGING_NON_PARTICIPANT_MENTION_SENDER", (Object) bool2);
        o0 = new H9n("CHAT_VIDEO_THUMBNAIL_PLAYBACK_OPTIMIZATION", (Object) 0);
        p0 = new H9n("GROUP_STREAKS_MAX_GROUP_SIZE", (Object) 8);
        q0 = new H9n("FEED_SHORTCUT_LOADING_POSITION", (Object) 0);
        r0 = new H9n("MERLIN_FORWARDING_ENABLED", (Object) bool3);
        s0 = new H9n("MESSAGING_NON_PARTICIPANT_MENTION_RECEIVER", (Object) bool3);
        t0 = new H9n("ENABLE_CONTINUOUS_PLAYBACK_FOR_BUNDLED_SNAPS", (Object) bool3);
        u0 = new H9n("SAVED_STORY_MEDIA_SNAPDOC", (Object) bool3);
        v0 = new H9n("COMMUNITY_GROUP_CHAT_VIEWING_CONFIG", (Object) bool3);
        w0 = new H9n("ANDROID_ENABLE_SAVE_CTA_PLUGIN", (Object) bool3);
        x0 = new H9n("ANDROID_ENABLE_FORWARD_CTA_PLUGIN", (Object) bool3);
        y0 = new H9n("ANDROID_ENABLE_TEXT_FORWARD_CTA_PLUGIN", (Object) bool3);
        z0 = new H9n("UNICON_CHAT_MEDIA_CAROUSEL", (Object) bool3);
        A0 = new H9n("UNICON_WAIT_FOR_ALL_MEDIA_UNPRESERVE", (Object) bool3);
        B0 = new H9n("SPOTLIGHT_SHARE_ENABLE_CHAT_REPLY_ANDROID", (Object) bool3);
        C0 = new H9n("ANDROID_ENABLE_BELOW_MESSAGE_ACCESSORIES_PLUGIN", (Object) bool3);
        D0 = new H9n("ANDROID_ENABLE_VOICE_NOTE_STORY_REPLY", (Object) bool3);
        E0 = new H9n("SHORTCUT_PERF_IMPROVEMENTS", (Object) bool3);
        F0 = new H9n("FRIENDS_FEED_STATE_LOGGING_ENABLED", (Object) bool3);
        G0 = new H9n("FRIENDS_FEED_STATE_LOGGING_CELL_STATE_COUNT", (Object) 20);
        ZKd zKd = ZKd.i;
        YEd yEd = new YEd();
        yEd.a = new XEd();
        yEd.c = new XEd();
        yEd.b = new XEd();
        H0 = new C38953ocl("MERLIN_JIT_CONFIG", zKd, yEd);
        WKd wKd = WKd.i;
        YR3 yr3 = new YR3();
        yr3.b = false;
        yr3.a |= 1;
        yr3.c = false;
        yr3.a |= 2;
        yr3.d = false;
        yr3.a |= 4;
        I0 = new C38953ocl("CG_COMMUNITIES_GROUP_CHAT", wKd, yr3);
        J0 = new H9n("ANDROID_ACTION_MENU_V2", (Object) bool3);
    }
}
