package defpackage;

import com.amazon.identity.auth.device.datastore.DatabaseHelper;
import com.coremedia.iso.boxes.UserBox;
import com.google.gson.annotations.SerializedName;
import java.util.ArrayList;
import java.util.List;

/* renamed from: ook  reason: default package and case insensitive filesystem */
/* loaded from: classes8.dex */
public class C39251ook {
    @SerializedName("shouldAutoGenerateSnapKitSticker")
    private final boolean A;
    @SerializedName("unlockableId")
    private final String B;
    @SerializedName("isSponsored")
    private final boolean C;
    @SerializedName("isGameSnippetSticker")
    private final boolean D;
    @SerializedName("index")
    private final int E;
    @SerializedName("stickerCount")
    private final int F;
    @SerializedName("stickerLocation")
    private final NG9 G;
    @SerializedName("capturedSnapSource")
    private final String H;
    @SerializedName("capturedTimestamp")
    private final long I;
    @SerializedName("stickerIds")

    /* renamed from: J  reason: collision with root package name */
    private final List<String> f247J;
    @SerializedName("snapProStoryReplyQuotedUserId")
    private final String K;
    @SerializedName("stickerCanvasId")
    private final String L;
    @SerializedName("tappableX")
    @Deprecated
    private final double M;
    @SerializedName("tappableY")
    @Deprecated
    private final double N;
    @SerializedName("tappableRelativeWidth")
    @Deprecated
    private final double O;
    @SerializedName("tappableRelativeHeight")
    @Deprecated
    private final double P;
    @SerializedName("appId")
    private final String Q;
    @SerializedName("appShareInfo")
    private final String R;
    @SerializedName("conversationId")
    private final String S;
    @SerializedName("distanceFromCaptureLocation")
    private final Double T;
    @SerializedName("venueCameFromSearch")
    private final boolean U;
    @SerializedName("hasDifferentTappableBounds")
    private final boolean V;
    @SerializedName("startTimeMs")
    private final int W;
    @SerializedName("endTimeMs")
    private final int X;
    @SerializedName("isTimed")
    private final boolean Y;
    @SerializedName(UserBox.TYPE)
    private final String Z;
    @SerializedName(alternate = {"a"}, value = DatabaseHelper.authorizationToken_Type)
    private final int a;
    @SerializedName("customText")
    private final String a0;
    @SerializedName(alternate = {"b"}, value = "isRecent")
    private final boolean b;
    @SerializedName("commerceStickerStyle")
    private final C27813hO3 b0;
    @SerializedName(alternate = {"c"}, value = "isFromSearch")
    private final boolean c;
    @SerializedName("tappableStickerElements")
    private final List<C48331ujl> c0;
    @SerializedName("isAutoGenerated")
    private final boolean d;
    @SerializedName("base64CtItem")
    private final String d0;
    @SerializedName(alternate = {"d"}, value = "isGeoSticker")
    private final boolean e;
    @SerializedName("forceCenterInParent")
    private final boolean e0;
    @SerializedName(alternate = {"e"}, value = "emojiCode")
    private final String f;
    @SerializedName("editCapabilities")
    private final List<MU7> f0;
    @SerializedName(alternate = {"f"}, value = "packId")
    private final String g;
    @SerializedName(alternate = {"g"}, value = "stickerId")
    private final String h;
    @SerializedName(alternate = {"h"}, value = "position")
    private final ZIf i;
    @SerializedName(alternate = {"i"}, value = "rotationInClockwiseDegrees")
    private final double j;
    @SerializedName(alternate = {"j"}, value = "scale")
    private final double k;
    @SerializedName(alternate = {"k"}, value = "width")
    private final double l;
    @SerializedName(alternate = {"l"}, value = "height")
    private final double m;
    @SerializedName(alternate = {"m"}, value = "relativeWidth")
    private final double n;
    @SerializedName(alternate = {"n"}, value = "relativeHeight")
    private final double o;
    @SerializedName(alternate = {"o"}, value = "isPinned")
    private final boolean p;
    @SerializedName(alternate = {"p"}, value = "normalizedTrajectory")
    private final PPl<C56390zze> q;
    @SerializedName(alternate = {"q"}, value = "alpha")
    private final float r;
    @SerializedName("infoStickerType")
    private final String s;
    @SerializedName("infoStickerStyle")
    private final XQa t;
    @SerializedName("isUnlockableSticker")
    private final boolean u;
    @SerializedName("isAnimated")
    private final boolean v;
    @SerializedName("externalSrcUrl")
    private final String w;
    @SerializedName("attachmentUrl")
    private final String x;
    @SerializedName("snapKitStickerFavIconUrl")
    private final String y;
    @SerializedName("snapKitStickerTitle")
    private final String z;

    public C39251ook(C37715nok c37715nok) {
        String uuid;
        this.a = c37715nok.a;
        this.b = c37715nok.b;
        this.c = c37715nok.c;
        this.d = c37715nok.d;
        this.e = c37715nok.e;
        this.u = c37715nok.D;
        this.v = c37715nok.E;
        this.f = c37715nok.f;
        this.g = c37715nok.g;
        this.h = c37715nok.h;
        this.w = c37715nok.i;
        this.x = c37715nok.j;
        this.y = c37715nok.k;
        this.z = c37715nok.l;
        this.A = c37715nok.m;
        if (c37715nok.u == null) {
            double d = c37715nok.p;
            if (d != 0.0d) {
                double d2 = c37715nok.q;
                if (d2 != 0.0d) {
                    c37715nok.u = new ZIf(c37715nok.n / ((float) Math.min(c37715nok.q, c37715nok.p)), c37715nok.o / ((float) Math.max(d2, d)));
                }
            }
            throw new IllegalStateException("Cant create normalized point if width and height are not set");
        }
        this.i = c37715nok.u;
        this.j = c37715nok.r;
        this.k = c37715nok.s;
        this.r = c37715nok.t;
        this.l = c37715nok.w;
        this.m = c37715nok.v;
        this.n = c37715nok.x;
        this.o = c37715nok.y;
        this.p = c37715nok.z;
        this.q = c37715nok.A;
        this.s = c37715nok.B;
        this.t = c37715nok.C;
        this.B = c37715nok.F;
        this.C = c37715nok.G;
        this.D = c37715nok.H;
        this.E = c37715nok.I;
        this.F = c37715nok.f241J;
        this.G = c37715nok.K;
        this.H = c37715nok.L;
        this.I = c37715nok.M;
        this.f247J = c37715nok.N;
        this.K = c37715nok.O;
        this.L = c37715nok.P;
        this.M = c37715nok.Q;
        this.N = c37715nok.R;
        this.O = c37715nok.S;
        this.P = c37715nok.T;
        this.c0 = c37715nok.U;
        this.Q = c37715nok.V;
        this.R = c37715nok.W;
        this.S = c37715nok.X;
        this.T = c37715nok.Y;
        this.U = c37715nok.Z;
        this.V = c37715nok.a0;
        this.Y = c37715nok.d0;
        this.W = c37715nok.b0;
        this.X = c37715nok.c0;
        this.a0 = c37715nok.h0;
        this.b0 = c37715nok.i0;
        this.d0 = c37715nok.j0;
        this.e0 = c37715nok.f0;
        this.f0 = c37715nok.g0;
        String str = c37715nok.e0;
        if (str != null && !str.isEmpty()) {
            uuid = c37715nok.e0;
        } else {
            uuid = AbstractC41139q2m.a().toString();
        }
        this.Z = uuid;
    }

    public final String A0() {
        return this.s;
    }

    public final boolean B0() {
        return this.p;
    }

    public final boolean C0() {
        return this.C;
    }

    public final PPl D0() {
        return this.q;
    }

    public final String E0() {
        return this.g;
    }

    public final ZIf F0() {
        return this.i;
    }

    public final double G0() {
        return this.o;
    }

    public final double H0() {
        return this.n;
    }

    public final double I0() {
        return this.j;
    }

    public final double J0() {
        return this.k;
    }

    public final String K0() {
        return this.y;
    }

    public final String L0() {
        return this.z;
    }

    public final String M0() {
        return this.K;
    }

    public final int N0() {
        return this.W;
    }

    public final String O0() {
        return this.L;
    }

    public final int P0() {
        return this.F;
    }

    public final String Q0() {
        return this.h;
    }

    public final List R0() {
        return this.f247J;
    }

    public final NG9 S0() {
        return this.G;
    }

    public final List T0() {
        List<C48331ujl> list = this.c0;
        if (list != null) {
            return list;
        }
        ArrayList arrayList = new ArrayList();
        arrayList.add(new C48331ujl(this.M, this.N, this.O, this.P));
        return arrayList;
    }

    public final int U0() {
        return this.a;
    }

    public final String V0() {
        return this.Z;
    }

    public final String W0() {
        return this.B;
    }

    public final double X0() {
        return this.l;
    }

    public final boolean Y0() {
        return this.V;
    }

    public final boolean Z0() {
        return this.v;
    }

    public final boolean a1() {
        return this.d;
    }

    public final boolean b1() {
        return this.c;
    }

    public final boolean c1() {
        return this.D;
    }

    public final boolean d1() {
        return this.e;
    }

    public final boolean e1() {
        return this.b;
    }

    public final boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null || getClass() != obj.getClass()) {
            return false;
        }
        C39251ook c39251ook = (C39251ook) obj;
        boolean z = this.p;
        if (z != c39251ook.p) {
            return false;
        }
        if (z) {
            Q58 q58 = new Q58();
            q58.e(this.q, c39251ook.q);
            return q58.a;
        }
        Q58 q582 = new Q58();
        q582.c(this.a, c39251ook.a);
        q582.f(this.b, c39251ook.b);
        q582.f(this.c, c39251ook.c);
        q582.f(this.d, c39251ook.d);
        q582.f(this.e, c39251ook.e);
        q582.e(this.f, c39251ook.f);
        q582.e(this.i, c39251ook.i);
        q582.a(this.j, c39251ook.j);
        q582.a(this.k, c39251ook.k);
        q582.b(this.r, c39251ook.r);
        q582.e(this.s, c39251ook.s);
        q582.e(this.t, c39251ook.t);
        q582.f(this.u, c39251ook.u);
        q582.f(this.v, c39251ook.v);
        q582.e(this.a0, c39251ook.a0);
        q582.e(this.w, c39251ook.w);
        q582.e(this.x, c39251ook.x);
        q582.e(this.y, c39251ook.y);
        q582.e(this.z, c39251ook.z);
        q582.f(this.A, c39251ook.A);
        q582.e(this.B, c39251ook.B);
        q582.f(this.C, c39251ook.C);
        q582.f(this.D, c39251ook.D);
        q582.c(this.E, c39251ook.E);
        q582.c(this.F, c39251ook.F);
        q582.e(this.G, c39251ook.G);
        q582.e(this.H, c39251ook.H);
        q582.d(this.I, c39251ook.I);
        q582.e(this.f247J, c39251ook.f247J);
        q582.e(this.K, c39251ook.K);
        q582.e(this.L, c39251ook.L);
        q582.a(this.M, c39251ook.M);
        q582.a(this.N, c39251ook.N);
        q582.a(this.O, c39251ook.O);
        q582.a(this.P, c39251ook.P);
        q582.e(this.Q, c39251ook.Q);
        q582.e(this.R, c39251ook.R);
        q582.e(this.S, c39251ook.S);
        q582.e(this.T, c39251ook.T);
        q582.f(this.U, c39251ook.U);
        q582.e(this.b0, c39251ook.b0);
        q582.e(this.d0, c39251ook.d0);
        q582.f(this.e0, c39251ook.e0);
        q582.e(this.f0, c39251ook.f0);
        List<C48331ujl> list = this.c0;
        if (list != null || c39251ook.c0 != null) {
            q582.e(list, c39251ook.T0());
        }
        return q582.a;
    }

    public final boolean f1() {
        return this.Y;
    }

    public final float g0() {
        return this.r;
    }

    public final boolean g1() {
        return this.u;
    }

    public final PPl h0() {
        PPl<C56390zze> pPl = this.q;
        if (pPl != null && !pPl.isEmpty()) {
            return this.q;
        }
        PPl pPl2 = new PPl(false);
        Double a = this.i.a();
        AbstractC47512uCa abstractC47512uCa = C7g.a;
        pPl2.b(0L, new C56390zze((float) Math.toRadians(this.j), (float) this.k, (float) a.doubleValue(), (float) this.i.b().doubleValue()));
        return pPl2;
    }

    public final boolean h1() {
        return this.U;
    }

    public final int hashCode() {
        C20509cda c20509cda = new C20509cda();
        c20509cda.c(this.a);
        c20509cda.f(this.b);
        c20509cda.f(this.c);
        c20509cda.f(this.d);
        c20509cda.f(this.e);
        c20509cda.e(this.f);
        c20509cda.e(this.g);
        c20509cda.e(this.h);
        c20509cda.e(this.i);
        c20509cda.a(this.j);
        c20509cda.a(this.k);
        c20509cda.b(this.r);
        c20509cda.a(this.l);
        c20509cda.a(this.m);
        c20509cda.a(this.n);
        c20509cda.a(this.o);
        c20509cda.f(this.p);
        c20509cda.e(this.q);
        c20509cda.e(this.s);
        c20509cda.e(this.t);
        c20509cda.f(this.u);
        c20509cda.f(this.v);
        c20509cda.e(this.a0);
        c20509cda.e(this.w);
        c20509cda.e(this.x);
        c20509cda.e(this.y);
        c20509cda.e(this.z);
        c20509cda.f(this.A);
        c20509cda.e(this.B);
        c20509cda.f(this.C);
        c20509cda.f(this.D);
        c20509cda.c(this.E);
        c20509cda.c(this.F);
        c20509cda.e(this.G);
        c20509cda.e(this.H);
        c20509cda.d(this.I);
        c20509cda.e(this.f247J);
        c20509cda.e(this.K);
        c20509cda.e(this.L);
        c20509cda.a(this.M);
        c20509cda.a(this.N);
        c20509cda.a(this.O);
        c20509cda.a(this.P);
        c20509cda.e(this.c0);
        c20509cda.e(this.Q);
        c20509cda.e(this.R);
        c20509cda.e(this.S);
        c20509cda.e(this.T);
        c20509cda.f(this.U);
        c20509cda.f(this.V);
        c20509cda.e(this.b0);
        c20509cda.e(this.d0);
        c20509cda.f(this.e0);
        c20509cda.e(this.f0);
        return c20509cda.a;
    }

    public final String i0() {
        return this.Q;
    }

    public final boolean i1() {
        return this.A;
    }

    public final String j0() {
        return this.R;
    }

    public final String k0() {
        return this.x;
    }

    public final String l0() {
        return this.d0;
    }

    public final String m0() {
        return this.H;
    }

    public final long n0() {
        return this.I;
    }

    public final C27813hO3 o0() {
        return this.b0;
    }

    public final String p0() {
        return this.S;
    }

    public final String q0() {
        return this.a0;
    }

    public final Double r0() {
        return this.T;
    }

    public final List s0() {
        return this.f0;
    }

    public final String t0() {
        return this.f;
    }

    public final String toString() {
        XSm E1 = AbstractC55790zbb.E1(this);
        E1.h(this.a, DatabaseHelper.authorizationToken_Type);
        E1.j("isRecent", this.b);
        E1.j("isFromSearch", this.c);
        E1.j("isAutoGenerated", this.d);
        E1.j("isGeoSticker", this.e);
        E1.m(this.f, "emojiCode");
        E1.m(this.g, "packId");
        E1.m(this.h, "stickerId");
        E1.m(this.i, "position");
        E1.d(this.j, "rotationInClockwiseDegrees");
        E1.d(this.k, "scale");
        E1.f("alpha", this.r);
        E1.d(this.l, "width");
        E1.d(this.m, "height");
        E1.d(this.n, "relativeWidth");
        E1.d(this.o, "relativeHeight");
        E1.j("isPinned", this.p);
        E1.j("isTimed", this.Y);
        E1.m(this.Z, UserBox.TYPE);
        E1.m(this.q, "timeTransforms");
        E1.m(this.s, "infoStickerType");
        E1.m(this.t, "infoStickerStyle");
        E1.j("isUnlockableSticker", this.u);
        E1.j("isAnimated", this.v);
        E1.m(this.a0, "customText");
        E1.m(this.w, "externalSrcUrl");
        E1.m(this.x, "attachmentUrl");
        E1.m(this.y, "snapKitStickerFavIconUrl");
        E1.m(this.z, "snapKitStickerTitle");
        E1.j("shouldAutoGenerateSnapKitSticker", this.A);
        E1.m(this.B, "unlockableId");
        E1.j("isSponsored", this.C);
        E1.j("isGameSnippetSticker", this.D);
        E1.h(this.E, "index");
        E1.h(this.F, "stickerCount");
        E1.m(this.G, "stickerLocation");
        E1.m(this.H, "capturedSnapSource");
        E1.e(this.I, "capturedTimestamp");
        E1.m(this.f247J, "stickerIds");
        E1.m(this.K, "snapProStoryReplyQuotedUserId");
        E1.m(this.L, "stickerCanvasId");
        E1.d(this.M, "tappableX");
        E1.d(this.N, "tappableY");
        E1.d(this.O, "tappableRelativeWidth");
        E1.d(this.P, "tappableRelativeHeight");
        E1.m(this.c0, "tappableStickerElements");
        E1.m(this.Q, "appId");
        E1.m(this.R, "appShareInfo");
        E1.m(this.S, "conversationId");
        E1.m(this.T, "distancefromCaptureLocation");
        E1.j("isVenueStickerFromSearch", this.U);
        E1.j("hasDifferentTappableBounds", this.V);
        E1.m(this.b0, "commerceStickerStyle");
        E1.m(this.d0, "base64CtItem");
        E1.j("forceCenterInParent", this.e0);
        E1.m(this.f0, "editCapabilities");
        return E1.toString();
    }

    public final int u0() {
        return this.X;
    }

    public final String v0() {
        return this.w;
    }

    public final boolean w0() {
        return this.e0;
    }

    public final double x0() {
        return this.m;
    }

    public final int y0() {
        return this.E;
    }

    public final XQa z0() {
        return this.t;
    }
}
