package defpackage;

import java.util.Map;
import java.util.Set;

/* renamed from: qJ4  reason: default package and case insensitive filesystem */
/* loaded from: classes8.dex */
public final class C41546qJ4 extends AbstractC49920vm1 implements InterfaceC33853lIc {
    public Boolean A;
    public EnumC40011pJ4 b;
    public String c;
    public Boolean d;
    public String e;
    public Boolean f;
    public Boolean g;
    public Boolean h;
    public EnumC49215vJ4 i;
    public Boolean j;
    public EnumC23860eoj k;
    public String l;
    public String m;
    public Boolean n;
    public Boolean o;
    public Long p;
    public String q;
    public EnumC10838Rcb r;
    public String s;
    public Boolean t;
    public Boolean u;
    public Boolean v;
    public Boolean w;
    public String x;
    public String y;
    public Long z;

    public C41546qJ4() {
    }

    @Override // defpackage.InterfaceC42467qug
    public final void c(C38303oC7 c38303oC7, Set set) {
        byte[] bArr = new byte[4];
        AbstractC39604p2m.O0(c38303oC7, 2, bArr, this.c, set);
        AbstractC39604p2m.O0(c38303oC7, 3, bArr, this.m, set);
        AbstractC39604p2m.O0(c38303oC7, 4, bArr, this.e, set);
        AbstractC39604p2m.L0(c38303oC7, 5, bArr, this.k, set);
        AbstractC39604p2m.O0(c38303oC7, 6, bArr, this.l, set);
        AbstractC39604p2m.J0(c38303oC7, 7, bArr, this.f, set);
        AbstractC39604p2m.J0(c38303oC7, 8, bArr, this.h, set);
        AbstractC39604p2m.J0(c38303oC7, 9, bArr, this.j, set);
        AbstractC39604p2m.M0(c38303oC7, 10, bArr, this.p, set);
        AbstractC39604p2m.L0(c38303oC7, 11, bArr, this.b, set);
        AbstractC39604p2m.L0(c38303oC7, 12, bArr, this.i, set);
        AbstractC39604p2m.J0(c38303oC7, 13, bArr, this.d, set);
        AbstractC39604p2m.J0(c38303oC7, 14, bArr, this.g, set);
        AbstractC39604p2m.J0(c38303oC7, 15, bArr, this.n, set);
        AbstractC39604p2m.O0(c38303oC7, 16, bArr, this.q, set);
        AbstractC39604p2m.L0(c38303oC7, 17, bArr, this.r, set);
        AbstractC39604p2m.O0(c38303oC7, 18, bArr, this.s, set);
        AbstractC39604p2m.J0(c38303oC7, 19, bArr, this.t, set);
        AbstractC39604p2m.J0(c38303oC7, 20, bArr, this.u, set);
        AbstractC39604p2m.J0(c38303oC7, 21, bArr, this.v, set);
        AbstractC39604p2m.J0(c38303oC7, 22, bArr, this.w, set);
        AbstractC39604p2m.O0(c38303oC7, 23, bArr, this.x, set);
        AbstractC39604p2m.M0(c38303oC7, 24, bArr, this.z, set);
        AbstractC39604p2m.O0(c38303oC7, 25, bArr, this.y, set);
        AbstractC39604p2m.J0(c38303oC7, 26, bArr, this.o, set);
        AbstractC39604p2m.J0(c38303oC7, 27, bArr, this.A, set);
        c38303oC7.j(bArr);
    }

    @Override // defpackage.InterfaceC33853lIc
    public final int d(Map map) {
        int i;
        EnumC49215vJ4 enumC49215vJ4;
        EnumC40011pJ4 enumC40011pJ4;
        EnumC23860eoj enumC23860eoj;
        EnumC10838Rcb enumC10838Rcb;
        Long l = (Long) map.get("deep_link_handling_id");
        this.z = l;
        if (l != null) {
            i = 1;
        } else {
            i = 0;
        }
        String str = (String) map.get("deep_link_url");
        this.y = str;
        if (str != null) {
            i++;
        }
        Boolean bool = (Boolean) map.get("has_lens_launch_data");
        this.o = bool;
        if (bool != null) {
            i++;
        }
        Boolean bool2 = (Boolean) map.get("is_draggable_sticker");
        this.A = bool2;
        if (bool2 != null) {
            i++;
        }
        Boolean bool3 = (Boolean) map.get("is_from_react_native_plugin");
        this.u = bool3;
        if (bool3 != null) {
            i++;
        }
        Boolean bool4 = (Boolean) map.get("is_spotlight_posting_permitted");
        this.t = bool4;
        if (bool4 != null) {
            i++;
        }
        Boolean bool5 = (Boolean) map.get("is_using_autogenerated_sticker");
        this.v = bool5;
        if (bool5 != null) {
            i++;
        }
        if (map.containsKey("kit_plugin_type")) {
            Object obj = map.get("kit_plugin_type");
            if (obj instanceof String) {
                enumC10838Rcb = EnumC10838Rcb.valueOf((String) obj);
            } else {
                enumC10838Rcb = (EnumC10838Rcb) obj;
            }
            this.r = enumC10838Rcb;
            i++;
        }
        String str2 = (String) map.get("o_auth_client_id");
        this.c = str2;
        if (str2 != null) {
            i++;
        }
        Boolean bool6 = (Boolean) map.get("requires_identity_web_view");
        this.w = bool6;
        if (bool6 != null) {
            i++;
        }
        String str3 = (String) map.get("snap_kit_application_id");
        this.m = str3;
        if (str3 != null) {
            i++;
        }
        String str4 = (String) map.get("snap_kit_attachment_url");
        this.e = str4;
        if (str4 != null) {
            i++;
        }
        if (map.containsKey("snap_kit_creative_kit_product")) {
            Object obj2 = map.get("snap_kit_creative_kit_product");
            if (obj2 instanceof String) {
                enumC23860eoj = EnumC23860eoj.valueOf((String) obj2);
            } else {
                enumC23860eoj = (EnumC23860eoj) obj2;
            }
            this.k = enumC23860eoj;
            i++;
        }
        String str5 = (String) map.get("snap_kit_creative_kit_version");
        this.l = str5;
        if (str5 != null) {
            i++;
        }
        Boolean bool7 = (Boolean) map.get("snap_kit_delete_attachment_url");
        this.f = bool7;
        if (bool7 != null) {
            i++;
        }
        Boolean bool8 = (Boolean) map.get("snap_kit_delete_caption");
        this.h = bool8;
        if (bool8 != null) {
            i++;
        }
        Boolean bool9 = (Boolean) map.get("snap_kit_delete_sticker");
        this.j = bool9;
        if (bool9 != null) {
            i++;
        }
        Long l2 = (Long) map.get("snap_kit_lens_id");
        this.p = l2;
        if (l2 != null) {
            i++;
        }
        String str6 = (String) map.get("snap_kit_scannable_lens_id");
        this.q = str6;
        if (str6 != null) {
            i++;
        }
        String str7 = (String) map.get("snap_kit_session_id");
        this.x = str7;
        if (str7 != null) {
            i++;
        }
        if (map.containsKey("snap_kit_share_type")) {
            Object obj3 = map.get("snap_kit_share_type");
            if (obj3 instanceof String) {
                enumC40011pJ4 = EnumC40011pJ4.valueOf((String) obj3);
            } else {
                enumC40011pJ4 = (EnumC40011pJ4) obj3;
            }
            this.b = enumC40011pJ4;
            i++;
        }
        if (map.containsKey("snap_kit_sticker_type")) {
            Object obj4 = map.get("snap_kit_sticker_type");
            if (obj4 instanceof String) {
                enumC49215vJ4 = EnumC49215vJ4.valueOf((String) obj4);
            } else {
                enumC49215vJ4 = (EnumC49215vJ4) obj4;
            }
            this.i = enumC49215vJ4;
            i++;
        }
        Boolean bool10 = (Boolean) map.get("snap_kit_with_attachment_url");
        this.d = bool10;
        if (bool10 != null) {
            i++;
        }
        Boolean bool11 = (Boolean) map.get("snap_kit_with_caption");
        this.g = bool11;
        if (bool11 != null) {
            i++;
        }
        Boolean bool12 = (Boolean) map.get("snap_kit_with_lens");
        this.n = bool12;
        if (bool12 != null) {
            i++;
        }
        String str8 = (String) map.get("topic_list");
        this.s = str8;
        if (str8 != null) {
            return i + 1;
        }
        return i;
    }

    public C41546qJ4(C41546qJ4 c41546qJ4) {
        this.b = c41546qJ4.b;
        this.c = c41546qJ4.c;
        this.d = c41546qJ4.d;
        this.e = c41546qJ4.e;
        this.f = c41546qJ4.f;
        this.g = c41546qJ4.g;
        this.h = c41546qJ4.h;
        this.i = c41546qJ4.i;
        this.j = c41546qJ4.j;
        this.k = c41546qJ4.k;
        this.l = c41546qJ4.l;
        this.m = c41546qJ4.m;
        this.n = c41546qJ4.n;
        this.o = c41546qJ4.o;
        this.p = c41546qJ4.p;
        this.q = c41546qJ4.q;
        this.r = c41546qJ4.r;
        this.s = c41546qJ4.s;
        this.t = c41546qJ4.t;
        this.u = c41546qJ4.u;
        this.v = c41546qJ4.v;
        this.w = c41546qJ4.w;
        this.x = c41546qJ4.x;
        this.y = c41546qJ4.y;
        this.z = c41546qJ4.z;
        this.A = c41546qJ4.A;
    }
}
