package defpackage;

import java.util.List;
import kotlin.jvm.functions.Function1;

/* renamed from: vzg  reason: default package and case insensitive filesystem */
/* loaded from: classes4.dex */
public final class C50259vzg extends AbstractC10863Rdb implements Function1 {
    public final /* synthetic */ boolean A0;
    public final /* synthetic */ boolean B0;
    public final /* synthetic */ String C0;
    public final /* synthetic */ long D0;
    public final /* synthetic */ long E0;
    public final /* synthetic */ Long F0;
    public final /* synthetic */ String G0;
    public final /* synthetic */ String H0;
    public final /* synthetic */ String I0;
    public final /* synthetic */ String J0;
    public final /* synthetic */ String K0;
    public final /* synthetic */ Long L0;
    public final /* synthetic */ String M0;
    public final /* synthetic */ Long N0;
    public final /* synthetic */ Long O0;
    public final /* synthetic */ String P0;
    public final /* synthetic */ String Q0;
    public final /* synthetic */ Long R0;
    public final /* synthetic */ String S0;
    public final /* synthetic */ Long T0;
    public final /* synthetic */ Long U0;
    public final /* synthetic */ String V0;
    public final /* synthetic */ Boolean W0;
    public final /* synthetic */ String X;
    public final /* synthetic */ byte[] X0;
    public final /* synthetic */ Long Y;
    public final /* synthetic */ byte[] Y0;
    public final /* synthetic */ EnumC31716jw8 Z;
    public final /* synthetic */ String Z0;
    public final /* synthetic */ String a1;
    public final /* synthetic */ String b1;
    public final /* synthetic */ Boolean c1;
    public final /* synthetic */ long d;
    public final /* synthetic */ Long d1;
    public final /* synthetic */ String e;
    public final /* synthetic */ String e1;
    public final /* synthetic */ long f;
    public final /* synthetic */ Long f1;
    public final /* synthetic */ long g;
    public final /* synthetic */ List g1;
    public final /* synthetic */ String h;
    public final /* synthetic */ String h1;
    public final /* synthetic */ String i;
    public final /* synthetic */ Long i1;
    public final /* synthetic */ C1253By8 j;
    public final /* synthetic */ EnumC8849Nyg k;
    public final /* synthetic */ String n1;
    public final /* synthetic */ String o1;
    public final /* synthetic */ byte[] p1;
    public final /* synthetic */ String t;
    public final /* synthetic */ String y0;
    public final /* synthetic */ boolean z0;
    public final /* synthetic */ String j1 = null;
    public final /* synthetic */ String k1 = null;
    public final /* synthetic */ String l1 = null;
    public final /* synthetic */ String m1 = null;

    /* JADX WARN: 'super' call moved to the top of the method (can break code semantics) */
    public C50259vzg(long j, String str, long j2, long j3, String str2, String str3, C1253By8 c1253By8, EnumC8849Nyg enumC8849Nyg, String str4, String str5, Long l, EnumC31716jw8 enumC31716jw8, String str6, boolean z, boolean z2, boolean z3, String str7, long j4, long j5, Long l2, String str8, String str9, String str10, String str11, String str12, Long l3, String str13, Long l4, Long l5, String str14, String str15, Long l6, String str16, Long l7, Long l8, String str17, Boolean bool, byte[] bArr, byte[] bArr2, String str18, String str19, String str20, Boolean bool2, Long l9, String str21, Long l10, List list, String str22, Long l11, String str23, String str24, byte[] bArr3) {
        super(1);
        this.d = j;
        this.e = str;
        this.f = j2;
        this.g = j3;
        this.h = str2;
        this.i = str3;
        this.j = c1253By8;
        this.k = enumC8849Nyg;
        this.t = str4;
        this.X = str5;
        this.Y = l;
        this.Z = enumC31716jw8;
        this.y0 = str6;
        this.z0 = z;
        this.A0 = z2;
        this.B0 = z3;
        this.C0 = str7;
        this.D0 = j4;
        this.E0 = j5;
        this.F0 = l2;
        this.G0 = str8;
        this.H0 = str9;
        this.I0 = str10;
        this.J0 = str11;
        this.K0 = str12;
        this.L0 = l3;
        this.M0 = str13;
        this.N0 = l4;
        this.O0 = l5;
        this.P0 = str14;
        this.Q0 = str15;
        this.R0 = l6;
        this.S0 = str16;
        this.T0 = l7;
        this.U0 = l8;
        this.V0 = str17;
        this.W0 = bool;
        this.X0 = bArr;
        this.Y0 = bArr2;
        this.Z0 = str18;
        this.a1 = str19;
        this.b1 = str20;
        this.c1 = bool2;
        this.d1 = l9;
        this.e1 = str21;
        this.f1 = l10;
        this.g1 = list;
        this.h1 = str22;
        this.i1 = l11;
        this.n1 = str23;
        this.o1 = str24;
        this.p1 = bArr3;
    }

    @Override // kotlin.jvm.functions.Function1
    public final Object invoke(Object obj) {
        String str;
        InterfaceC55874zek interfaceC55874zek = (InterfaceC55874zek) obj;
        interfaceC55874zek.b(0, Long.valueOf(this.d));
        interfaceC55874zek.bindString(1, this.e);
        interfaceC55874zek.b(2, Long.valueOf(this.f));
        interfaceC55874zek.b(3, Long.valueOf(this.g));
        interfaceC55874zek.bindString(4, this.h);
        interfaceC55874zek.bindString(5, this.i);
        C1253By8 c1253By8 = this.j;
        interfaceC55874zek.b(6, (Long) ((C37986nzg) c1253By8.c).a.o(this.k));
        interfaceC55874zek.bindString(7, this.t);
        interfaceC55874zek.bindString(8, this.X);
        interfaceC55874zek.b(9, this.Y);
        C37986nzg c37986nzg = (C37986nzg) c1253By8.c;
        interfaceC55874zek.b(10, (Long) c37986nzg.b.o(this.Z));
        interfaceC55874zek.bindString(11, this.y0);
        interfaceC55874zek.g(12, Boolean.valueOf(this.z0));
        interfaceC55874zek.g(13, Boolean.valueOf(this.A0));
        interfaceC55874zek.g(14, Boolean.valueOf(this.B0));
        interfaceC55874zek.bindString(15, this.C0);
        interfaceC55874zek.b(16, Long.valueOf(this.D0));
        interfaceC55874zek.b(17, Long.valueOf(this.E0));
        interfaceC55874zek.b(18, this.F0);
        interfaceC55874zek.bindString(19, this.G0);
        interfaceC55874zek.bindString(20, this.H0);
        interfaceC55874zek.bindString(21, this.I0);
        interfaceC55874zek.bindString(22, this.J0);
        interfaceC55874zek.bindString(23, this.K0);
        interfaceC55874zek.b(24, this.L0);
        interfaceC55874zek.bindString(25, this.M0);
        interfaceC55874zek.b(26, this.N0);
        interfaceC55874zek.b(27, this.O0);
        interfaceC55874zek.bindString(28, this.P0);
        interfaceC55874zek.bindString(29, this.Q0);
        interfaceC55874zek.b(30, this.R0);
        interfaceC55874zek.bindString(31, this.S0);
        interfaceC55874zek.b(32, this.T0);
        interfaceC55874zek.b(33, this.U0);
        interfaceC55874zek.bindString(34, this.V0);
        interfaceC55874zek.g(35, this.W0);
        interfaceC55874zek.i(36, this.X0);
        interfaceC55874zek.i(37, this.Y0);
        interfaceC55874zek.bindString(38, this.Z0);
        interfaceC55874zek.bindString(39, this.a1);
        interfaceC55874zek.bindString(40, this.b1);
        interfaceC55874zek.g(41, this.c1);
        interfaceC55874zek.b(42, this.d1);
        interfaceC55874zek.bindString(43, this.e1);
        interfaceC55874zek.b(44, this.f1);
        List list = this.g1;
        if (list != null) {
            str = (String) c37986nzg.c.o(list);
        } else {
            str = null;
        }
        interfaceC55874zek.bindString(45, str);
        interfaceC55874zek.bindString(46, this.h1);
        interfaceC55874zek.b(47, this.i1);
        interfaceC55874zek.bindString(48, this.j1);
        interfaceC55874zek.bindString(49, this.k1);
        interfaceC55874zek.bindString(50, this.l1);
        interfaceC55874zek.bindString(51, this.m1);
        interfaceC55874zek.bindString(52, this.n1);
        interfaceC55874zek.bindString(53, this.o1);
        interfaceC55874zek.i(54, this.p1);
        return C38218o8m.a;
    }
}
