package defpackage;

/* renamed from: CUk  reason: default package */
/* loaded from: classes8.dex */
public enum CUk implements I58 {
    MY(0),
    OUR(1),
    USER(2),
    BRAND(3),
    AD(4),
    DYNAMIC(5),
    GROUP(6),
    PROMOTED_STORY(7),
    LIVE_STREAMING(8),
    DISCOVER(9),
    PUBLISHER(10),
    SHOW(11),
    IMPALA(12),
    THIRD_PARTY_APP(13),
    MIXED(14),
    COMMUNITY(15),
    AUTOGENERATED(16),
    MY_STORY_VARIANT(17);
    
    public final int a;

    CUk(int i) {
        this.a = i;
    }

    @Override // defpackage.I58
    public final int a() {
        return this.a;
    }
}
