package defpackage;

import com.snapchat.client.messaging.Tweaks;
import java.util.concurrent.TimeUnit;
import org.opencv.imgproc.Imgproc;

/* JADX WARN: Enum visitor error
jadx.core.utils.exceptions.JadxRuntimeException: Init of enum g uses external variables
	at jadx.core.dex.visitors.EnumVisitor.createEnumFieldByConstructor(EnumVisitor.java:444)
	at jadx.core.dex.visitors.EnumVisitor.processEnumFieldByField(EnumVisitor.java:368)
	at jadx.core.dex.visitors.EnumVisitor.processEnumFieldByWrappedInsn(EnumVisitor.java:333)
	at jadx.core.dex.visitors.EnumVisitor.extractEnumFieldsFromFilledArray(EnumVisitor.java:318)
	at jadx.core.dex.visitors.EnumVisitor.extractEnumFieldsFromInsn(EnumVisitor.java:258)
	at jadx.core.dex.visitors.EnumVisitor.extractEnumFieldsFromInvoke(EnumVisitor.java:289)
	at jadx.core.dex.visitors.EnumVisitor.extractEnumFieldsFromInsn(EnumVisitor.java:262)
	at jadx.core.dex.visitors.EnumVisitor.convertToEnum(EnumVisitor.java:151)
	at jadx.core.dex.visitors.EnumVisitor.visit(EnumVisitor.java:100)
 */
/* JADX WARN: Failed to restore enum class, 'enum' modifier and super class removed */
/* renamed from: DAf  reason: default package */
/* loaded from: classes.dex */
public final class DAf implements InterfaceC55783zb4 {
    public static final DAf A0;
    public static final DAf A1;
    public static final DAf A2;
    public static final DAf B0;
    public static final DAf B1;
    public static final DAf B2;
    public static final DAf C0;
    public static final DAf C1;
    public static final DAf C2;
    public static final DAf D0;
    public static final DAf D1;
    public static final DAf D2;
    public static final DAf E0;
    public static final DAf E1;
    public static final DAf E2;
    public static final DAf F0;
    public static final DAf F1;
    public static final DAf F2;
    public static final DAf G0;
    public static final DAf G1;
    public static final DAf G2;
    public static final DAf H0;
    public static final DAf H1;
    public static final DAf H2;
    public static final DAf I0;
    public static final DAf I1;
    public static final DAf I2;
    public static final DAf J0;
    public static final DAf J1;
    public static final DAf J2;
    public static final DAf K0;
    public static final DAf K1;
    public static final DAf K2;
    public static final DAf L0;
    public static final DAf L1;
    public static final DAf L2;
    public static final DAf M0;
    public static final DAf M1;
    public static final DAf M2;
    public static final DAf N0;
    public static final DAf N1;
    public static final DAf N2;
    public static final DAf O0;
    public static final DAf O1;
    public static final DAf O2;
    public static final DAf P0;
    public static final DAf P1;
    public static final DAf P2;
    public static final DAf Q0;
    public static final DAf Q1;
    public static final DAf Q2;
    public static final DAf R0;
    public static final DAf R1;
    public static final DAf R2;
    public static final DAf S0;
    public static final DAf S1;
    public static final DAf S2;
    public static final DAf T0;
    public static final DAf T1;
    public static final DAf T2;
    public static final DAf U0;
    public static final DAf U1;
    public static final DAf U2;
    public static final DAf V0;
    public static final DAf V1;
    public static final DAf V2;
    public static final DAf W0;
    public static final DAf W1;
    public static final /* synthetic */ DAf[] W2;
    public static final DAf X;
    public static final DAf X0;
    public static final DAf X1;
    public static final DAf Y;
    public static final DAf Y0;
    public static final DAf Y1;
    public static final DAf Z;
    public static final DAf Z0;
    public static final DAf Z1;
    public static final DAf a1;
    public static final DAf a2;
    public static final DAf b1;
    public static final DAf b2;
    public static final DAf c1;
    public static final DAf c2;
    public static final DAf d1;
    public static final DAf d2;
    public static final DAf e1;
    public static final DAf e2;
    public static final DAf f1;
    public static final DAf f2;
    public static final DAf g;
    public static final DAf g1;
    public static final DAf g2;
    public static final DAf h;
    public static final DAf h1;
    public static final DAf h2;
    public static final DAf i;
    public static final DAf i1;
    public static final DAf i2;
    public static final DAf j;
    public static final DAf j1;
    public static final DAf j2;
    public static final DAf k;
    public static final DAf k1;
    public static final DAf k2;
    public static final DAf l1;
    public static final DAf l2;
    public static final DAf m1;
    public static final DAf m2;
    public static final DAf n1;
    public static final DAf n2;
    public static final DAf o1;
    public static final DAf o2;
    public static final DAf p1;
    public static final DAf p2;
    public static final DAf q1;
    public static final DAf q2;
    public static final DAf r1;
    public static final DAf r2;
    public static final DAf s1;
    public static final DAf s2;
    public static final DAf t;
    public static final DAf t1;
    public static final DAf t2;
    public static final DAf u1;
    public static final DAf u2;
    public static final DAf v1;
    public static final DAf v2;
    public static final DAf w1;
    public static final DAf w2;
    public static final DAf x1;
    public static final DAf x2;
    public static final DAf y0;
    public static final DAf y1;
    public static final DAf y2;
    public static final DAf z0;
    public static final DAf z1;
    public static final DAf z2;
    public final C54249yb4 a;
    public static final DAf b = new DAf("BANDWIDTH_LOG_VIEWER", 0, KQ.U(true));
    public static final DAf c = new DAf("MEMORY_LOG_VIEWER", 1, KQ.U(true));
    public static final DAf d = new DAf("KERNEL_MEMORY_LOG_VIEWER", 2, KQ.U(false));
    public static final DAf e = new DAf("CPU_GPU_LOG_VIEWER", 3, KQ.U(false));
    public static final DAf f = new DAf("STARTUP_MODE", 4, KQ.X(EnumC7832Mik.a));

    static {
        C54249yb4 U = KQ.U(false);
        C54249yb4.o(U, "finish_activity_on_back", "enabled", 4);
        g = new DAf("FINISH_ACTIVITY_ON_BACK", 5, U);
        h = new DAf("USERNAME_V2_DECORATE_IF_DIFFERENT", 6, KQ.U(false));
        i = new DAf("USERNAME_V2_DECORATE_DISPLAY", 7, KQ.U(false));
        j = new DAf("LOW_END_DEVICE_MODE", 8, KQ.U(false));
        k = new DAf("TAB_NAVIGATION_MODE", 9, KQ.U(false));
        C54249yb4 U3 = KQ.U(false);
        C54249yb4.o(U3, "LOW_END_DEVICE_NO_ANIMATION_AB", "ENABLED", 4);
        t = new DAf("NO_ANIMATION_MODE", 10, U3);
        C54249yb4 i0 = KQ.i0("");
        C54249yb4.o(i0, "DECK_PAGE_PURGE_CLIENT", "BACKGROUND_PURGE_PAGE_TYPES", 4);
        X = new DAf("DECK_PAGE_BACKGROUND_PURGE_PAGE_TYPES", 11, i0);
        C54249yb4 i02 = KQ.i0("");
        C54249yb4.o(i02, "DECK_PAGE_LOW_MEMORY_PURGE", "LOW_MEMORY_PURGE_PAGE_TYPES", 4);
        Y = new DAf("DECK_PAGE_LOW_MEMORY_PURGE_PAGE_TYPES", 12, i02);
        Z = new DAf("FEATURE_CONFIG_SYNCED_TOOLTIPS", 13, KQ.U(false));
        C54249yb4 Z2 = KQ.Z(0);
        Z2.d = "display-notch-height";
        y0 = new DAf("DISPLAY_NOTCH_HEIGHT", 14, Z2);
        C54249yb4 X2 = KQ.X(CAf.a);
        X2.d = "device_has_soft_nav_bar";
        z0 = new DAf("HAS_SOFT_NAV_BAR", 15, X2);
        A0 = new DAf("NGS_MODE", 16, KQ.Z(5));
        C54249yb4 Z3 = KQ.Z(30);
        Z3.d = "NEW_USER_SHOW_LABEL_DAYS";
        B0 = new DAf("NV_SHOW_LABEL_DAYS", 17, Z3);
        C54249yb4 U4 = KQ.U(false);
        U4.d = "SHOULD_DISPLAY_NAVIGATION_LABEL";
        C0 = new DAf("SHOULD_DISPLAY_NAVIGATION_LABEL", 18, U4);
        C54249yb4 U5 = KQ.U(false);
        U5.d = "DISABLE_LOCAL_30_DAY_LABEL_CHECK";
        D0 = new DAf("DISABLE_LOCAL_LABEL_CHECK", 19, U5);
        E0 = new DAf("NV_NEW_CAMERA_BADGE_AVAILABLE_DAYS", 20, KQ.Z(14));
        C54249yb4 U6 = KQ.U(false);
        C54249yb4.o(U6, "CONNECTIVITY_STATUS_INDICATOR", "ENABLED", 4);
        F0 = new DAf("CONNECTIVITY_STATUS_INDICATOR", 21, U6);
        C54249yb4 Z4 = KQ.Z(-1);
        Z4.d = "platform_main_thread_stuck_detector_threshold_ms";
        G0 = new DAf("MAIN_THREAD_STUCK_DETECTOR_THRESHOLD_MS", 22, Z4);
        C54249yb4 Z5 = KQ.Z(-1);
        Z5.d = "platform_main_thread_inflation_threshold_ms";
        H0 = new DAf("PLATFORM_COF_MAIN_THREAD_INFLATION_THRESHOLD_MS", 23, Z5);
        C54249yb4 Z6 = KQ.Z(13);
        Z6.d = "ANDROID_DELAY_ACTIVITY_OBSERVERS_CRITICAL_BITMASK";
        I0 = new DAf("ANDROID_DELAY_ACTIVITY_OBSERVERS_CRITICAL_BITMASK", 24, Z6);
        C54249yb4 Z7 = KQ.Z(13);
        Z7.d = "FRIENDS_FEED_ACTIVITY_OBSERVERS_CRITICAL_BITMASK";
        J0 = new DAf("FRIENDS_FEED_ACTIVITY_OBSERVERS_CRITICAL_BITMASK", 25, Z7);
        C54249yb4 Z8 = KQ.Z(13);
        Z8.d = "CHAT_ACTIVITY_OBSERVERS_CRITICAL_BITMASK";
        K0 = new DAf("CHAT_ACTIVITY_OBSERVERS_CRITICAL_BITMASK", 26, Z8);
        C54249yb4 Z9 = KQ.Z(13);
        Z9.d = "DISCOVER_FEED_ACTIVITY_OBSERVERS_CRITICAL_BITMASK";
        L0 = new DAf("DISCOVER_FEED_ACTIVITY_OBSERVERS_CRITICAL_BITMASK", 27, Z9);
        C54249yb4 Z10 = KQ.Z(13);
        Z10.d = "MAPS_ACTIVITY_OBSERVERS_CRITICAL_BITMASK";
        M0 = new DAf("MAPS_ACTIVITY_OBSERVERS_CRITICAL_BITMASK", 28, Z10);
        C54249yb4 U7 = KQ.U(false);
        U7.d = "USE_MULTIBIND_ACTIVITY_OBSERVERS";
        N0 = new DAf("USE_MULTIBIND_ACTIVITY_OBSERVERS", 29, U7);
        C54249yb4 Z11 = KQ.Z(0);
        Z11.d = "SIG_ANDROID_APP_APPEARANCE_CONFIG";
        O0 = new DAf("SIG_APP_APPEARANCE_CONFIG", 30, Z11);
        C54249yb4 U8 = KQ.U(false);
        U8.d = "SIG_ANDROID_APP_APPEARANCE_MATCH_SYSTEM_ENABLED";
        P0 = new DAf("SIG_APP_APPEARANCE_MATCH_SYSTEM_ENABLED", 31, U8);
        C54249yb4 U9 = KQ.U(false);
        U9.d = "ANDROID_CLEAN_PAGE_FACTORY_ON_NAV_HOST_DESTROY";
        Q0 = new DAf("CLEAN_PAGE_FACTORY_ON_NAV_HOST_DESTROY", 32, U9);
        C54249yb4 U10 = KQ.U(false);
        U10.d = "SIG_ANDROID_APP_APPEARANCE_USE_ACTIVITY_RESTART";
        R0 = new DAf("SIG_APP_APPEARANCE_USE_ACTIVITY_RESTART", 33, U10);
        C54249yb4 U11 = KQ.U(false);
        U11.d = "ANDROID_APP_UPGRADE_FLEXIBLE_ELIGIBLE";
        S0 = new DAf("APP_UPGRADE_FLEXIBLE_ELIGIBLE", 34, U11);
        C54249yb4 a0 = KQ.a0(TimeUnit.DAYS.toMillis(3L));
        a0.d = "ANDROID_APP_UPGRADE_FLEXIBLE_PROMPT_COOLDOWN";
        T0 = new DAf("APP_UPGRADE_FLEXIBLE_PROMPT_COOLDOWN", 35, a0);
        U0 = new DAf("APP_UPDATE_ELIGIBILITY_CHECK", 36, KQ.U(true));
        V0 = new DAf("APP_UPDATE_ELIGIBILITY_SET_TIMESTAMP_MS", 37, KQ.a0(0L));
        C54249yb4 a02 = KQ.a0(2592000000L);
        a02.d = "ANDROID_APP_UPDATE_ELIGIBILITY_EXPIRY_MS";
        W0 = new DAf("APP_UPDATE_ELIGIBILITY_EXPIRY_MS", 38, a02);
        C54249yb4 U12 = KQ.U(false);
        U12.d = "CRITICAL_WORK_NOTIFY_OBSERVERS";
        X0 = new DAf("CRITICAL_WORK_NOTIFY_OBSERVERS", 39, U12);
        C54249yb4 U13 = KQ.U(false);
        U13.d = "CRITICAL_WORK_PAUSE_DURABLE_JOBS";
        Y0 = new DAf("CRITICAL_WORK_PAUSE_DURABLE_JOBS", 40, U13);
        C54249yb4 U14 = KQ.U(true);
        U14.d = "CRITICAL_WORK_PAUSE_NON_CRITICAL_DURABLE_JOBS";
        Z0 = new DAf("CRITICAL_WORK_PAUSE_NON_CRITICAL_DURABLE_JOBS", 41, U14);
        C54249yb4 U15 = KQ.U(false);
        U15.d = "CRITICAL_WORK_PAGE_TRANSITIONS";
        a1 = new DAf("CRITICAL_WORK_PAGE_TRANSITIONS", 42, U15);
        C54249yb4 a03 = KQ.a0(4000L);
        a03.d = "critical_work_main_activity_startup_critical_section_timeout_ms";
        b1 = new DAf("CRITICAL_WORK_MAIN_ACTIVITY_STARTUP_CRITICAL_SECTION_TIMEOUT_MS", 43, a03);
        C54249yb4 U16 = KQ.U(false);
        U16.d = "delay_non_critical_startup_acitivty_observer_after_critical_section";
        c1 = new DAf("DELAY_NON_CRITICAL_STARTUP_ACTIVITY_OBSERVER_AFTER_CRITICAL_SECTION", 44, U16);
        C54249yb4 U17 = KQ.U(false);
        U17.d = "delay_non_critical_startup_activity_observer_on_idle_scheduler";
        d1 = new DAf("DELAY_NON_CRITICAL_STARTUP_ACTIVITY_OBSERVER_ON_IDLE_SCHEDULER", 45, U17);
        C54249yb4 U18 = KQ.U(false);
        U18.d = "page_load_signal_on_critical_section";
        e1 = new DAf("PAGE_LOAD_SIGNAL_ON_CRITICAL_SECTION", 46, U18);
        C54249yb4 U19 = KQ.U(true);
        U19.d = "UPDATE_SCHEDULERS_CONFIGS_VIA_DURABLE_JOB";
        f1 = new DAf("UPDATE_SCHEDULERS_CONFIGS_VIA_DURABLE_JOB", 47, U19);
        C54249yb4 a04 = KQ.a0(4000L);
        a04.d = "page_load_signal_critical_section_timeout_ms";
        g1 = new DAf("PAGE_LOAD_SIGNAL_CRITICAL_SECTION_TIMEOUT_MS", 48, a04);
        h1 = new DAf("HISTORICAL_EXIT_REASONS_LAST_PID", 49, KQ.Z(0));
        C54249yb4 U20 = KQ.U(false);
        U20.d = "PLATFORM_COF_LOCALIZATION_PSEUDOLOCALE_ENABLED";
        i1 = new DAf("PLATFORM_COF_LOCALIZATION_PSEUDOLOCALE_ENABLED", 50, U20);
        C54249yb4 X3 = KQ.X(G6l.a);
        X3.d = "PLATFORM_COF_LOCALIZATION_OVERRIDE_LOCALE";
        j1 = new DAf("PLATFORM_COF_LOCALIZATION_OVERRIDE_LOCALE", 51, X3);
        C54249yb4 U21 = KQ.U(false);
        U21.d = "PLATFORM_COF_ENABLE_L10N_ISSUE_DETECTORS";
        k1 = new DAf("PLATFORM_COF_ENABLE_L10N_ISSUE_DETECTORS", 52, U21);
        l1 = new DAf("LOCALIZATION_RTL_PSEUDOLOCALE_ENABLED", 53, KQ.U(false));
        C54249yb4 U22 = KQ.U(false);
        C54249yb4.o(U22, "PROCESS_RESTART_JOB", "ENABLE_PROCESS_RESTART_JOB", 4);
        m1 = new DAf("ENABLE_PROCESS_RESTART_JOB", 54, U22);
        C54249yb4 Z12 = KQ.Z(29);
        C54249yb4.o(Z12, "PROCESS_RESTART_JOB", "PROCESS_RESTART_MAX_ANDROID_VERSION", 4);
        n1 = new DAf("PROCESS_RESTART_MAX_ANDROID_VERSION", 55, Z12);
        C54249yb4 a05 = KQ.a0(10L);
        C54249yb4.o(a05, "PROCESS_RESTART_JOB", "DEVICE_MEMORY_MAX_THRESHOLD_GB", 4);
        o1 = new DAf("DEVICE_MEMORY_MAX_THRESHOLD_GB", 56, a05);
        C54249yb4 a06 = KQ.a0(800L);
        C54249yb4.o(a06, "PROCESS_RESTART_JOB", "OOM_SCORE_MIN_THRESHOLD", 4);
        p1 = new DAf("OOM_SCORE_MIN_THRESHOLD", 57, a06);
        C54249yb4 a07 = KQ.a0(35L);
        C54249yb4.o(a07, "PROCESS_RESTART_JOB", "PROCESS_RESTART_JOB_RECURRING_DELAY_MINS", 4);
        q1 = new DAf("PROCESS_RESTART_JOB_RECURRING_DELAY_MINS", 58, a07);
        C54249yb4 a08 = KQ.a0(30L);
        C54249yb4.o(a08, "PROCESS_RESTART_JOB", "PROCESS_TIME_MIN_THRESHOLD_MINS", 4);
        r1 = new DAf("PROCESS_TIME_MIN_THRESHOLD_MINS", 59, a08);
        C54249yb4 a09 = KQ.a0(30L);
        C54249yb4.o(a09, "PROCESS_RESTART_JOB", "ACTIVE_USER_TIME_MIN_THRESHOLD_MINS", 4);
        s1 = new DAf("ACTIVE_USER_TIME_MIN_THRESHOLD_MINS", 60, a09);
        C54249yb4 a010 = KQ.a0(1440L);
        C54249yb4.o(a010, "PROCESS_RESTART_JOB", "BACKGROUND_TIME_MIN_THRESHOLD_MINS", 4);
        t1 = new DAf("BACKGROUND_TIME_MIN_THRESHOLD_MINS", 61, a010);
        u1 = new DAf("ACTIVE_USER_TIME_MS", 62, KQ.a0(0L));
        C54249yb4 U23 = KQ.U(true);
        U23.d = "android_s_content_capture_enabled";
        v1 = new DAf("ANDROID_S_CONTENT_CAPTURE_ENABLED", 63, U23);
        C54249yb4 U24 = KQ.U(false);
        U24.d = "android_best_friends_widget_force_enabled";
        w1 = new DAf("ANDROID_BEST_FRIENDS_WIDGET_FORCE_ENABLED", 64, U24);
        C54249yb4 U25 = KQ.U(false);
        U25.d = "android_best_friends_widget_force_disabled";
        x1 = new DAf("ANDROID_BEST_FRIENDS_WIDGET_FORCE_DISABLED", 65, U25);
        C54249yb4 U26 = KQ.U(false);
        U26.i = 584;
        y1 = new DAf("CAMERA_LOCKSCREEN_IS_PRIVACY_DISCLAIMER_ACCEPTED", 66, U26);
        z1 = new DAf("CAMERA_LOCKSCREEN_FORCE_IS_PRIVACY_DISCLAIMER_ACCEPTED", 67, KQ.U(false));
        C54249yb4 a011 = KQ.a0(0L);
        a011.i = 585;
        A1 = new DAf("CAMERA_LOCKSCREEN_ENROLLMENT_PROMPT_LAST_SEEN", 68, a011);
        C54249yb4 Z13 = KQ.Z(0);
        Z13.i = 586;
        B1 = new DAf("CAMERA_LOCKSCREEN_ENROLLMENT_PROMPT_SEEN_COUNT", 69, Z13);
        C1 = new DAf("CAMERA_LOCKSCREEN_ENROLLMENT_PROMPT_SEEN_DEVICE_LIST_SIZE_LIMIT", 70, KQ.Z(3));
        C54249yb4 i03 = KQ.i0("");
        i03.i = 876;
        D1 = new DAf("CAMERA_LOCKSCREEN_ENROLLMENT_PROMPT_SEEN_DEVICE_LIST", 71, i03);
        C54249yb4 U27 = KQ.U(false);
        U27.d = "camera_enable_lock_screen_mode";
        E1 = new DAf("CAMERA_LOCKSCREEN_TO_CAMERA_ENABLED", 72, U27);
        C54249yb4 U28 = KQ.U(false);
        U28.d = "camera_quick_tap_to_camera_switch_processor_enabled";
        F1 = new DAf("CAMERA_LOCKSCREEN_TO_CAMERA_SWITCH_PROCESSOR_ENABLED", 73, U28);
        G1 = new DAf("CAMERA_LOCKSCREEN_TO_CAMERA_FORCE_ENABLED", 74, KQ.U(false));
        H1 = new DAf("CAMERA_LOCKSCREEN_TO_CAMERA_SERVICE_TYPE", 75, KQ.X(BAf.a));
        C54249yb4 U29 = KQ.U(false);
        U29.d = "camera_quick_tap_to_camera_allow_deeplink_override_tweak";
        I1 = new DAf("CAMERA_LOCKSCREEN_TO_CAMERA_DEEPLINK_OVERRIDE_ALLOWED", 76, U29);
        J1 = new DAf("CAMERA_LOCKSCREEN_TO_CAMERA_DEEPLINK_OVERRIDE", 77, KQ.U(false));
        K1 = new DAf("CAMERA_LOCKSCREEN_UNLOCK_TO_CAMERA_STATUS_RESPONSE", 78, KQ.X(EnumC55133zAf.a));
        L1 = new DAf("CAMERA_LOCKSCREEN_UNLOCK_TO_CAMERA_TARGET_RESPONSE", 79, KQ.X(AAf.a));
        C54249yb4 a012 = KQ.a0(TimeUnit.DAYS.toMillis(5L));
        a012.d = "camera_android_quick_tap_promo_cooldown_ms";
        M1 = new DAf("CAMERA_LOCKSCREEN_UNLOCK_TO_CAMERA_PROMPT_COOLDOWN_MS", 80, a012);
        C54249yb4 Z14 = KQ.Z(3);
        Z14.d = "camera_android_quick_tap_promo_max_views";
        N1 = new DAf("CAMERA_LOCKSCREEN_UNLOCK_TO_CAMERA_PROMPT_MAX_VIEWS", 81, Z14);
        C54249yb4 U30 = KQ.U(false);
        U30.d = "camera_android_quick_tap_full_res_promo_asset_prefetch_enabled";
        O1 = new DAf("CAMERA_LOCKSCREEN_FULL_RES_PROMO_ASSET_PREFETCH_ENABLED", 82, U30);
        P1 = new DAf("CAMERA_LOCKSCREEN_PENDING_ON_TARGET_RESPONSE", 83, KQ.U(false));
        Q1 = new DAf("DISPOSABLE_RELEASER_VIOLATION_ENABLED", 84, KQ.U(false));
        C54249yb4 Z15 = KQ.Z(240);
        Z15.d = "PLATFORM_BG_DATA_SYNC";
        R1 = new DAf("PLATFORM_BG_DATA_SYNC_MINS", 85, Z15);
        C54249yb4 U31 = KQ.U(false);
        U31.d = "PLATFORM_DATA_SYNC_ON_NAV";
        S1 = new DAf("PLATFORM_DATA_SYNC_ON_NAV", 86, U31);
        C54249yb4 U32 = KQ.U(false);
        U32.d = "STARTUP_NAVIGATE_EARLY";
        T1 = new DAf("STARTUP_NAVIGATE_EARLY", 87, U32);
        C54249yb4 U33 = KQ.U(false);
        U33.d = "EXISTING_IO_THREAD_POOL_CALLERS_ON_IO_THREAD_POOL";
        U1 = new DAf("EXISTING_IO_THREAD_POOL_CALLERS_ON_IO_THREAD_POOL", 88, U33);
        C54249yb4 U34 = KQ.U(false);
        U34.d = "CONTENT_MANAGER_ON_IO_THREAD_POOL";
        V1 = new DAf("CONTENT_MANAGER_ON_IO_THREAD_POOL", 89, U34);
        C54249yb4 Z16 = KQ.Z(10);
        Z16.d = "MAX_IO_CONCURRENT_TASKS";
        W1 = new DAf("MAX_IO_CONCURRENT_TASKS", 90, Z16);
        C54249yb4 Z17 = KQ.Z(4);
        Z17.d = "IO_THREAD_POOL_PRIORITY";
        X1 = new DAf("IO_THREAD_POOL_PRIORITY", 91, Z17);
        C54249yb4 Z18 = KQ.Z(10);
        Z18.d = "CPU_THREAD_POOL_PRIORITY";
        Y1 = new DAf("CPU_THREAD_POOL_PRIORITY", 92, Z18);
        C54249yb4 Y2 = KQ.Y(1.0f);
        Y2.d = "UI_BG_THREAD_POOL_SIZE_MULTIPLIER";
        Z1 = new DAf("UI_BG_THREAD_POOL_SIZE_MULTIPLIER", 93, Y2);
        C54249yb4 Y3 = KQ.Y(1.0f);
        Y3.d = "CPU_THREAD_POOL_SIZE_MULTIPLIER";
        a2 = new DAf("CPU_THREAD_POOL_SIZE_MULTIPLIER", 94, Y3);
        C54249yb4 Z19 = KQ.Z(5);
        Z19.d = "DB_QUERIES_THREAD_POOL_SIZE";
        b2 = new DAf("DB_QUERIES_THREAD_POOL_SIZE", 95, Z19);
        C54249yb4 U35 = KQ.U(false);
        U35.d = "IDLE_SCHEDULER_USE_CPU_POOL";
        c2 = new DAf("IDLE_SCHEDULER_USE_CPU_POOL", 96, U35);
        C54249yb4 U36 = KQ.U(false);
        U36.d = "UI_BG_SCHEDULER_USE_CPU_POOL";
        d2 = new DAf("UI_BG_SCHEDULER_USE_CPU_POOL", 97, U36);
        C54249yb4 U37 = KQ.U(false);
        U37.d = "BLIZZARD_SCHEDULER_ENABLED";
        e2 = new DAf("BLIZZARD_SCHEDULER_ENABLED", 98, U37);
        C54249yb4 Z20 = KQ.Z(2);
        Z20.d = "BLIZZARD_THREAD_POOL_SIZE";
        f2 = new DAf("BLIZZARD_THREAD_POOL_SIZE", 99, Z20);
        C54249yb4 Z21 = KQ.Z(10);
        Z21.d = "BLIZZARD_THREAD_PRIORITY";
        g2 = new DAf("BLIZZARD_THREAD_PRIORITY", 100, Z21);
        C54249yb4 U38 = KQ.U(false);
        U38.d = "LEAK_CANARY_FOR_GOLD_ALPHA_BUILDS";
        h2 = new DAf("LEAK_CANARY_FOR_GOLD_ALPHA_BUILDS", 101, U38);
        C54249yb4 a013 = KQ.a0(5000L);
        a013.d = "LEAK_CANARY_HEAPDUMP_DELAY_MS";
        i2 = new DAf("LEAK_CANARY_HEAPDUMP_DELAY_MS", 102, a013);
        C54249yb4 U39 = KQ.U(false);
        U39.d = "USE_SNAP_PRIORITY_QUEUE_SCHEDULING";
        j2 = new DAf("USE_SNAP_PRIORITY_QUEUE_SCHEDULING", 103, U39);
        C54249yb4 c54249yb4 = new C54249yb4(C53153xsj.class, new C53153xsj());
        c54249yb4.d = "SNAP_PRIORITY_QUEUE_CONFIG";
        k2 = new DAf("SNAP_PRIORITY_QUEUE_CONFIG", 104, c54249yb4);
        C54249yb4 U40 = KQ.U(false);
        U40.d = "MUSHROOM_MIGRATION_NOTIFICATION_ENABLED";
        l2 = new DAf("MUSHROOM_MIGRATION_NOTIFICATION_ENABLED", 105, U40);
        C54249yb4 U41 = KQ.U(false);
        U41.d = "cam_screen_param_async_update";
        m2 = new DAf("CAMERA_SCREEN_PARAM_ASYNC_UPDATE", 106, U41);
        C54249yb4 U42 = KQ.U(true);
        U42.d = "COMPLETABLE_SUBSCRIBE_SAFE_ALLOWLISTED";
        n2 = new DAf("COMPLETABLE_SUBSCRIBE_SAFE_ALLOWLISTED", 107, U42);
        C54249yb4 Z22 = KQ.Z(0);
        Z22.d = "ANDROID_CAPRI_DEVICE_UI_EVENT_SAMPLE_RATE";
        o2 = new DAf("CAPRI_DEVICE_UI_EVENT_SAMPLE_RATE", 108, Z22);
        p2 = new DAf("CACHED_SURFACE_VIEW_LAYOUT_PARAMS", Tweaks.MAX_HOURS_AFTER_STREAK_EXPIRE_TO_ENABLE_RESTORE, KQ.a0(0L));
        C54249yb4 U43 = KQ.U(false);
        U43.d = "ANDROID_CAPRI_MIRROR_VIEW";
        q2 = new DAf("CAPRI_FOOTER_MIRROR_VIEW", Tweaks.ENABLE_STREAK_EDUCATION, U43);
        C54249yb4 U44 = KQ.U(false);
        U44.d = "ANDROID_ENABLE_FOOTER_UI_UPDATES_FOR_PERSISTENT_FOOTER";
        r2 = new DAf("ENABLE_FOOTER_UI_UPDATES_FOR_PERSISTENT_FOOTER", 111, U44);
        C54249yb4 U45 = KQ.U(false);
        U45.d = "G2X_ENABLE_NAV_DEST_SIGNALER_ON_LOGIN_ACTIVITY";
        s2 = new DAf("G2X_ENABLE_NAV_DEST_SIGNALER_ON_LOGIN_ACTIVITY", 112, U45);
        C54249yb4 U46 = KQ.U(false);
        U46.d = "REPORT_CRASH_ANR_WATCHDOG_THREAD";
        t2 = new DAf("REPORT_CRASH_ANR_WATCHDOG_THREAD", Tweaks.DELTA_SYNC_SQLITE_SHARED_STORAGE_CACHE_SIZE, U46);
        C54249yb4 U47 = KQ.U(false);
        U47.d = "CRASH_ON_LARGE_BITMAPS";
        u2 = new DAf("CRASH_ON_LARGE_BITMAPS", Tweaks.FAIL_DECRYPT_FOR_DUPLEX_SNAPS_TEST_ONLY, U47);
        C54249yb4 U48 = KQ.U(false);
        U48.d = "LOG_LARGE_BITMAPS";
        v2 = new DAf("LOG_LARGE_BITMAPS", 115, U48);
        C54249yb4 U49 = KQ.U(false);
        U49.d = "REPORT_NON_FATAL_ON_HOT_PHONE";
        w2 = new DAf("REPORT_NON_FATAL_ON_HOT_PHONE", 116, U49);
        C54249yb4 Z23 = KQ.Z(0);
        Z23.d = "HOT_PHONE_NON_FATAL_REPORTING_SAMPLING_RATE";
        x2 = new DAf("HOT_PHONE_NON_FATAL_REPORTING_SAMPLING_RATE", 117, Z23);
        C54249yb4 U50 = KQ.U(false);
        U50.d = "HIGH_CPU_USAGE_DETECTION_ENABLED";
        y2 = new DAf("HIGH_CPU_USAGE_DETECTION_ENABLED", 118, U50);
        C54249yb4 Z24 = KQ.Z(180);
        Z24.d = "HIGH_CPU_USAGE_DETECTION_TIME_WINDOW_SECONDS";
        z2 = new DAf("HIGH_CPU_USAGE_DETECTION_TIME_WINDOW_SECONDS", 119, Z24);
        C54249yb4 Z25 = KQ.Z(25);
        Z25.d = "HIGH_CPU_USAGE_DETECTION_PERCENTAGE_THRESHOLD";
        A2 = new DAf("HIGH_CPU_USAGE_DETECTION_PERCENTAGE_THRESHOLD", 120, Z25);
        C54249yb4 Z26 = KQ.Z(0);
        Z26.d = "BITMAP_ANALYSIS_SAMPLING_RATE";
        B2 = new DAf("BITMAP_ANALYSIS_SAMPLING_RATE", 121, Z26);
        C54249yb4 U51 = KQ.U(false);
        U51.d = "PLATFORM_HOVA_AVATAR_BADGE_USE_UPDATE_STRATEGY";
        C2 = new DAf("PLATFORM_HOVA_AVATAR_BADGE_USE_UPDATE_STRATEGY", 122, U51);
        C54249yb4 U52 = KQ.U(false);
        U52.d = "PLATFORM_HOVA_ADD_FRIENDS_BADGE_USE_UPDATE_STRATEGY";
        D2 = new DAf("PLATFORM_HOVA_ADD_FRIENDS_BADGE_USE_UPDATE_STRATEGY", 123, U52);
        C54249yb4 X4 = KQ.X(EnumC53599yAf.a);
        X4.d = "PLATFORM_DELAY_HOVA_COMPONENT_UPDATE_STRATEGY";
        E2 = new DAf("PLATFORM_HOVA_COMPONENT_UPDATE_STRATEGY", 124, X4);
        C54249yb4 U53 = KQ.U(false);
        U53.d = "CHECK_FLOATING_VIEW_SCROLLABILITY";
        F2 = new DAf("CHECK_FLOATING_VIEW_SCROLLABILITY", 125, U53);
        C54249yb4 U54 = KQ.U(false);
        U54.d = "CAPRI_MOVE_DISCOVER_FEED_ABOVE_FOOTER";
        G2 = new DAf("CAPRI_MOVE_DISCOVER_FEED_ABOVE_FOOTER", 126, U54);
        C54249yb4 Z27 = KQ.Z(0);
        Z27.d = "ANDROID_TALL_FOOTER_TYPE";
        H2 = new DAf("TALL_FOOTER_STYLE", 127, Z27);
        C54249yb4 U55 = KQ.U(false);
        U55.d = "SHOULD_MANUALLY_INFLATE_MAIN_LAYOUT";
        I2 = new DAf("SHOULD_MANUALLY_INFLATE_MAIN_LAYOUT", 128, U55);
        C54249yb4 U56 = KQ.U(false);
        U56.d = "SCREENSHOT_DETECTION_API";
        J2 = new DAf("SCREENSHOT_DETECTION_API", 129, U56);
        K2 = new DAf("ENABLE_SCREENSHOT_DETECTION", 130, KQ.U(true));
        C54249yb4 U57 = KQ.U(false);
        U57.d = "SCHEDULER_METRICS_REPORTING_ENABLED";
        L2 = new DAf("SCHEDULER_METRICS_REPORTING_ENABLED", Imgproc.COLOR_RGB2YUV_YV12, U57);
        C54249yb4 a014 = KQ.a0(2000L);
        a014.d = "SCHEDULER_METRICS_POLLING_INTERVAL_MS";
        M2 = new DAf("SCHEDULER_METRICS_POLLING_INTERVAL_MS", Imgproc.COLOR_BGR2YUV_YV12, a014);
        C54249yb4 i04 = KQ.i0("");
        i04.d = "DISABLED_BG_PRE_FETCHERS";
        N2 = new DAf("DISABLED_BG_PRE_FETCHERS", Imgproc.COLOR_RGBA2YUV_YV12, i04);
        C54249yb4 U58 = KQ.U(false);
        U58.d = "DELAY_NGS_NAV_BAR_BADGE_NON_CRITICAL";
        O2 = new DAf("DELAY_NGS_NAV_BAR_BADGE_NON_CRITICAL", Imgproc.COLOR_BGRA2YUV_YV12, U58);
        P2 = new DAf("LAST_UPDATE_TIME", 135, KQ.a0(-1L));
        Q2 = new DAf("LAST_UPDATE_VERSION", 136, KQ.i0(""));
        C54249yb4 U59 = KQ.U(false);
        U59.d = "CREATE_FEATURE_GRAPH_MAIN_THREAD";
        R2 = new DAf("CREATE_FEATURE_GRAPH_MAIN_THREAD", 137, U59);
        C54249yb4 Z28 = KQ.Z(0);
        Z28.d = "INIT_CONFIG_PROVIDERS_ON_QUERIES_SCHEDULER";
        S2 = new DAf("INIT_CONFIG_PROVIDERS_ON_QUERIES_SCHEDULER", 138, Z28);
        C54249yb4 Z29 = KQ.Z(0);
        Z29.d = "LAZY_INIT_CONFIG_PROVIDERS";
        T2 = new DAf("LAZY_INIT_CONFIG_PROVIDERS", Imgproc.COLOR_COLORCVT_MAX, Z29);
        C54249yb4 U60 = KQ.U(false);
        U60.d = "STARTUP_ENABLE_BG_APP_CREATION_REPORTING";
        U2 = new DAf("STARTUP_ENABLE_BG_APP_CREATION_REPORTING", 140, U60);
        C54249yb4 U61 = KQ.U(false);
        U61.d = "STARTUP_USE_DEEPLINK_URI_MATCHER_REGISTRY";
        V2 = new DAf("STARTUP_USE_DEEPLINK_URI_MATCHER_REGISTRY", 141, U61);
        W2 = a();
    }

    public DAf(String str, int i3, C54249yb4 c54249yb4) {
        this.a = c54249yb4;
    }

    public static /* synthetic */ DAf[] a() {
        return new DAf[]{b, c, d, e, f, g, h, i, j, k, t, X, Y, Z, y0, z0, A0, B0, C0, D0, E0, F0, G0, H0, I0, J0, K0, L0, M0, N0, O0, P0, Q0, R0, S0, T0, U0, V0, W0, X0, Y0, Z0, a1, b1, c1, d1, e1, f1, g1, h1, i1, j1, k1, l1, m1, n1, o1, p1, q1, r1, s1, t1, u1, v1, w1, x1, y1, z1, A1, B1, C1, D1, E1, F1, G1, H1, I1, J1, K1, L1, M1, N1, O1, P1, Q1, R1, S1, T1, U1, V1, W1, X1, Y1, Z1, a2, b2, c2, d2, e2, f2, g2, h2, i2, j2, k2, l2, m2, n2, o2, p2, q2, r2, s2, t2, u2, v2, w2, x2, y2, z2, A2, B2, C2, D2, E2, F2, G2, H2, I2, J2, K2, L2, M2, N2, O2, P2, Q2, R2, S2, T2, U2, V2};
    }

    public static DAf valueOf(String str) {
        return (DAf) Enum.valueOf(DAf.class, str);
    }

    public static DAf[] values() {
        return (DAf[]) W2.clone();
    }

    @Override // defpackage.InterfaceC55783zb4
    public final EnumC51183wb4 e() {
        return EnumC51183wb4.a;
    }

    @Override // defpackage.InterfaceC55783zb4
    public final String getName() {
        return name();
    }

    @Override // defpackage.InterfaceC55783zb4
    public final C54249yb4 x() {
        return this.a;
    }
}
