package defpackage;

import java.util.Locale;

/* renamed from: Mt8  reason: default package and case insensitive filesystem */
/* loaded from: classes.dex */
public enum EnumC8088Mt8 {
    AUTHENTICATION("AUTHENTICATION"),
    ANALYTICS("ANALYTICS"),
    BITMOJI("BITMOJI"),
    CALLING("CALLING"),
    CAMERA("CAMERA"),
    CHAT("CHAT"),
    CONTEXT("CONTEXT"),
    CUSTOM_STICKERS("CUSTOM_STICKERS"),
    DEBUG("DEBUG"),
    DISCOVER("DISCOVER"),
    GEOFILTER("GEOFILTER"),
    LENS("LENS"),
    REGISTRATION("REGISTRATION"),
    MAPS("MAPS"),
    MEMORIES("MEMORIES"),
    MUSIC("MUSIC"),
    NAVIGATION("NAVIGATION"),
    NOTIFICATIONS("NOTIFICATIONS"),
    PROFILE("PROFILE"),
    SEARCH("SEARCH"),
    SPECTACLES("SPECTACLES"),
    SNAPADS("SNAPADS"),
    SNAPCODES("SNAPCODES"),
    SNAPCRAFT("SNAPCRAFT"),
    STICKERS("STICKERS"),
    STORIES("STORIES"),
    TROPHIES("TROPHIES"),
    UNKNOWN("UNKNOWN"),
    SNAPCASH("SNAPCASH"),
    CONFIGURATION("CONFIGURATION"),
    FRIENDS("FRIENDS"),
    MOBILE_ODG("MOBILE_ODG"),
    STARTUP("STARTUP"),
    DISK("DISK"),
    SNAP("SNAP"),
    NETWORK_INFRA("NETWORK_INFRA"),
    DDML("DDML"),
    OAUTH2("OAUTH2"),
    SNAP_TOKEN("SNAP_TOKEN"),
    FIDELIUS("FIDELIUS"),
    COMMERCE("COMMERCE"),
    SNAP_KIT("SNAP_KIT"),
    BOLT("BOLT"),
    COGNAC("COGNAC"),
    CHAT_GROUP_CREATE("CHAT_GROUP_CREATE"),
    CHAT_GROUP_HAMBURGER("CHAT_GROUP_HAMBURGER"),
    CHAT_HAMBURGER("CHAT_HAMBURGER"),
    CHAT_MEDIA("CHAT_MEDIA"),
    FRIENDS_FEED("FRIENDS_FEED"),
    SEND_TO("SEND_TO"),
    STICKERS_CHAT("STICKERS_CHAT"),
    STICKERS_PREVIEW("STICKERS_PREVIEW"),
    STICKERS_ODG("STICKERS_ODG"),
    STORIES_BITMOJI("STORIES_BITMOJI"),
    CHAT_AUTOSUGGEST("CHAT_AUTOSUGGEST"),
    COMMERCE_PLATFORM("COMMERCE_PLATFORM"),
    INTERNAL_TOOLS("INTERNAL_TOOLS"),
    PROFILE_PUBLIC("PROFILE_PUBLIC"),
    CHARMS("CHARMS"),
    STICKERS_QUICKREPLY("STICKERS_QUICKREPLY"),
    WIDGETS("WIDGETS"),
    SHARE_EXTENSION("SHARE_EXTENSION"),
    ENHANCED_CONTACTS("ENHANCED_CONTACTS"),
    CUSTOMOJI("CUSTOMOJI"),
    BITMOJI_FASHION("BITMOJI_FASHION"),
    SELFIE_PICKER_BANNER("SELFIE_PICKER_BANNER"),
    STYLE_SWITCHER_SETTINGS("STYLE_SWITCHER_SETTINGS"),
    PREVIEW("PREVIEW"),
    CHAT_SUGGEST_ICON("CHAT_SUGGEST_ICON"),
    SNAP_SUGGEST_ICON("SNAP_SUGGEST_ICON"),
    COMMUNITIES("COMMUNITIES"),
    PROFILE_PICKER("PROFILE_PICKER"),
    MAP_TRAY_PICKER("MAP_TRAY_PICKER"),
    AVATAR_BUILDER("AVATAR_BUILDER"),
    PLUS("PLUS"),
    PRESENCE("PRESENCE"),
    UNRECOGNIZED_VALUE("UNRECOGNIZED_VALUE");
    
    public final String a;

    EnumC8088Mt8(String str) {
        this.a = str;
    }

    public static EnumC8088Mt8 a(String str) {
        EnumC8088Mt8 enumC8088Mt8 = UNRECOGNIZED_VALUE;
        if (str == null) {
            return enumC8088Mt8;
        }
        try {
            return valueOf(str.toUpperCase(Locale.US));
        } catch (Exception unused) {
            return enumC8088Mt8;
        }
    }

    @Override // java.lang.Enum
    public final String toString() {
        return this.a;
    }
}
