package defpackage;

import java.util.Locale;

/* renamed from: Oik  reason: default package and case insensitive filesystem */
/* loaded from: classes.dex */
public enum EnumC9097Oik implements InterfaceC33734lDi {
    PROCESS_CREATED(null),
    PLATFORM_G2_END(null),
    CAMERA_PREPARE_TRIGGERED(EnumC7504Lv8.CAMERA_ANDROID_PREPARE_TRIGGERED),
    CAMERA_PREPARE_COMPLETE(EnumC7504Lv8.CAMERA_ANDROID_PREPARE_COMPLETED),
    CAMERA_OPEN_TRIGGERED(EnumC7504Lv8.CAMERA_ANDROID_SERVICE_OPEN_TRIGGERED),
    CAMERA_OPENED(EnumC7504Lv8.CAMERA_ANDROID_SERVICE_OPEN_COMPLETED),
    CAMERA_FEATURE_READY(null),
    SHARED_SURFACE_CREATED(null),
    FIRST_UI_RENDERED(EnumC7504Lv8.CAMERA_FIRST_UI_RENDERED),
    ENABLE_STREAMING_TRIGGERED(EnumC7504Lv8.CAMERA_ANDROID_ENABLE_STREAMING_TRIGGERED),
    START_PREVIEW_TRIGGERED(EnumC7504Lv8.CAMERA_ANDROID_START_PREVIEW_TRIGGERED),
    START_PREVIEW_BG_THREAD_COMPLETE(EnumC7504Lv8.CAMERA_ANDROID_START_PREVIEW_BG_THREAD_COMPLETED),
    FIRST_PREVIEW_FRAME_RECEIVED(EnumC7504Lv8.CAMERA_FIRST_PREVIEW_FRAME_RECEIVED),
    FIRST_PREVIEW_FRAME_RENDERED(EnumC7504Lv8.CAMERA_FIRST_PREVIEW_FRAME_RENDERED),
    START_PREVIEW_UI_THREAD_COMPLETE(EnumC7504Lv8.CAMERA_ANDROID_START_PREVIEW_MAIN_THREAD_COMPLETED);
    
    public final EnumC7504Lv8 a;

    EnumC9097Oik(EnumC7504Lv8 enumC7504Lv8) {
        this.a = enumC7504Lv8;
    }

    @Override // defpackage.InterfaceC32152kDi
    public final String a() {
        return "startup:".concat(name().toLowerCase(Locale.ROOT));
    }

    @Override // defpackage.InterfaceC32152kDi
    public final String b() {
        return name();
    }
}
