package defpackage;

/* renamed from: rA  reason: default package and case insensitive filesystem */
/* loaded from: classes.dex */
public enum EnumC42850rA {
    ADDED_BY_PHONE("ADDED_BY_PHONE"),
    ADDED_BY_USERNAME("ADDED_BY_USERNAME"),
    ADDED_BY_QR_CODE("ADDED_BY_QR_CODE"),
    ADDED_BY_ADDED_ME_BACK("ADDED_BY_ADDED_ME_BACK"),
    ADDED_BY_NEARBY("ADDED_BY_NEARBY"),
    ADDED_BY_SUGGESTED("ADDED_BY_SUGGESTED"),
    ADDED_BY_OFFICIAL_STORY_SEARCH("ADDED_BY_OFFICIAL_STORY_SEARCH"),
    ADDED_BY_DEEP_LINK("ADDED_BY_DEEP_LINK"),
    ADDED_BY_INVITE("ADDED_BY_INVITE"),
    ADDED_BY_STORY_CHROME("ADDED_BY_STORY_CHROME"),
    ADDED_BY_SHARED_USERNAME("ADDED_BY_SHARED_USERNAME"),
    ADDED_BY_SHARED_STORY("ADDED_BY_SHARED_STORY"),
    ADDED_BY_GROUP_CHAT("ADDED_BY_GROUP_CHAT"),
    ADDED_BY_SHAZAM("ADDED_BY_SHAZAM"),
    ADDED_BY_MOB("ADDED_BY_MOB"),
    ADDED_BY_FEATURED_OFFICIAL_STORY("ADDED_BY_FEATURED_OFFICIAL_STORY"),
    ADDED_FROM_OUR_STORY("ADDED_FROM_OUR_STORY"),
    ADDED_BY_INFLUENCER_RECOMMENDATION("ADDED_BY_INFLUENCER_RECOMMENDATION"),
    ADDED_BY_DISPLAY_NAME("ADDED_BY_DISPLAY_NAME"),
    ADDED_BY_TEST("ADDED_BY_TEST"),
    ADDED_BY_MENTION("ADDED_BY_MENTION"),
    ADDED_BY_SUBSCRIPTION("ADDED_BY_SUBSCRIPTION"),
    ADDED_BY_MENTION_STICKER("ADDED_BY_MENTION_STICKER"),
    ADDED_BY_SNAPCODE_STICKER("ADDED_BY_SNAPCODE_STICKER"),
    ADDED_FROM_SPOTLIGHT("ADDED_FROM_SPOTLIGHT"),
    ADDED_FROM_PUBLIC_PROFILE("ADDED_FROM_PUBLIC_PROFILE"),
    ADDED_FROM_LENS("ADDED_FROM_LENS"),
    ADDED_BY_CHAT("ADDED_BY_CHAT"),
    ADDED_BY_SNAP_ANYONE("ADDED_BY_SNAP_ANYONE"),
    ADDED_BY_COMMUNITY("ADDED_BY_COMMUNITY"),
    ADDED_BY_NEARBY_FRIENDS("ADDED_BY_NEARBY_FRIENDS"),
    ADDED_BY_SEARCH("ADDED_BY_SEARCH"),
    /* JADX INFO: Fake field, exist only in values array */
    UNRECOGNIZED_VALUE("UNRECOGNIZED_VALUE");
    
    public final String a;

    EnumC42850rA(String str) {
        this.a = str;
    }

    @Override // java.lang.Enum
    public final String toString() {
        return this.a;
    }
}
