package defpackage;

/* renamed from: dd  reason: default package and case insensitive filesystem */
/* loaded from: classes4.dex */
public enum EnumC22033dd {
    DEFAULT("LandingPageActivity", "icon_v6"),
    DENISE_AB("DeniseAbAlias", "icon_denise_ab"),
    CLASSIC_GHOST("ClassicGhostAlias", "icon_classic_ghost"),
    PLUS_GOLD("PlusGoldAlias", "icon_plus_gold"),
    GOLDEN("GoldenAlias", "icon_golden"),
    PLUS_BLACK("PlusBlackAlias", "icon_plus_black"),
    PLUS_2("Plus2Alias", "icon_plus_2"),
    PLUS_3("Plus3Alias", "icon_plus_3"),
    CHROME_DRIP("ChromeDripAlias", "icon_chrome_drip"),
    FLOWERS("FlowersAlias", "icon_flowers"),
    GOLD("GoldAlias", "icon_gold"),
    MESH_GHOST("MeshGhostAlias", "icon_mesh_ghost"),
    PLUSH("PlushAlias", "icon_plush"),
    VDAY_70S_LOVE("Vday70sLoveAlias", "icon_vday_70s_love"),
    HEART_CANDY("HeartCandyAlias", "icon_vday_heart_candy"),
    ROSES("RosesAlias", "icon_vday_roses"),
    VALENTINES_SCRIPT("ValentinesScriptAlias", "icon_vday_valentines_script"),
    VALENTINES_SUGAR_COOKIE("ValentinesSugarCookieAlias", "icon_vday_valentines_sugar_cookie"),
    ANGEL("AngelAlias", "icon_vday_angel"),
    VDAY_CHROME("VDayChromeAlias", "icon_vday_chrome"),
    CUPID("CupidAlias", "icon_vday_cupid"),
    DEVIL("DevilAlias", "icon_vday_devil"),
    HEARTS("HeartsAlias", "icon_vday_hearts"),
    HEARTS_DARKER("HeartsDarkerAlias", "icon_vday_hearts_darker"),
    COLORFUL_DOTS("ColorfulDotsAlias", "icon_colorful_dots"),
    SNAP_BALLOON("SnapBalloonAlias", "icon_snap_balloon"),
    SNAPPY_DOODLE("SnappyDoodleAlias", "icon_snappy_doodle"),
    STEAMED_DUMPLING("SteamedDumplingAlias", "icon_steamed_dumpling"),
    NYE_CONFETTI("NyeConfettiAlias", "icon_nye_confetti"),
    NYE_DISCO_BALL("NyeDiscoBallAlias", "icon_nye_disco_ball"),
    NYE_GOLD_GHOST("NyeGoldGhostAlias", "icon_nye_gold_ghost"),
    NYE_GOLD("NyeGoldAlias", "icon_nye_gold"),
    NYE_SNOW("NyeSnowAlias", "icon_nye_snow"),
    NYE_SWIRL("NyeSwirlAlias", "icon_nye_swirl"),
    CANDY_CANE("CandyCaneAlias", "icon_candy_cane"),
    COLD("ColdAlias", "icon_cold"),
    GIFT("GiftAlias", "icon_gift"),
    ORNAMENT("OrnamentAlias", "icon_ornament"),
    DREIDEL("DreidelAlias", "icon_dreidel"),
    SNOWFLAKE("SnowflakeAlias", "icon_snowflake"),
    DIAMOND_GHOST("DiamondGhostAlias", "icon_diamond_ghost"),
    NORTHLIGHT("NorthlightAlias", "icon_northlight"),
    FALL_SCARF("FallScarfAlias", "icon_fall_scarf"),
    HARVEST_MOON("HarvestMoonAlias", "icon_harvest_moon"),
    THANKSGIVINGLEAF("thanksgivingleafAlias", "icon_thanksgivingleaf"),
    DIWALI_CLAY_LAMP("DiwaliClayLampAlias", "icon_diwali_clay_lamp"),
    DIWALI_GOLD_FRAME("DiwaliGoldFrameAlias", "icon_diwali_gold_frame"),
    DIWALI_TYPE("DiwaliTypeAlias", "icon_diwali_type"),
    GOOEY_HALLOWEEN("GooeyHalloweenAlias", "icon_gooey_halloween"),
    HALLOWEEN_EYE("HalloweenEyeAlias", "icon_halloween_eye"),
    MUMMY("MummyAlias", "icon_mummy"),
    VAMPIRE("VampireAlias", "icon_vampire"),
    FORTUNE_BALL("FortuneBallAlias", "icon_fortune_ball"),
    TOMBSTONE("TombstoneAlias", "icon_tombstone"),
    TRANSLUCENT_GHOST_HALLOWEEN("TranslucentGhostHalloweenAlias", "icon_translucent_ghost_halloween"),
    MARIACHI("MariachiAlias", "icon_mariachi"),
    WITCH("WitchAlias", "icon_witch"),
    ZOMBIE_GHOST("ZombieGhostAlias", "icon_zombie_ghost"),
    XRAY_GHOST("XrayGhostAlias", "icon_xray_ghost"),
    ALIEN("AlienAlias", "icon_alien"),
    BLUE_PRINT("BluePrintAlias", "icon_blue_print"),
    LATTE_ART("LatteArtAlias", "icon_latte_art"),
    SILK("SilkAlias", "icon_silk"),
    SUMMER_FOREST("SummerForestAlias", "icon_summer_forest"),
    ARCADE_GAME("ArcadeGameAlias", "icon_arcade_game"),
    MAGIC_WAND("MagicWandAlias", "icon_magic_wand"),
    ROSE_DREAM("RoseDreamAlias", "icon_rose_dream"),
    MUSHROOM("MushroomAlias", "icon_mushroom"),
    KAWAII("KawaiiAlias", "icon_kawaii"),
    SHARPIE_DOODLE("SharpieDoodleAlias", "icon_sharpie_doodle"),
    SNAP_CLONES("SnapClonesAlias", "icon_snap_clones"),
    PLANET("PlanetAlias", "icon_planet"),
    FURRY("FurryAlias", "icon_furry"),
    PINK_SLIME("PinkSlimeAlias", "icon_pink_slime"),
    ART_DECO("ArtDecoAlias", "icon_art_deco"),
    FRIENDSHIP_DAY_GHOST("FriendshipDayGhostAlias", "icon_friendship_day_ghost"),
    LAVA("LavaAlias", "icon_lava"),
    SPRAY_PAINT("SprayPaintAlias", "icon_spray_paint"),
    Y2K_SNAP("Y2kSnapAlias", "icon_y2k_snap"),
    ABSTRACT_FIREWORKS("AbstractFireworksAlias", "icon_abstract_fireworks"),
    SHELL_ON_BEACH("ShellOnBeachAlias", "icon_shell_on_beach"),
    TOASTED_MARSHMALLOW("ToastedMarshmallowAlias", "icon_toasted_marshmallow"),
    CLOWN("ClownAlias", "icon_clown"),
    POP_ART_SNAP("PopArtSnapAlias", "icon_pop_art_snap"),
    NEON_LIGHT("NeonLightAlias", "icon_neon_light"),
    EID_AL_ADHA("EidAlAdhaAlias", "icon_eid_al_adha"),
    RETRO_CARTOON("RetroCartoonAlias", "icon_retro_cartoon"),
    PIXEL("PixelAlias", "icon_pixel"),
    VAPORWAVE("VaporwaveAlias", "icon_vaporwave"),
    SCUBA("ScubaAlias", "icon_scuba"),
    DANCE_PARTY("DancePartyAlias", "icon_dance_party"),
    CHERRY_BLOSSOM("CherryBlossomAlias", "icon_cherry_blossom"),
    WILD_WEST("WildWestAlias", "icon_wild_west"),
    FROG("FrogAlias", "icon_frog"),
    GLITTER("GlitterAlias", "icon_glitter"),
    FAIRY("FairyAlias", "icon_fairy"),
    HOLI_POWDERS("HoliPowdersAlias", "icon_holi_powders"),
    AI_WAVE("AiWaveAlias", "icon_ai_wave"),
    DOODLE("DoodleAlias", "icon_doodle"),
    GLASS("GlassAlias", "icon_glass"),
    BLACK_MARBLE("BlackMarbleAlias", "icon_black_marble"),
    PALM("PalmAlias", "icon_palm"),
    CHILLAH_FACE("ChillahFaceAlias", "icon_chillah_face"),
    NEON_GHOST("NeonGhostAlias", "icon_neon_ghost"),
    GOLD_B("GoldBAlias", "icon_gold_b"),
    YELLOW_PINK("YellowPinkAlias", "icon_yellow_pink"),
    SILVER_ON_LEATHER("SilverOnLeatherAlias", "icon_silver_on_leather"),
    PRIDE("PrideAlias", "icon_pride"),
    FROSTED("FrostedAlias", "icon_frosted"),
    CHROME("ChromeAlias", "icon_chrome"),
    ICON_2_1("Icon21Alias", "icon_2_1"),
    ICON_2_2("Icon22Alias", "icon_2_2"),
    COLORFUL_JELLY_GHOST("ColorfulJellyGhostAlias", "icon_colorful_jelly_ghost"),
    NEON("NeonAlias", "icon_neon"),
    NEON_WAVES("NeonWavesAlias", "icon_neon_waves"),
    PURPLE("PurpleAlias", "icon_purple"),
    PINK("PinkAlias", "icon_pink"),
    TEAL("TealAlias", "icon_teal"),
    US_2("Us2Alias", "icon_us_2"),
    UK("UkAlias", "icon_uk"),
    FRANCE("FranceAlias", "icon_france"),
    UKRAINE("UkraineAlias", "icon_ukraine"),
    BOBA("BobaAlias", "icon_boba"),
    COLOR_RIBBONS("ColorRibbonsAlias", "icon_color_ribbons"),
    COOKIE_DOUGH("CookieDoughAlias", "icon_cookie_dough"),
    LEAF_PUDDLE("LeafPuddleAlias", "icon_leaf_puddle"),
    REDMAS("RedmasAlias", "icon_redmas"),
    J2("AnimalAlias", "icon_animal", true),
    K2("BalloonAlias", "icon_vday_balloon", true),
    L2("BeachChillAlias", "icon_beach_chill", true),
    M2("BlueDeniseAlias", "icon_blue_denise", true),
    N2("BubbleAlias", "icon_bubble", true),
    O2("BunnyAlias", "icon_bunny", true),
    P2("ChalkboardAlias", "icon_chalkboard", true),
    Q2("CherryBlossomsAlias", "icon_cherry_blossoms", true),
    R2("ColorWavesAlias", "icon_color_waves", true),
    S2("ConfettiAlias", "icon_confetti", true),
    T2("DenisePinkAlias", "icon_denise_pink", true),
    U2("DenisePinkBlueAlias", "icon_denise_pink_blue", true),
    V2("DiwaliFlowerAlias", "icon_diwali_flower", true),
    W2("EggAlias", "icon_egg", true),
    X2("EggSurpriseAlias", "icon_egg_surprise", true),
    Y2("FlagAlias", "icon_flag", true),
    Z2("FoliageAlias", "icon_foliage", true),
    a3("GalaxyAlias", "icon_galaxy", true),
    b3("GhostUniverseAlias", "icon_ghost_universe", true),
    c3("GiftWrapAlias", "icon_gift_wrap", true),
    d3("GingerCookieAlias", "icon_ginger_cookie", true),
    e3("GlitterStickerAlias", "icon_glitter_sticker", true),
    f3("GoldCAlias", "icon_gold_c", true),
    g3("GreenAlias", "icon_green", true),
    h3("HeartCandiesAlias", "icon_vday_heart_candies", true),
    i3("Icon23Alias", "icon_2_3", true),
    j3("Icon24Alias", "icon_2_4", true),
    k3("Icon25Alias", "icon_2_5", true),
    l3("Icon26Alias", "icon_2_6", true),
    m3("LeprechaunAlias", "icon_leprechaun", true),
    n3("Material01Alias", "icon_material_01", true),
    o3("MemphisAlias", "icon_memphis", true),
    p3("PinwheelAlias", "icon_pinwheel", true),
    q3("Plus1Alias", "icon_plus_1", true),
    r3("PopArtAlias", "icon_pop_art", true),
    s3("PoppyAlias", "icon_poppy", true),
    t3("PoolsideAlias", "icon_poolside", true),
    u3("PotOfGoldAlias", "icon_pot_of_gold", true),
    v3("PumpkinGhostAlias", "icon_pumpkin_ghost", true),
    w3("PurpleWhiteAlias", "icon_purple_white", true),
    x3("RainbowAlias", "icon_rainbow", true),
    y3("RainbowShapeAlias", "icon_rainbow_shape", true),
    z3("RamadanFlowerAlias", "icon_ramadan_flower", true),
    A3("RamadanNightAlias", "icon_ramadan_night", true),
    B3("ReindeerAlias", "icon_reindeer", true),
    C3("RubberDuckyAlias", "icon_rubber_ducky", true),
    D3("SilverRadialAlias", "icon_silver_radial", true),
    E3("SlidePuzzleAlias", "icon_slide_puzzle", true),
    F3("SparklerSpinAlias", "icon_sparkler_spin", true),
    G3("SnowmanGhostAlias", "icon_snowman_ghost", true),
    H3("SpiderWebAlias", "icon_spider_web", true),
    I3("SpringAlias", "icon_spring", true),
    J3("SunburstAlias", "icon_sunburst", true),
    K3("SweaterGhostAlias", "icon_sweater_ghost", true),
    L3("thanksgivingfullAlias", "icon_thanksgivingfull", true),
    M3("thanksgivingsignAlias", "icon_thanksgivingsign", true),
    N3("TieDyeAlias", "icon_tie_dye", true),
    O3("TulipsAlias", "icon_tulips", true),
    P3("Us1Alias", "icon_us_1", true),
    Q3("VDayRainbowAlias", "icon_vday_rainbow", true);
    
    public final String a;
    public final boolean b;
    public final String c;

    EnumC22033dd(String str, String str2, boolean z) {
        this.a = str2;
        this.b = z;
        this.c = "com.snapchat.android.".concat(str);
    }

    /* synthetic */ EnumC22033dd(String str, String str2) {
        this(str, str2, false);
    }
}
