package defpackage;

import com.snapchat.client.mediaengine.SnapMuxer;
import com.snapchat.client.messaging.Tweaks;
import org.opencv.imgproc.Imgproc;

/* JADX WARN: Enum visitor error
jadx.core.utils.exceptions.JadxRuntimeException: Init of enum g uses external variables
	at jadx.core.dex.visitors.EnumVisitor.createEnumFieldByConstructor(EnumVisitor.java:444)
	at jadx.core.dex.visitors.EnumVisitor.processEnumFieldByField(EnumVisitor.java:368)
	at jadx.core.dex.visitors.EnumVisitor.processEnumFieldByWrappedInsn(EnumVisitor.java:333)
	at jadx.core.dex.visitors.EnumVisitor.extractEnumFieldsFromFilledArray(EnumVisitor.java:318)
	at jadx.core.dex.visitors.EnumVisitor.extractEnumFieldsFromInsn(EnumVisitor.java:258)
	at jadx.core.dex.visitors.EnumVisitor.extractEnumFieldsFromInvoke(EnumVisitor.java:289)
	at jadx.core.dex.visitors.EnumVisitor.extractEnumFieldsFromInsn(EnumVisitor.java:262)
	at jadx.core.dex.visitors.EnumVisitor.convertToEnum(EnumVisitor.java:151)
	at jadx.core.dex.visitors.EnumVisitor.visit(EnumVisitor.java:100)
 */
/* JADX WARN: Failed to restore enum class, 'enum' modifier and super class removed */
/* renamed from: JWf  reason: default package */
/* loaded from: classes.dex */
public final class JWf implements InterfaceC55783zb4 {
    public static final JWf A0;
    public static final JWf A1;
    public static final JWf A2;
    public static final JWf B0;
    public static final JWf B1;
    public static final JWf B2;
    public static final JWf C0;
    public static final JWf C1;
    public static final JWf C2;
    public static final JWf D0;
    public static final JWf D1;
    public static final JWf D2;
    public static final JWf E0;
    public static final JWf E1;
    public static final JWf E2;
    public static final JWf F0;
    public static final JWf F1;
    public static final JWf F2;
    public static final JWf G0;
    public static final JWf G1;
    public static final JWf G2;
    public static final JWf H0;
    public static final JWf H1;
    public static final JWf H2;
    public static final JWf I0;
    public static final JWf I1;
    public static final JWf I2;
    public static final JWf J0;
    public static final JWf J1;
    public static final JWf J2;
    public static final JWf K0;
    public static final JWf K1;
    public static final JWf K2;
    public static final JWf L0;
    public static final JWf L1;
    public static final JWf L2;
    public static final JWf M0;
    public static final JWf M1;
    public static final JWf M2;
    public static final JWf N0;
    public static final JWf N1;
    public static final JWf N2;
    public static final JWf O0;
    public static final JWf O1;
    public static final JWf O2;
    public static final JWf P0;
    public static final JWf P1;
    public static final JWf P2;
    public static final JWf Q0;
    public static final JWf Q1;
    public static final JWf Q2;
    public static final JWf R0;
    public static final JWf R1;
    public static final JWf R2;
    public static final JWf S0;
    public static final JWf S1;
    public static final JWf S2;
    public static final JWf T0;
    public static final JWf T1;
    public static final JWf T2;
    public static final JWf U0;
    public static final JWf U1;
    public static final JWf U2;
    public static final JWf V0;
    public static final JWf V1;
    public static final JWf V2;
    public static final JWf W0;
    public static final JWf W1;
    public static final JWf W2;
    public static final JWf X;
    public static final JWf X0;
    public static final JWf X1;
    public static final JWf X2;
    public static final JWf Y;
    public static final JWf Y0;
    public static final JWf Y1;
    public static final JWf Y2;
    public static final JWf Z;
    public static final JWf Z0;
    public static final JWf Z1;
    public static final JWf Z2;
    public static final JWf a1;
    public static final JWf a2;
    public static final JWf a3;
    public static final JWf b1;
    public static final JWf b2;
    public static final JWf b3;
    public static final JWf c1;
    public static final JWf c2;
    public static final JWf c3;
    public static final JWf d1;
    public static final JWf d2;
    public static final JWf d3;
    public static final JWf e1;
    public static final JWf e2;
    public static final JWf e3;
    public static final JWf f1;
    public static final JWf f2;
    public static final JWf f3;
    public static final JWf g;
    public static final JWf g1;
    public static final JWf g2;
    public static final JWf g3;
    public static final JWf h;
    public static final JWf h1;
    public static final JWf h2;
    public static final JWf h3;
    public static final JWf i;
    public static final JWf i1;
    public static final JWf i2;
    public static final JWf i3;
    public static final JWf j;
    public static final JWf j1;
    public static final JWf j2;
    public static final /* synthetic */ JWf[] j3;
    public static final JWf k;
    public static final JWf k1;
    public static final JWf k2;
    public static final JWf l1;
    public static final JWf l2;
    public static final JWf m1;
    public static final JWf m2;
    public static final JWf n1;
    public static final JWf n2;
    public static final JWf o1;
    public static final JWf o2;
    public static final JWf p1;
    public static final JWf p2;
    public static final JWf q1;
    public static final JWf q2;
    public static final JWf r1;
    public static final JWf r2;
    public static final JWf s1;
    public static final JWf s2;
    public static final JWf t;
    public static final JWf t1;
    public static final JWf t2;
    public static final JWf u1;
    public static final JWf u2;
    public static final JWf v1;
    public static final JWf v2;
    public static final JWf w1;
    public static final JWf w2;
    public static final JWf x1;
    public static final JWf x2;
    public static final JWf y0;
    public static final JWf y1;
    public static final JWf y2;
    public static final JWf z0;
    public static final JWf z1;
    public static final JWf z2;
    public final C54249yb4 a;
    public static final JWf b = new JWf("IMAGE_TIMER_DEFAULT_VALUE", 0, KQ.Z(0));
    public static final JWf c = new JWf("VIDEO_TIMER_PLAYBACK_STATE", 1, KQ.X(KNm.a));
    public static final JWf d = new JWf("COLOR_PICKER_DEFAULT_COLOR_STATE", 2, new C54249yb4(C33744lE3.class, "{}"));
    public static final JWf e = new JWf("PINNABLE_CAPTION_ENABLED", 3, KQ.U(true));
    public static final JWf f = new JWf("DYNAMIC_CAPTIONS_V25", 4, KQ.U(true));

    static {
        C54249yb4 U = KQ.U(false);
        U.d = "fast-motion-filter-enabled";
        g = new JWf("FAST_MOTION_FILTER_ENABLED", 5, U);
        C54249yb4 U3 = KQ.U(false);
        U3.d = "SUPER_FAST_MOTION_FILTER_ENABLED";
        h = new JWf("SUPER_FAST_MOTION_FILTER_ENABLED", 6, U3);
        i = new JWf("HAS_SEEN_DIRECT_POST_STORY_WARNING", 7, KQ.U(false));
        C54249yb4 U4 = KQ.U(false);
        U4.i = 276;
        j = new JWf("HAS_SEEN_DIRECT_POST_STORY_WARNING_SUP", 8, U4);
        C54249yb4 a0 = KQ.a0(0L);
        a0.i = 820;
        k = new JWf("SAVED_STORY_PREVIEW_PROMPT_COUNT", 9, a0);
        C54249yb4 Z3 = KQ.Z(6);
        Z3.d = "PREVIEW_UCO_COLOR_COUNT";
        t = new JWf("UCO_COLOR_FILTERS_COUNT", 10, Z3);
        C54249yb4 Z4 = KQ.Z(6);
        Z4.d = "PREVIEW_UCO_AR_COUNT";
        X = new JWf("UCO_AR_FILTERS_COUNT", 11, Z4);
        Y = new JWf("UCO_FILTER_LENS_ID_FOR_TESTING", 12, KQ.i0(""));
        C54249yb4 c54249yb4 = new C54249yb4(byte[].class, IKf.i);
        c54249yb4.d = "LENSES_POST_CAPTURE_AVAILABILITY";
        Z = new JWf("LENSES_POST_CAPTURE_AVAILABILITY", 13, c54249yb4);
        G2m g2m = G2m.e;
        y0 = new JWf("UCO_DARK_OVERLAY", 14, KQ.X(g2m));
        z0 = new JWf("UCO_LOADING_SPINNER", 15, KQ.X(g2m));
        A0 = new JWf("UCO_SPLIT_SCREEN", 16, KQ.X(G2m.d));
        B0 = new JWf("UCO_CAROUSEL_RESPECT_COF", 17, KQ.U(true));
        C54249yb4 c54249yb42 = new C54249yb4(byte[].class, new byte[0]);
        c54249yb42.d = "uco_carousel_config_android";
        C0 = new JWf("UCO_CAROUSEL_CONFIG_PROTO", 18, c54249yb42);
        C54249yb4 U5 = KQ.U(false);
        U5.l("caption_sticker_suggestion");
        D0 = new JWf("CAPTION_STICKER_SUGGESTION", 19, U5);
        C54249yb4 U6 = KQ.U(false);
        U6.i = 275;
        E0 = new JWf("HAS_SEEN_SWIPE_FILTERS_ONBOARDING_MESSAGE", 20, U6);
        C54249yb4 U7 = KQ.U(false);
        U7.i = 470;
        F0 = new JWf("HAS_SEEN_SWIPE_NEWPORT_FILTERS_ONBOARDING_MESSAGE", 21, U7);
        C54249yb4 U8 = KQ.U(false);
        U8.i = 288;
        G0 = new JWf("HAS_SEEN_SOUND_TOOLS_TOOLTIP", 22, U8);
        C54249yb4 U9 = KQ.U(false);
        U9.i = 297;
        H0 = new JWf("HAS_SEEN_UNLOCKABLE_STICKER_TOOLTIP", 23, U9);
        C54249yb4 U10 = KQ.U(false);
        U10.i = 471;
        I0 = new JWf("HAS_SEEN_BLOOPS_STICKER_TOOLTIP", 24, U10);
        C54249yb4 U11 = KQ.U(false);
        U11.i = 472;
        J0 = new JWf("HAS_SEEN_GROUP_INVITE_STICKER_TOOLTIP", 25, U11);
        C54249yb4 U12 = KQ.U(false);
        U12.i = 473;
        K0 = new JWf("HAS_SEEN_OR_USED_SNAP_CROP_TOOLTIP", 26, U12);
        C54249yb4 U13 = KQ.U(false);
        U13.i = 474;
        L0 = new JWf("HAS_SEEN_MULTISNAP_DELETION_DIALOG", 27, U13);
        C54249yb4 U14 = KQ.U(false);
        U14.i = 475;
        M0 = new JWf("HAS_SEEN_MULTISNAP_TRIMMING_TOOLTIP", 28, U14);
        C54249yb4 U15 = KQ.U(false);
        U15.i = 337;
        N0 = new JWf("HAS_SEEN_POST_STORY_DIALOG", 29, U15);
        C54249yb4 U16 = KQ.U(false);
        U16.i = 476;
        O0 = new JWf("HAS_SEEN_SNAPCODE_STICKER_TOOLTIP", 30, U16);
        C54249yb4 U17 = KQ.U(false);
        U17.i = 547;
        P0 = new JWf("HAS_SEEN_MULTISNAP_USER_NOTICE", 31, U17);
        C54249yb4 Z5 = KQ.Z(0);
        Z5.i = 608;
        Q0 = new JWf("SUPERCUT_APPLY_EFFECTS_TOOLTIP_SEEN_COUNT", 32, Z5);
        C54249yb4 U18 = KQ.U(false);
        U18.i = 609;
        R0 = new JWf("SUPERCUT_CHANGE_EFFECTS_TOOLTIP_SEEN", 33, U18);
        C54249yb4 U19 = KQ.U(false);
        U19.i = 625;
        S0 = new JWf("HAS_SEEN_AUTO_CROP_ONBOARDING_DIALOG", 34, U19);
        C54249yb4 U20 = KQ.U(false);
        U20.i = 626;
        T0 = new JWf("HAS_SEEN_AUTO_CROP_ONBOARDING_TOOLTIP", 35, U20);
        C54249yb4 U21 = KQ.U(false);
        U21.i = 627;
        U0 = new JWf("AUTO_CROP_HAS_FIRST_APPLIED_EFFECT", 36, U21);
        C54249yb4 U22 = KQ.U(false);
        U22.i = 628;
        V0 = new JWf("AUTO_CROP_HAS_FIRST_REMOVED_EFFECT", 37, U22);
        C54249yb4 U23 = KQ.U(false);
        U23.i = 633;
        W0 = new JWf("HAS_SEEN_PLACE_CAPTION_TOOLTIP", 38, U23);
        C54249yb4 U24 = KQ.U(false);
        U24.d = "CT_MUSIC_VOLUME_PROMOTION";
        X0 = new JWf("MUSIC_VOLUME_PROMOTION", 39, U24);
        C54249yb4 U25 = KQ.U(false);
        U25.d = "MUSIC_SHOW_LENS_RECOMMENDATION_ON_PREVIEW";
        Y0 = new JWf("MUSIC_SHOW_LENS_RECOMMENDATION_ON_PREVIEW", 40, U25);
        C54249yb4 U26 = KQ.U(false);
        U26.d = "MUSIC_ANDROID_AUDIO_MIXING";
        Z0 = new JWf("AUDIO_MIXING", 41, U26);
        a1 = new JWf("TIME_BASED_DISCARD_LOGIC", 42, KQ.Z(15000));
        b1 = new JWf("ANDROID_PREVIEW_SWIPE_THRESHOLD", 43, KQ.Z(100));
        C54249yb4 U27 = KQ.U(false);
        U27.d = "CT_ANDROID_REPORT_FILTER_ORDER_INFO";
        c1 = new JWf("REPORT_FILTER_ORDER_INFO", 44, U27);
        C54249yb4 c54249yb43 = new C54249yb4(byte[].class, new byte[0]);
        c54249yb43.d = "POST_CAPTURE_CAROUSEL_GLOBAL_SCORE_CONFIG";
        d1 = new JWf("POST_CAPTURE_CAROUSEL_GLOBAL_SCORE_CONFIG", 45, c54249yb43);
        C54249yb4 U28 = KQ.U(false);
        U28.d = "ANDROID_POST_CAPTURE_CAROUSEL_REPLACEMENT_ENABLED";
        e1 = new JWf("POST_CAPTURE_CAROUSEL_REPLACEMENT_ENABLED", 46, U28);
        C54249yb4 c54249yb44 = new C54249yb4(IZ7.class, new IZ7());
        c54249yb44.d = "CT_DRAWING_EMOJI_LIST";
        f1 = new JWf("CT_DRAWING_EMOJI_LIST", 47, c54249yb44);
        g1 = new JWf("CLIPBOARD_DETECTOR_OPTION_SELECTED", 48, KQ.U(false));
        h1 = new JWf("CLIPBOARD_DETECTOR_ENABLED", 49, KQ.U(false));
        C54249yb4 Z6 = KQ.Z(SnapMuxer.COMMAND_GET_FASTSTART_RESULT);
        Z6.d = "camera_me_loading_ui_timeout_ms";
        i1 = new JWf("LOADING_UI_TIMEOUT_MS", 50, Z6);
        C54249yb4 U29 = KQ.U(false);
        U29.i = 486;
        j1 = new JWf("TIMELINE_MODE_RECORD_MORE_TOOLTIP", 51, U29);
        C54249yb4 U30 = KQ.U(false);
        U30.i = 603;
        k1 = new JWf("HAS_SEEN_TIMELINE_DRAFT_TOOLTIP", 52, U30);
        l1 = new JWf("CE_CAPTIONS_HAS_SEEN_BACKGROUND_TOOLTIP", 53, KQ.U(false));
        C54249yb4 U31 = KQ.U(false);
        U31.d = "PREVIEW_ANDROID_AUTO_CAPTION_ENABLED";
        m1 = new JWf("AUTO_CAPTION_ENABLED", 54, U31);
        C54249yb4 U32 = KQ.U(false);
        U32.d = "PREVIEW_ANDROID_AUTO_CAPTION_MULTISEGMENT_ENABLED";
        n1 = new JWf("AUTO_CAPTION_MULTI_SEGMENT_ENABLED", 55, U32);
        o1 = new JWf("SHOULD_SHOW_AUTO_CAPTION_PERMISSION_PROMPT", 56, KQ.U(true));
        p1 = new JWf("AUTO_CAPTION_CUSTOM_ROUTING_HEADER", 57, KQ.i0(""));
        C54249yb4 Z7 = KQ.Z(2048);
        Z7.d = "ANDROID_AUTO_CAPTION_BUFFER_SIZE";
        q1 = new JWf("AUTO_CAPTION_BUFFER_SIZE", 58, Z7);
        r1 = new JWf("HAS_SEEN_TIMED_CAPTION_TOOLTIP", 59, KQ.U(false));
        C54249yb4 U33 = KQ.U(false);
        U33.d = "CT_ANDROID_TRIM_TOOL_POLISH_ENABLED";
        s1 = new JWf("TRIM_TOOL_ACCESSIBLE_EDITING_ENABLED", 60, U33);
        C54249yb4 U34 = KQ.U(false);
        U34.d = "COMMERCE_STICKERS_ENABLED";
        t1 = new JWf("COMMERCE_STICKERS_ENABLED", 61, U34);
        C54249yb4 X3 = KQ.X(M5g.a);
        X3.d = "ANDROID_PREVIEW_SCROLLABLE_TOOLBAR";
        u1 = new JWf("PREVIEW_SCROLLABLE_TOOLBAR", 62, X3);
        v1 = new JWf("PREVIEW_MOCK_TOOLBAR_ICONS", 63, KQ.U(false));
        w1 = new JWf("PREVIEW_TOOLBAR_EXPANDED", 64, KQ.U(false));
        C54249yb4 X4 = KQ.X(Q4g.a);
        X4.d = "PREVIEW_SWIPE_DISMISS_V2_ANDROID";
        x1 = new JWf("PREVIEW_SWIPE_DOWN_V2_ANDROID", 65, X4);
        C54249yb4 Z8 = KQ.Z(1440);
        Z8.d = "PREVIEW_OVERLAY_MAX_WIDTH_IN_PORTRAIT";
        y1 = new JWf("PREVIEW_OVERLAY_MAX_WIDTH_IN_PORTRAIT", 66, Z8);
        z1 = new JWf("POST_CAPTURE_LE_SWIPE_GESTURE", 67, KQ.U(false));
        C54249yb4 U35 = KQ.U(false);
        U35.p(576);
        A1 = new JWf("PREVIEW_HAS_SEEN_POST_CAPTURE_AR_TOOLTIP", 68, U35);
        C54249yb4 U36 = KQ.U(false);
        U36.p(788);
        B1 = new JWf("PREVIEW_HAS_SEEN_CLIP_REORDER_TOOLTIP", 69, U36);
        C54249yb4 Z9 = KQ.Z(0);
        Z9.p(850);
        C1 = new JWf("PREVIEW_HAS_SEEN_SAVED_TO_DRAFT", 70, Z9);
        C54249yb4 U37 = KQ.U(false);
        U37.p(746);
        D1 = new JWf("PREVIEW_HAS_SEEN_CLIP_LEVEL_EDIT_TOOLTIP", 71, U37);
        C54249yb4 U38 = KQ.U(false);
        U38.p(747);
        E1 = new JWf("PREVIEW_HAS_SEEN_CLIP_LEVEL_EDIT_FTUE_MODAL", 72, U38);
        F1 = new JWf("FORCE_RESET_SAVE_TOOLTIP_STATUS", 73, KQ.U(false));
        G1 = new JWf("LOCALLY_USED_RECENT_CAPTIONS_CACHE", 74, KQ.i0(""));
        H1 = new JWf("PREVIEW_MENU_CAPTION_HINT_SHOW_COUNT", 75, KQ.Z(0));
        I1 = new JWf("PREVIEW_MENU_STICKER_HINT_SHOW_COUNT", 76, KQ.Z(0));
        J1 = new JWf("GEOFILTER_DEBUG", 77, KQ.U(false));
        K1 = new JWf("VOICEOVER_TOOLTIP_SHOW_COUNT", 78, KQ.Z(0));
        C54249yb4 U39 = KQ.U(false);
        U39.d = "CE_ANDROID_PINNABLE_TOOL_UI";
        L1 = new JWf("PINNABLE_TOOL_UI_ENABLED", 79, U39);
        C54249yb4 U40 = KQ.U(false);
        U40.d = "CE_ANDROID_AUDIO_EFFECTS_TOOL";
        M1 = new JWf("AUDIO_EFFECTS_TOOL_ENABLED", 80, U40);
        C54249yb4 U41 = KQ.U(false);
        U41.d = "CT_ANDROID_QUESTION_STICKER_SUGGESTION";
        N1 = new JWf("QUESTION_STICKER_SUGGESTION_ENABLED", 81, U41);
        C54249yb4 U42 = KQ.U(false);
        U42.d = "ENABLE_ANDROID_SMART_EDIT";
        O1 = new JWf("CHEERIOS_SUPERCUT_ENABLED", 82, U42);
        C54249yb4 U43 = KQ.U(false);
        U43.d = "ANDROID_CHEERIOS_AUTO_CROP_ENABLED";
        P1 = new JWf("CHEERIOS_AUTOCROP_ENABLED", 83, U43);
        C54249yb4 c54249yb45 = new C54249yb4(KE.class, b());
        c54249yb45.d = "PREVIEW_AI_CROP_TOOL_GATED_FEATURES";
        Q1 = new JWf("GENERATIVE_AI_CROP_TOOL_GATED_FEATURES", 84, c54249yb45);
        R1 = new JWf("GENERATIVE_AI_CROP_TOOL_OVERRIDE_GATED_FEATURES", 85, KQ.U(false));
        S1 = new JWf("GENERATIVE_AI_CROP_TOOL_ENHANCE_ENABLED", 86, KQ.U(false));
        T1 = new JWf("GENERATIVE_AI_CROP_TOOL_ENHANCE_USE_FIR", 87, KQ.U(false));
        U1 = new JWf("GENERATIVE_AI_CROP_TOOL_EXTEND_ENABLED", 88, KQ.U(false));
        V1 = new JWf("GENERATIVE_AI_CROP_TOOL_EXTEND_DOWNSCALE", 89, KQ.U(false));
        C54249yb4 X5 = KQ.X(EnumC12661Tz9.a);
        X5.d = "GENERATIVE_AI_CROP_TOOL_DISCLAIMER_TEXT";
        W1 = new JWf("GENERATIVE_AI_CROP_TOOL_DISCLAIMER_TEXT", 90, X5);
        C54249yb4 U44 = KQ.U(false);
        U44.p(868);
        X1 = new JWf("GENERATIVE_AI_CROP_TOOL_DISCLAIMER_ACCEPTED", 91, U44);
        C54249yb4 U45 = KQ.U(false);
        U45.p(900);
        Y1 = new JWf("GENERATIVE_AI_CAPTIONS_DISCLAIMER_ACCEPTED", 92, U45);
        C54249yb4 U46 = KQ.U(false);
        U46.p(274);
        Z1 = new JWf("HAS_SEEN_TAP_ADD_CAPTION", 93, U46);
        C54249yb4 U47 = KQ.U(false);
        U47.d = "PREVIEW_ANDROID_UCO_FILTER_STACKING_ENABLED";
        a2 = new JWf("UCO_FILTER_STACKING_ENABLED", 94, U47);
        b2 = new JWf("GROUP_UCO_FILTERS_IN_CAROUSEL", 95, KQ.U(false));
        c2 = new JWf("ENABLE_UCO_EVERYWHERE", 96, KQ.U(false));
        C54249yb4 c54249yb46 = new C54249yb4(SZl.class, new SZl());
        c54249yb46.d = "UCO_RANKING_SUPPORT_UPDATES";
        d2 = new JWf("UCO_RANKING_UPDATES", 97, c54249yb46);
        C54249yb4 U48 = KQ.U(false);
        U48.d = "CT_ANDROID_REMIX_PREVIEW_TOOLBAR_MEMORIES_ENABLED";
        e2 = new JWf("PREVIEW_TOOLBAR_MEMORIES_REMIX_TOOL_ENABLED", 98, U48);
        C54249yb4 U49 = KQ.U(false);
        U49.d = "PREVIEW_USE_DEFAULT_LOCALE_FOR_MENTION_SEARCH";
        f2 = new JWf("PREVIEW_USE_DEFAULT_LOCALE_FOR_MENTION_SEARCH", 99, U49);
        C54249yb4 X6 = KQ.X(EnumC51074wWf.a);
        X6.d = "PREVIEW_CTITEM_ANDROID";
        g2 = new JWf("PREVIEW_CTITEM_ANDROID", 100, X6);
        C54249yb4 U50 = KQ.U(true);
        U50.d = "CT_ANDROID_EDIT_MEMORIES_ENABLED";
        h2 = new JWf("PREVIEW_EDIT_MEMORIES_ENABLED", 101, U50);
        C54249yb4 U51 = KQ.U(true);
        U51.d = "CT_ANDROID_EDIT_MEMORIES_GALLERY_ENABLED";
        i2 = new JWf("PREVIEW_EDIT_MEMORIES_GALLERY_ENABLED", 102, U51);
        C54249yb4 U52 = KQ.U(false);
        U52.d = "PREVIEW_ANDROID_TOGGLE_LENS_TOOL_ENABLED";
        j2 = new JWf("PREVIEW_TOGGLE_LENS_TOOL_ENABLED", 103, U52);
        C54249yb4 U53 = KQ.U(false);
        U53.d = "PREVIEW_TOGGLE_TOOL_MULTI_STATE";
        k2 = new JWf("PREVIEW_TOGGLE_TOOL_MULTI_STATE", 104, U53);
        C54249yb4 c54249yb47 = new C54249yb4(byte[].class, new byte[0]);
        c54249yb47.d = "PREVIEW_TOGGLE_TOOL_ANDROID";
        l2 = new JWf("PREVIEW_TOGGLE_TOOL_ANDROID", 105, c54249yb47);
        C54249yb4 i0 = KQ.i0("61875520878");
        i0.d = "PREVIEW_ANDROID_TOGGLE_LENS_ID";
        m2 = new JWf("PREVIEW_TOGGLE_LENS_ID", 106, i0);
        C54249yb4 X7 = KQ.X(IYf.a);
        X7.d = "PREVIEW_ANDROID_LENS_TOOL_TYPE";
        n2 = new JWf("PREVIEW_TOGGLE_LENS_TOOL_TYPE", 107, X7);
        C54249yb4 X8 = KQ.X(HYf.a);
        X8.d = "PREVIEW_LENS_TOOL_SUPPORTED_MEDIA";
        o2 = new JWf("PREVIEW_LENS_TOOL_SUPPORTED_MEDIA_TYPE", 108, X8);
        C54249yb4 i02 = KQ.i0("");
        i02.d = "PREVIEW_ANDROID_MAGIC_ERASER_LENS_ID";
        p2 = new JWf("PREVIEW_MAGIC_ERASER_LENS_ID", Tweaks.MAX_HOURS_AFTER_STREAK_EXPIRE_TO_ENABLE_RESTORE, i02);
        q2 = new JWf("PREVIEW_REPOST_LENS_ID", Tweaks.ENABLE_STREAK_EDUCATION, KQ.i0("62696420876"));
        r2 = new JWf("PREVIEW_DEBUG_GEO_FILTER_IDS", 111, KQ.i0(""));
        C54249yb4 Z10 = KQ.Z(0);
        Z10.d = "PREVIEW_PRELOAD_STRATEGY";
        s2 = new JWf("PREVIEW_PRELOAD_STRATEGY", 112, Z10);
        C54249yb4 U54 = KQ.U(false);
        U54.d = "ADD_TO_STORY_ALERT_SHOW_ONCE";
        t2 = new JWf("ADD_TO_STORY_ALERT_SHOW_ONCE", Tweaks.DELTA_SYNC_SQLITE_SHARED_STORAGE_CACHE_SIZE, U54);
        C54249yb4 U55 = KQ.U(false);
        U55.d = "QUICK_POST_TRAY_FEATURE_UPDATES";
        u2 = new JWf("QUICK_POST_TRAY_FEATURE_UPDATES", Tweaks.FAIL_DECRYPT_FOR_DUPLEX_SNAPS_TEST_ONLY, U55);
        C54249yb4 U56 = KQ.U(false);
        U56.d = "PREVIEW_REPLY_BAR_CAROUSEL_ENABLED";
        v2 = new JWf("PREVIEW_REPLY_BAR_CAROUSEL_ENABLED", 115, U56);
        C54249yb4 U57 = KQ.U(false);
        U57.d = "PREVIEW_REPLY_BAR_MORE_FRIENDS_CONTEXT";
        w2 = new JWf("PREVIEW_REPLY_BAR_MORE_FRIENDS_CONTEXT", 116, U57);
        C54249yb4 c54249yb48 = new C54249yb4(byte[].class, new byte[0]);
        c54249yb48.d = "VISUAL_CONTEXTUAL_LENSES_IN_PREVIEW";
        x2 = new JWf("VISUAL_CONTEXTUAL_LENSES_CONFIGURATION", 117, c54249yb48);
        y2 = new JWf("ENABLE_VISUAL_CONTEXTUAL_LENSES", 118, KQ.U(false));
        C54249yb4 U58 = KQ.U(false);
        U58.d = "PREVIEW_CLASSIFICATION_MODEL_ROTATION";
        z2 = new JWf("VISUAL_CLASSIFICATION_IMAGE_ROTATION", 119, U58);
        C54249yb4 Z11 = KQ.Z(0);
        Z11.p(794);
        A2 = new JWf("PREVIEW_TOOLBAR_ADD_LENS_TOOLTIP_SEEN_COUNT", 120, Z11);
        C54249yb4 U59 = KQ.U(false);
        U59.p(884);
        B2 = new JWf("PREVIEW_MAGIC_ERASER_TOOLTIP_SEEN", 121, U59);
        C54249yb4 U60 = KQ.U(false);
        U60.d = "PREVIEW_SAVE_APPLIED_FILTERS_ONLY";
        C2 = new JWf("PREVIEW_SAVE_APPLIED_FILTERS_ONLY", 122, U60);
        C54249yb4 U61 = KQ.U(false);
        U61.d = "LENS_USE_CT_ITEMS_FROM_MIXER";
        D2 = new JWf("LENS_USE_CT_ITEMS_FROM_MIXER", 123, U61);
        E2 = new JWf("PREVIEW_POST_CAPTURE_LENS_METRICS", 124, KQ.U(false));
        C54249yb4 U62 = KQ.U(false);
        U62.d = "PREVIEW_ANDROID_MENTION_HINT_ENABLED";
        F2 = new JWf("PREVIEW_MENTION_HINT_FRAME_CAPTURE_ENABLED", 125, U62);
        C54249yb4 U63 = KQ.U(true);
        U63.d = "PREVIEW_ANDROID_MENTION_HINT_BITMAP_CONVERSION_ENABLED";
        G2 = new JWf("PREVIEW_MENTION_HINT_BITMAP_CONVERSION_ENABLED", 126, U63);
        C54249yb4 U64 = KQ.U(true);
        U64.d = "PREVIEW_ANDROID_MENTION_HINT_FACE_DETECTION_ENABLED";
        H2 = new JWf("PREVIEW_MENTION_HINT_FACE_DETECTION_ENABLED", 127, U64);
        C54249yb4 U65 = KQ.U(true);
        U65.d = "PREVIEW_ANDROID_MENTION_HINT_ENABLED";
        I2 = new JWf("PREVIEW_MENTION_HINT_ANIMATION_ENABLED", 128, U65);
        C54249yb4 a02 = KQ.a0(0L);
        a02.d = "PREVIEW_ANDROID_MENTION_HINT_INIT_DELAY";
        J2 = new JWf("PREVIEW_MENTION_HINT_INIT_DELAY", 129, a02);
        C54249yb4 U66 = KQ.U(false);
        U66.d = "PREVIEW_ANDROID_MENTION_HINT_USE_DOWN_SCALED_BITMAP";
        K2 = new JWf("PREVIEW_MENTION_HINT_USE_DOWN_SCALED_BITMAP", 130, U66);
        L2 = new JWf("PREVIEW_MENTION_HINT_SHOW_FACES", Imgproc.COLOR_RGB2YUV_YV12, KQ.U(false));
        M2 = new JWf("SKIP_CONVERT_EDITS_TO_SERIALIZED_OVERLAY", Imgproc.COLOR_BGR2YUV_YV12, KQ.U(false));
        C54249yb4 U67 = KQ.U(false);
        U67.d = "CTITEM_MIGRATION_ATTACHMENT";
        N2 = new JWf("CTITEM_MIGRATION_ATTACHMENT", Imgproc.COLOR_RGBA2YUV_YV12, U67);
        C54249yb4 U68 = KQ.U(false);
        U68.d = "CTITEM_MIGRATION_FILTER_ANDROID";
        O2 = new JWf("CTITEM_MIGRATION_FILTER", Imgproc.COLOR_BGRA2YUV_YV12, U68);
        C54249yb4 U69 = KQ.U(false);
        U69.d = "PREVIEW_ANDROID_ENABLE_SAVE_SECONDARY_OPTION";
        P2 = new JWf("PREVIEW_ENABLE_SAVE_SECONDARY_OPTION", 135, U69);
        Q2 = new JWf("PREVIEW_ADJUSTMENT_LENS_ID", 136, KQ.i0(""));
        C54249yb4 U70 = KQ.U(false);
        U70.d = "ANDROID_SCAN_QR_CODE_IN_POST_CAPTURE";
        R2 = new JWf("SCAN_QR_CODE_IN_POST_CAPTURE", 137, U70);
        C54249yb4 U71 = KQ.U(false);
        U71.d = "ANDROID_SNAPCODE_BANNER_IN_POST_CAPTURE";
        S2 = new JWf("SNAPCODE_BANNER_IN_POST_CAPTURE", 138, U71);
        C54249yb4 U72 = KQ.U(false);
        U72.d = "ANDROID_WATERMARK_AI_MODE_PREVIEW_EXPORT";
        T2 = new JWf("PREVIEW_WATERMARK_AI_MODE_MEDIA", Imgproc.COLOR_COLORCVT_MAX, U72);
        U2 = new JWf("PREVIEW_FULL_FRAME_RETOUCH_LENS_ID", 140, KQ.i0(""));
        C54249yb4 Z12 = KQ.Z(0);
        Z12.d = "PREVIEW_MUSIC_ENTRY_REDESIGN";
        V2 = new JWf("PREVIEW_MUSIC_ENTRY_REDESIGN", 141, Z12);
        C54249yb4 U73 = KQ.U(false);
        U73.d = "ENABLE_ADD_SOUND_PILL_IN_MEMORIES_OPERA";
        W2 = new JWf("ENABLE_ADD_SOUND_PILL_IN_MEMORIES_OPERA", 142, U73);
        C54249yb4 U74 = KQ.U(false);
        U74.d = "SEND_SNAPDOC_TO_MEMORIES";
        X2 = new JWf("SEND_SNAPDOC_TO_MEMORIES", 143, U74);
        C54249yb4 U75 = KQ.U(false);
        U75.d = "SEND_SNAPDOC_TO_CAMERA_ROLL";
        Y2 = new JWf("SEND_SNAPDOC_TO_CAMERA_ROLL", 144, U75);
        C54249yb4 U76 = KQ.U(false);
        U76.d = "PREVIEW_SEND_SNAPDOC_TO_MESSAGING";
        Z2 = new JWf("SEND_SNAPDOC_TO_MESSAGING", 145, U76);
        C54249yb4 U77 = KQ.U(false);
        U77.d = "PREVIEW_REALTIME_EDITS_ANDROID";
        a3 = new JWf("PREVIEW_REALTIME_EDITS_ANDROID", 146, U77);
        b3 = new JWf("ENABLE_SNAP_EDITOR", 147, KQ.U(false));
        C54249yb4 U78 = KQ.U(false);
        U78.d = "HEADLESS_SNAP_EDITOR_CREATE_VIEW";
        c3 = new JWf("HEADLESS_SNAP_EDITOR_CREATE_VIEW", 148, U78);
        C54249yb4 U79 = KQ.U(false);
        U79.d = "HEADLESS_SNAP_EDITOR_PARSE_SNAPDOC";
        d3 = new JWf("HEADLESS_SNAP_EDITOR_PARSE_SNAPDOC", 149, U79);
        C54249yb4 U80 = KQ.U(false);
        U80.d = "PREVIEW_USE_SNAPDOC_FROM_MEMORIES";
        e3 = new JWf("PREVIEW_USE_SNAPDOC_FROM_MEMORIES", 150, U80);
        C54249yb4 i03 = KQ.i0("");
        i03.d = "PREVIEW_ANDROID_AI_MODE_LENS_ID";
        f3 = new JWf("PREVIEW_AI_MODE_LENS_ID", 151, i03);
        C54249yb4 U81 = KQ.U(false);
        U81.p(932);
        g3 = new JWf("PREVIEW_AI_MODE_DISCLAIMER_ACCEPTED", 152, U81);
        C54249yb4 U82 = KQ.U(false);
        U82.d = "PREVIEW_TOOLBAR_MUSIC_ENABLED";
        h3 = new JWf("PREVIEW_TOOLBAR_MUSIC_ENABLED", 153, U82);
        C54249yb4 U83 = KQ.U(false);
        U83.d = "PREVIEW_ANDROID_COMPOSER_CAPTION_CAROUSEL";
        i3 = new JWf("PREVIEW_COMPOSER_CAPTION_CAROUSEL_ENABLED", 154, U83);
        j3 = a();
    }

    public JWf(String str, int i4, C54249yb4 c54249yb4) {
        this.a = c54249yb4;
    }

    public static /* synthetic */ JWf[] a() {
        return new JWf[]{b, c, d, e, f, g, h, i, j, k, t, X, Y, Z, y0, z0, A0, B0, C0, D0, E0, F0, G0, H0, I0, J0, K0, L0, M0, N0, O0, P0, Q0, R0, S0, T0, U0, V0, W0, X0, Y0, Z0, a1, b1, c1, d1, e1, f1, g1, h1, i1, j1, k1, l1, m1, n1, o1, p1, q1, r1, s1, t1, u1, v1, w1, x1, y1, z1, A1, B1, C1, D1, E1, F1, G1, H1, I1, J1, K1, L1, M1, N1, O1, P1, Q1, R1, S1, T1, U1, V1, W1, X1, Y1, Z1, a2, b2, c2, d2, e2, f2, g2, h2, i2, j2, k2, l2, m2, n2, o2, p2, q2, r2, s2, t2, u2, v2, w2, x2, y2, z2, A2, B2, C2, D2, E2, F2, G2, H2, I2, J2, K2, L2, M2, N2, O2, P2, Q2, R2, S2, T2, U2, V2, W2, X2, Y2, Z2, a3, b3, c3, d3, e3, f3, g3, h3, i3};
    }

    public static KE b() {
        KE ke = new KE();
        ke.b = false;
        int i4 = ke.a;
        ke.h = false;
        ke.c = false;
        ke.g = false;
        ke.e = true;
        ke.f = false;
        ke.a = i4 | 63;
        JE je = new JE();
        je.b = 4096;
        int i5 = je.a;
        je.c = 4096;
        je.d = 0.625f;
        je.a = i5 | 7;
        ke.d = je;
        return ke;
    }

    public static JWf valueOf(String str) {
        return (JWf) Enum.valueOf(JWf.class, str);
    }

    public static JWf[] values() {
        return (JWf[]) j3.clone();
    }

    @Override // defpackage.InterfaceC55783zb4
    public final EnumC51183wb4 e() {
        return EnumC51183wb4.A0;
    }

    @Override // defpackage.InterfaceC55783zb4
    public final String getName() {
        return name();
    }

    @Override // defpackage.InterfaceC55783zb4
    public final C54249yb4 x() {
        return this.a;
    }
}
