package defpackage;

/* renamed from: L7  reason: default package */
/* loaded from: classes8.dex */
public enum L7 implements I58 {
    DEFAULT(0),
    STORY_PLAYER(1),
    STORY_PLAYER_CONTEXT_MENU(2),
    PROFILE_ACTION_MENU(3),
    PROFILE_CREATE_KEBAB(4),
    PROFILE_CREATE_KEBAB_TOOLTIP(5),
    PROFILE_CREATE_ACTIVITY_CARD(6),
    PROFILE_CREATE_EVERGREEN_CELL(21),
    PROFILE_CREATE_FORCED_ONBOARDING(23),
    PROFILE_ONBOARD_SNAP_STAR(22),
    PROFILE_HIGHLIGHT_ACTION_MENU(7),
    PROFILE_LENS_ACTION_MENU(8),
    ACTIVITY_CARD_LENS_CREATOR(9),
    ACTIVITY_CARD_EST_CREATOR(10),
    ACTIVITY_CARD_PUBLIC_USER(11),
    PUBLIC_PROFILE_CELL(12),
    FORCED_ONBOARDING(13),
    PLAYER(14),
    PAYOUT_INFORMATION(15),
    BUSINESS_INFORMATION(16),
    GUARDIAN_INFORMATION(17),
    SECURITY_CHECK(18),
    PAYOUT_INFORMATION_WITH_BIRTHDAY(19),
    PAYOUT_INFORMATION_WITHOUT_BIRTHDAY(20),
    PAYOUT_ONBOARDING_STEPS(52),
    PROFILE_SPOTLIGHT_ACTION_MENU(24),
    PROFILE_STORIES_ACTION_MENU(25),
    STORIES_TAB(26),
    SPOTLIGHT_TAB(27),
    EDIT_PROFILE_SETTINGS_MENU(28),
    PROFILE_MANAGEMENT_CELL(29),
    QUICK_POST_MENU(30),
    SEND_TO_MENU(31),
    PROFILE_INSIGHTS_SUMMARY(32),
    PROFILE_INSIGHTS_PUBLIC_STORY(33),
    PROFILE_INSIGHTS_LENSES(34),
    PROFILE_INSIGHTS_SPOTLIGHT(35),
    PROFILE_INSIGHTS_HIGHLIGHTS(36),
    PROFILE_INSIGHTS_AUDIENCE(64),
    PROFILE_INSIGHTS_SAVED_STORY(65),
    PROFILE_INSIGHTS_PROFILE(66),
    PROFILE_CREATE_SAVED_STORY(62),
    PROFILE_EDIT_AND_REVIEW_SAVED_STORY(63),
    PROFILE_CREATE_CAMEOS_IMAGE(37),
    PROFILE_CREATE_BITMOJI_IMAGE(38),
    STORY_REPLY_SNAP(39),
    STORY_REPLY_QUOTE(40),
    STORY_REPLY_CHAT(41),
    SNAP_PRO_SNAP_ADDED_NOTIFICATION(67),
    SNAP_PRO_SNAP_DELETED_NOTIFICATION(68),
    PUBLIC_PROFILE_ROLE_UPDATE_NOTIFICATION(69),
    SPOTLIGHT_REPLY_SNAP(42),
    SPOTLIGHT_REPLY_APPROVE(43),
    SPOTLIGHT_REPLY_QUOTE(71),
    SPOTLIGHT_REPLY_REJECT(44),
    SPOTLIGHT_STATUS_SNAP(45),
    SPOTLIGHT_STATUS_SUBMITTED(46),
    SPOTLIGHT_STATUS_LIVE(47),
    SPOTLIGHT_STATUS_REJECTED(48),
    SPOTLIGHT_REWARDS_ELIGIBILITY(70),
    STORY_REPLY(49),
    SPOTLIGHT_REPLY(50),
    SPOTLIGHT_STATUS(51),
    PAY_TO_PROMOTE_PUBLIC_STORY(53),
    PAY_TO_PROMOTE_SAVED_STORY(54),
    PAY_TO_PROMOTE_SPOTLIGHT(55),
    MIDROLL_ELIGIBILITY_NOTIFICATION(56),
    ONBOARDING_REMINDER_NOTIFICATION(57),
    TAX_VERIFICATION_NOTIFICATION(58),
    BEST_PRACTICES_NOTIFICATION(59),
    EXPIRING_CRYSTALS_NOTIFICATION(60),
    PAYOUT_VERIFICATION_NOTIFICATION(61);
    
    public final int a;

    L7(int i) {
        this.a = i;
    }

    @Override // defpackage.I58
    public final int a() {
        return this.a;
    }
}
