package defpackage;

/* renamed from: TAf  reason: default package */
/* loaded from: classes.dex */
public enum TAf implements I58 {
    STARTUP_COMPLETE(0),
    STARTUP_ABORTED(15),
    STARTUP_ERRORED(16),
    FEATURE_STARTUP_COMPLETE(1),
    FIRST_UI_RENDERED(2),
    NON_DESTINATION_FEATURE_STARTUP_COMPLETE(3),
    ANDROID_SIGNAL_CATCHER_THREAD_CREATION(12),
    ANDROID_PROCESS_CREATION(4),
    ANDROID_APP_CLASS_LOAD(5),
    ANDROID_APP_CTOR_START(31),
    ANDROID_APP_CTOR_END(32),
    ANDROID_APP_INJECT_START(33),
    ANDROID_APP_INJECT_END(34),
    ANDROID_APP_POST_INJECT_START(35),
    ANDROID_APP_POST_INJECT_END(36),
    ANDROID_APP_CREATE_START(6),
    ANDROID_APP_CREATE_END(7),
    ANDROID_ACTIVITY_LAUNCH_START(14),
    ANDROID_MAIN_ACT_CTOR_START(8),
    ANDROID_MAIN_ACT_CTOR_END(9),
    ANDROID_MAIN_ACT_CREATE_START(17),
    ANDROID_MAIN_ACT_CREATE_END(18),
    ANDROID_MAIN_ACT_INJECT_START(37),
    ANDROID_MAIN_ACT_INJECT_END(38),
    ANDROID_MAIN_ACT_POST_CREATE_START(19),
    ANDROID_MAIN_ACT_POST_CREATE_END(20),
    ANDROID_MAIN_ACT_START_START(21),
    ANDROID_MAIN_ACT_START_END(22),
    ANDROID_MAIN_ACT_RESUME_START(23),
    ANDROID_MAIN_ACT_RESUME_END(24),
    ANDROID_MAIN_ACT_ON_NEW_INTENT_START(39),
    ANDROID_MAIN_ACT_ON_NEW_INTENT_END(40),
    ANDROID_MAIN_ACT_RESTART_START(41),
    ANDROID_MAIN_ACT_RESTART_END(42),
    ANDROID_MAIN_ACT_POST_RESUME_START(10),
    ANDROID_MAIN_ACT_POST_RESUME_END(11),
    ANDROID_MAIN_ACT_PAUSE_START(25),
    ANDROID_MAIN_ACT_PAUSE_END(26),
    ANDROID_PAUSED_IMPORTANCE_FOREGROUND(27),
    ANDROID_PAUSED_IMPORTANCE_NOT_FOREGROUND(28),
    ANDROID_DEEPLINK_GET_PAGE_FROM_INTENT_START(29),
    ANDROID_DEEPLINK_GET_PAGE_FROM_INTENT_END(30);
    
    public final int a;

    TAf(int i) {
        this.a = i;
    }

    @Override // defpackage.I58
    public final int a() {
        return this.a;
    }
}
