package defpackage;

/* renamed from: TJ3  reason: default package */
/* loaded from: classes8.dex */
public enum TJ3 implements I58 {
    VIEW_PRODUCT(0),
    ADD_TO_BAG(1),
    CART_ICON(2),
    BACK_ARROW_ICON(3),
    CLOSE_CROSS_ICON(4),
    PRODUCT_DESCRIPTION_EXPAND(5),
    PRODUCT_QUANTITY(6),
    PRODUCT_REMOVE(7),
    SEE_RETURNS_POLICY(8),
    GO_TO_CHECKOUT(9),
    GO_TO_CHECKOUT_WEBVIEW(10),
    MERCHANT_TERMS(11),
    SNAPCHAT_TERMS(12),
    SAME_ADDRESS_AS_SHIPPING(13),
    PLACE_ORDER(14),
    VIEW_RECEIPT(15),
    DISMISS(16),
    SAVE(17),
    REMOVE(18),
    MERCHANT_SUPPORT_URL(19),
    MERCHANT_CONTACT_EMAIL(20),
    LENS_CTA(21),
    SNAP_STORE_SETTINGS_CELL(22),
    SPECTACLES_SETTINGS_BUY(23),
    CARD_IO_CAMERA(24),
    BITMOJI_MERCH(25),
    SWAP(26),
    TINT(27),
    SEARCH_SUGGESTION(28),
    CLEAR_SEARCH(29),
    EDIT_OUTFIT(30),
    EDIT_BITMOJI(31),
    ATTACH_BUTTON(32),
    REMOVE_ATTACH_BUTTON(33),
    CAMERA_TOOLBAR_ATTACH_BUTTON(34),
    ACTION_SHEET(35),
    SHOP_NOW(36),
    CALLOUT_BAR(37),
    UNFILLED_HEART(38),
    FILLED_HEART(39),
    SHARING_BUTTON(40),
    VIEW_ON_WEBSITE(41),
    EXTERNAL_BROWSER(46),
    EXTERNAL_DEEPLINK(47),
    TRY_ON_BUTTON(42),
    SIZE_REC_BUTTON(43),
    CLEAR_FIT_PROFILE_BUTTON(44),
    EDIT_FIT_PROFILE_BUTTON(45),
    SCREENSHOP_ONBOARDING_NEW_USER_POPUP_GREAT(48),
    SCREENSHOP_ONBOARDING_NEW_USER_POPUP_TRY_IT_NOW(49),
    SCREENSHOP_ONBOARDING_NEW_USER_EMBEDDED_TRY_IT_NOW(50),
    SCREENSHOP_ONBOARDING_EXISTING_USER_POPUP_GREAT(51),
    SCREENSHOP_ONBOARDING_EXISTING_USER_EMBEDDED_GREAT(52),
    SHOPPABLE_RECAP_SHOP_BUTTON(53);
    
    public final int a;

    TJ3(int i) {
        this.a = i;
    }

    @Override // defpackage.I58
    public final int a() {
        return this.a;
    }
}
