package com.snapchat.client.messaging;

/* loaded from: classes8.dex */
public enum ContentType {
    UNKNOWN,
    SNAP,
    CHAT,
    EXTERNAL_MEDIA,
    SHARE,
    NOTE,
    STICKER,
    STATUS,
    LOCATION,
    STATUS_SAVE_TO_CAMERA_ROLL,
    STATUS_CONVERSATION_CAPTURE_SCREENSHOT,
    STATUS_CONVERSATION_CAPTURE_RECORD,
    STATUS_CALL_MISSED_VIDEO,
    STATUS_CALL_MISSED_AUDIO,
    LIVE_LOCATION_SHARE,
    CREATIVE_TOOL_ITEM,
    FAMILY_CENTER_INVITE,
    FAMILY_CENTER_ACCEPT,
    FAMILY_CENTER_LEAVE,
    STATUS_PLUS_GIFT,
    PROMPT_LENS_RESPONSE,
    TINY_SNAP,
    STATUS_COUNTDOWN,
    MAP_REACTION
}
