package com.snapchat.client.messaging;

/* loaded from: classes8.dex */
public enum ValidateOrderStepOption {
    RELEASEMESSAGEUPDATEDOESNOTBLOCK,
    RELEASEMESSAGEUPDATEDOESNOTBLOCKEXCEPTOTHERRELEASES,
    RELEASEWATERMARKDOESNOTBLOCK,
    READMESSAGEUPDATEANDUPDATEWATERMARKDONOTBLOCK,
    MESSAGESENDISNOTBLOCKED
}
