.class public final Lcq4;
.super Ljava/lang/Object;
.source "SourceFile"

# interfaces
.implements Ljava/util/concurrent/Callable;


# instance fields
.field public final synthetic a:I

.field public final synthetic b:I

.field public final synthetic c:Z

.field public final synthetic d:Ljava/lang/Object;

.field public final synthetic e:Ljava/lang/Object;


# direct methods
.method public constructor <init>(ILsnj;ZLWAi;)V
    .locals 1

    .line 1
    invoke-direct {p0}, Ljava/lang/Object;-><init>()V

    const/4 v0, 0x1

    .line 2
    iput v0, p0, Lcq4;->a:I

    .line 3
    iput p1, p0, Lcq4;->b:I

    iput-object p2, p0, Lcq4;->d:Ljava/lang/Object;

    iput-boolean p3, p0, Lcq4;->c:Z

    iput-object p4, p0, Lcq4;->e:Ljava/lang/Object;

    return-void
.end method

.method public constructor <init>(Lpq4;Lbv4;IZ)V
    .locals 1

    .line 4
    invoke-direct {p0}, Ljava/lang/Object;-><init>()V

    const/4 v0, 0x0

    .line 5
    iput v0, p0, Lcq4;->a:I

    .line 6
    iput-object p1, p0, Lcq4;->d:Ljava/lang/Object;

    iput-object p2, p0, Lcq4;->e:Ljava/lang/Object;

    iput p3, p0, Lcq4;->b:I

    iput-boolean p4, p0, Lcq4;->c:Z

    return-void
.end method


# virtual methods
.method public final call()Ljava/lang/Object;
    .locals 36

    .line 1
    move-object/from16 v0, p0

    .line 2
    .line 3
    iget v1, v0, Lcq4;->a:I

    .line 4
    .line 5
    const/4 v2, 0x3

    .line 6
    const/4 v3, 0x0

    .line 7
    const/4 v4, 0x1

    .line 8
    const/16 v5, 0x8

    .line 9
    .line 10
    const/4 v6, 0x0

    .line 11
    packed-switch v1, :pswitch_data_0

    .line 12
    .line 13
    .line 14
    sget-object v1, Lnrk;->b:Ljava/util/LinkedHashMap;

    .line 15
    .line 16
    iget-object v1, v0, Lcq4;->d:Ljava/lang/Object;

    .line 17
    .line 18
    iget v7, v0, Lcq4;->b:I

    .line 19
    .line 20
    const/4 v8, 0x6

    .line 21
    const-string v9, "External Url is null"

    .line 22
    .line 23
    if-ne v7, v8, :cond_1

    .line 24
    .line 25
    check-cast v1, Lsnj;

    .line 26
    .line 27
    iget-object v2, v1, Lsnj;->a:Lsyj;

    .line 28
    .line 29
    iget-object v2, v2, Lsyj;->j:Ljava/lang/String;

    .line 30
    .line 31
    if-eqz v2, :cond_0

    .line 32
    .line 33
    new-instance v3, LoX9;

    .line 34
    .line 35
    iget-object v1, v1, Lsnj;->a:Lsyj;

    .line 36
    .line 37
    iget-object v1, v1, Lsyj;->b:Lk3m;

    .line 38
    .line 39
    new-instance v4, LlX9;

    .line 40
    .line 41
    invoke-direct {v4, v2, v2, v6}, LlX9;-><init>(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V

    .line 42
    .line 43
    .line 44
    invoke-direct {v3, v1, v4}, LoX9;-><init>(Lk3m;LlX9;)V

    .line 45
    .line 46
    .line 47
    goto/16 :goto_8

    .line 48
    .line 49
    :cond_0
    new-instance v1, Ljava/lang/IllegalArgumentException;

    .line 50
    .line 51
    invoke-direct {v1, v9}, Ljava/lang/IllegalArgumentException;-><init>(Ljava/lang/String;)V

    .line 52
    .line 53
    .line 54
    throw v1

    .line 55
    :cond_1
    if-ne v7, v5, :cond_5

    .line 56
    .line 57
    check-cast v1, Lsnj;

    .line 58
    .line 59
    iget-object v2, v1, Lsnj;->a:Lsyj;

    .line 60
    .line 61
    iget-object v2, v2, Lsyj;->o:Ljava/lang/Boolean;

    .line 62
    .line 63
    sget-object v3, Ljava/lang/Boolean;->TRUE:Ljava/lang/Boolean;

    .line 64
    .line 65
    invoke-static {v2, v3}, LK1c;->m(Ljava/lang/Object;Ljava/lang/Object;)Z

    .line 66
    .line 67
    .line 68
    move-result v2

    .line 69
    if-eqz v2, :cond_3

    .line 70
    .line 71
    iget-object v2, v1, Lsnj;->a:Lsyj;

    .line 72
    .line 73
    iget-object v2, v2, Lsyj;->k:Ljava/lang/String;

    .line 74
    .line 75
    if-eqz v2, :cond_2

    .line 76
    .line 77
    goto :goto_0

    .line 78
    :cond_2
    new-instance v1, Ljava/lang/IllegalArgumentException;

    .line 79
    .line 80
    const-string v2, "Missing AttachmentUrl for autogenerated sticker"

    .line 81
    .line 82
    invoke-direct {v1, v2}, Ljava/lang/IllegalArgumentException;-><init>(Ljava/lang/String;)V

    .line 83
    .line 84
    .line 85
    throw v1

    .line 86
    :cond_3
    iget-object v2, v1, Lsnj;->a:Lsyj;

    .line 87
    .line 88
    iget-object v2, v2, Lsyj;->j:Ljava/lang/String;

    .line 89
    .line 90
    if-eqz v2, :cond_4

    .line 91
    .line 92
    :goto_0
    new-instance v2, LTgj;

    .line 93
    .line 94
    iget-object v1, v1, Lsnj;->a:Lsyj;

    .line 95
    .line 96
    iget-object v4, v1, Lsyj;->b:Lk3m;

    .line 97
    .line 98
    new-instance v12, LRgj;

    .line 99
    .line 100
    iget-object v6, v1, Lsyj;->k:Ljava/lang/String;

    .line 101
    .line 102
    iget-object v7, v1, Lsyj;->j:Ljava/lang/String;

    .line 103
    .line 104
    iget-object v8, v1, Lsyj;->l:Ljava/lang/String;

    .line 105
    .line 106
    iget-object v9, v1, Lsyj;->m:Ljava/lang/String;

    .line 107
    .line 108
    iget-object v1, v1, Lsyj;->o:Ljava/lang/Boolean;

    .line 109
    .line 110
    invoke-static {v1, v3}, LK1c;->m(Ljava/lang/Object;Ljava/lang/Object;)Z

    .line 111
    .line 112
    .line 113
    move-result v10

    .line 114
    iget-boolean v11, v0, Lcq4;->c:Z

    .line 115
    .line 116
    move-object v5, v12

    .line 117
    invoke-direct/range {v5 .. v11}, LRgj;-><init>(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;ZZ)V

    .line 118
    .line 119
    .line 120
    invoke-direct {v2, v4, v12}, LTgj;-><init>(Lk3m;LRgj;)V

    .line 121
    .line 122
    .line 123
    :goto_1
    move-object v3, v2

    .line 124
    goto/16 :goto_8

    .line 125
    .line 126
    :cond_4
    new-instance v1, Ljava/lang/IllegalArgumentException;

    .line 127
    .line 128
    const-string v2, "Partner Sticker\'s external url is null"

    .line 129
    .line 130
    invoke-direct {v1, v2}, Ljava/lang/IllegalArgumentException;-><init>(Ljava/lang/String;)V

    .line 131
    .line 132
    .line 133
    throw v1

    .line 134
    :cond_5
    const-string v5, "Sticker id is null"

    .line 135
    .line 136
    if-nez v7, :cond_7

    .line 137
    .line 138
    check-cast v1, Lsnj;

    .line 139
    .line 140
    iget-object v2, v1, Lsnj;->a:Lsyj;

    .line 141
    .line 142
    iget-object v2, v2, Lsyj;->p:Ljava/lang/String;

    .line 143
    .line 144
    if-eqz v2, :cond_6

    .line 145
    .line 146
    new-instance v3, LaZ7;

    .line 147
    .line 148
    iget-object v1, v1, Lsnj;->a:Lsyj;

    .line 149
    .line 150
    iget-object v1, v1, Lsyj;->b:Lk3m;

    .line 151
    .line 152
    new-instance v5, LzZ7;

    .line 153
    .line 154
    invoke-static {v2}, LPY7;->a(Ljava/lang/String;)Ljava/lang/String;

    .line 155
    .line 156
    .line 157
    move-result-object v6

    .line 158
    invoke-direct {v5, v2, v6}, LzZ7;-><init>(Ljava/lang/String;Ljava/lang/String;)V

    .line 159
    .line 160
    .line 161
    invoke-direct {v3, v1, v5, v4}, LaZ7;-><init>(Lk3m;LzZ7;I)V

    .line 162
    .line 163
    .line 164
    goto/16 :goto_8

    .line 165
    .line 166
    :cond_6
    new-instance v1, Ljava/lang/IllegalArgumentException;

    .line 167
    .line 168
    invoke-direct {v1, v5}, Ljava/lang/IllegalArgumentException;-><init>(Ljava/lang/String;)V

    .line 169
    .line 170
    .line 171
    throw v1

    .line 172
    :cond_7
    const/4 v8, 0x2

    .line 173
    if-ne v7, v8, :cond_c

    .line 174
    .line 175
    check-cast v1, Lsnj;

    .line 176
    .line 177
    iget-object v2, v1, Lsnj;->a:Lsyj;

    .line 178
    .line 179
    iget-object v8, v2, Lsyj;->p:Ljava/lang/String;

    .line 180
    .line 181
    if-eqz v8, :cond_b

    .line 182
    .line 183
    iget-object v2, v2, Lsyj;->r:LCbl;

    .line 184
    .line 185
    invoke-virtual {v2}, LCbl;->getValue()Ljava/lang/Object;

    .line 186
    .line 187
    .line 188
    move-result-object v2

    .line 189
    move-object v10, v2

    .line 190
    check-cast v10, Ljava/lang/String;

    .line 191
    .line 192
    if-eqz v10, :cond_a

    .line 193
    .line 194
    iget-object v2, v1, Lsnj;->a:Lsyj;

    .line 195
    .line 196
    iget-object v2, v2, Lsyj;->u:Ljava/lang/String;

    .line 197
    .line 198
    if-eqz v2, :cond_8

    .line 199
    .line 200
    new-instance v6, LLT4;

    .line 201
    .line 202
    invoke-direct {v6, v2}, LLT4;-><init>(Ljava/lang/String;)V

    .line 203
    .line 204
    .line 205
    :cond_8
    move-object v14, v6

    .line 206
    new-instance v2, Lhg1;

    .line 207
    .line 208
    iget-object v1, v1, Lsnj;->a:Lsyj;

    .line 209
    .line 210
    iget-object v5, v1, Lsyj;->b:Lk3m;

    .line 211
    .line 212
    iget-object v9, v1, Lsyj;->s:Ljava/lang/String;

    .line 213
    .line 214
    if-eqz v14, :cond_9

    .line 215
    .line 216
    const/4 v13, 0x1

    .line 217
    goto :goto_2

    .line 218
    :cond_9
    const/4 v13, 0x0

    .line 219
    :goto_2
    sget-object v12, LMt8;->z1:LMt8;

    .line 220
    .line 221
    new-instance v1, Lag1;

    .line 222
    .line 223
    iget-boolean v11, v0, Lcq4;->c:Z

    .line 224
    .line 225
    const/16 v16, 0x120

    .line 226
    .line 227
    const/4 v15, 0x0

    .line 228
    move-object v7, v1

    .line 229
    invoke-direct/range {v7 .. v16}, Lag1;-><init>(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;ZLMt8;ZLLT4;II)V

    .line 230
    .line 231
    .line 232
    invoke-direct {v2, v5, v1}, Lhg1;-><init>(Lk3m;Lag1;)V

    .line 233
    .line 234
    .line 235
    goto :goto_1

    .line 236
    :cond_a
    new-instance v1, Ljava/lang/IllegalArgumentException;

    .line 237
    .line 238
    const-string v2, "Missing avatar id!"

    .line 239
    .line 240
    invoke-direct {v1, v2}, Ljava/lang/IllegalArgumentException;-><init>(Ljava/lang/String;)V

    .line 241
    .line 242
    .line 243
    throw v1

    .line 244
    :cond_b
    new-instance v1, Ljava/lang/IllegalArgumentException;

    .line 245
    .line 246
    invoke-direct {v1, v5}, Ljava/lang/IllegalArgumentException;-><init>(Ljava/lang/String;)V

    .line 247
    .line 248
    .line 249
    throw v1

    .line 250
    :cond_c
    const/16 v8, 0xb

    .line 251
    .line 252
    if-ne v7, v8, :cond_10

    .line 253
    .line 254
    new-instance v3, LcYi;

    .line 255
    .line 256
    check-cast v1, Lsnj;

    .line 257
    .line 258
    iget-object v2, v1, Lsnj;->a:Lsyj;

    .line 259
    .line 260
    iget-object v4, v2, Lsyj;->b:Lk3m;

    .line 261
    .line 262
    new-instance v5, LWXi;

    .line 263
    .line 264
    iget-object v2, v2, Lsyj;->E:LhO3;

    .line 265
    .line 266
    if-eqz v2, :cond_d

    .line 267
    .line 268
    iget-object v2, v2, LhO3;->c:Ljava/lang/String;

    .line 269
    .line 270
    goto :goto_3

    .line 271
    :cond_d
    move-object v2, v6

    .line 272
    :goto_3
    invoke-static {v2}, Lp2m;->V(Ljava/lang/String;)Ljava/lang/String;

    .line 273
    .line 274
    .line 275
    move-result-object v2

    .line 276
    iget-object v7, v1, Lsnj;->a:Lsyj;

    .line 277
    .line 278
    iget-object v7, v7, Lsyj;->E:LhO3;

    .line 279
    .line 280
    if-eqz v7, :cond_e

    .line 281
    .line 282
    iget-object v7, v7, LhO3;->d:Ljava/lang/String;

    .line 283
    .line 284
    goto :goto_4

    .line 285
    :cond_e
    move-object v7, v6

    .line 286
    :goto_4
    invoke-static {v7}, Lp2m;->V(Ljava/lang/String;)Ljava/lang/String;

    .line 287
    .line 288
    .line 289
    move-result-object v7

    .line 290
    iget-object v8, v1, Lsnj;->a:Lsyj;

    .line 291
    .line 292
    iget-object v8, v8, Lsyj;->E:LhO3;

    .line 293
    .line 294
    if-eqz v8, :cond_f

    .line 295
    .line 296
    iget-object v6, v8, LhO3;->e:Ljava/lang/String;

    .line 297
    .line 298
    :cond_f
    invoke-static {v6}, Lp2m;->V(Ljava/lang/String;)Ljava/lang/String;

    .line 299
    .line 300
    .line 301
    move-result-object v6

    .line 302
    iget-object v1, v1, Lsnj;->a:Lsyj;

    .line 303
    .line 304
    iget-object v1, v1, Lsyj;->j:Ljava/lang/String;

    .line 305
    .line 306
    invoke-static {v1}, Lp2m;->V(Ljava/lang/String;)Ljava/lang/String;

    .line 307
    .line 308
    .line 309
    move-result-object v1

    .line 310
    invoke-direct {v5, v2, v7, v6, v1}, LWXi;-><init>(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V

    .line 311
    .line 312
    .line 313
    invoke-direct {v3, v4, v5}, LcYi;-><init>(Lk3m;LWXi;)V

    .line 314
    .line 315
    .line 316
    goto/16 :goto_8

    .line 317
    .line 318
    :cond_10
    iget-boolean v6, v0, Lcq4;->c:Z

    .line 319
    .line 320
    if-ne v7, v2, :cond_11

    .line 321
    .line 322
    goto :goto_5

    .line 323
    :cond_11
    if-ne v7, v4, :cond_14

    .line 324
    .line 325
    :goto_5
    check-cast v1, Lsnj;

    .line 326
    .line 327
    iget-object v2, v1, Lsnj;->a:Lsyj;

    .line 328
    .line 329
    iget-object v3, v2, Lsyj;->p:Ljava/lang/String;

    .line 330
    .line 331
    if-eqz v3, :cond_13

    .line 332
    .line 333
    iget-object v2, v2, Lsyj;->s:Ljava/lang/String;

    .line 334
    .line 335
    if-eqz v2, :cond_12

    .line 336
    .line 337
    new-instance v4, Lhg1;

    .line 338
    .line 339
    iget-object v1, v1, Lsnj;->a:Lsyj;

    .line 340
    .line 341
    iget-object v1, v1, Lsyj;->b:Lk3m;

    .line 342
    .line 343
    new-instance v5, LOCj;

    .line 344
    .line 345
    new-instance v7, Lqkb;

    .line 346
    .line 347
    invoke-direct {v7, v2, v3, v6}, Lqkb;-><init>(Ljava/lang/String;Ljava/lang/String;Z)V

    .line 348
    .line 349
    .line 350
    invoke-direct {v5, v7}, LOCj;-><init>(Lqkb;)V

    .line 351
    .line 352
    .line 353
    invoke-direct {v4, v1, v5}, Lhg1;-><init>(Lk3m;LOCj;)V

    .line 354
    .line 355
    .line 356
    :goto_6
    move-object v3, v4

    .line 357
    goto/16 :goto_8

    .line 358
    .line 359
    :cond_12
    new-instance v1, Ljava/lang/IllegalArgumentException;

    .line 360
    .line 361
    const-string v2, "Pack id is null"

    .line 362
    .line 363
    invoke-direct {v1, v2}, Ljava/lang/IllegalArgumentException;-><init>(Ljava/lang/String;)V

    .line 364
    .line 365
    .line 366
    throw v1

    .line 367
    :cond_13
    new-instance v1, Ljava/lang/IllegalArgumentException;

    .line 368
    .line 369
    invoke-direct {v1, v5}, Ljava/lang/IllegalArgumentException;-><init>(Ljava/lang/String;)V

    .line 370
    .line 371
    .line 372
    throw v1

    .line 373
    :cond_14
    const/4 v2, 0x4

    .line 374
    if-ne v7, v2, :cond_16

    .line 375
    .line 376
    check-cast v1, Lsnj;

    .line 377
    .line 378
    iget-object v2, v1, Lsnj;->a:Lsyj;

    .line 379
    .line 380
    iget-object v2, v2, Lsyj;->a:Landroid/net/Uri;

    .line 381
    .line 382
    const-string v3, "custom_sticker_data"

    .line 383
    .line 384
    invoke-virtual {v2, v3}, Landroid/net/Uri;->getQueryParameter(Ljava/lang/String;)Ljava/lang/String;

    .line 385
    .line 386
    .line 387
    move-result-object v2

    .line 388
    if-eqz v2, :cond_15

    .line 389
    .line 390
    iget-object v3, v0, Lcq4;->e:Ljava/lang/Object;

    .line 391
    .line 392
    check-cast v3, LWAi;

    .line 393
    .line 394
    const-class v4, LqS4;

    .line 395
    .line 396
    invoke-virtual {v3, v4, v2}, LWAi;->f(Ljava/lang/Class;Ljava/lang/String;)Ljava/lang/Object;

    .line 397
    .line 398
    .line 399
    move-result-object v2

    .line 400
    check-cast v2, LqS4;

    .line 401
    .line 402
    new-instance v3, LiS4;

    .line 403
    .line 404
    invoke-direct {v3, v2}, LiS4;-><init>(LqS4;)V

    .line 405
    .line 406
    .line 407
    new-instance v2, LtF1;

    .line 408
    .line 409
    iget-object v1, v1, Lsnj;->a:Lsyj;

    .line 410
    .line 411
    iget-object v1, v1, Lsyj;->b:Lk3m;

    .line 412
    .line 413
    invoke-direct {v2, v3, v1}, LtF1;-><init>(LiS4;Lk3m;)V

    .line 414
    .line 415
    .line 416
    goto/16 :goto_1

    .line 417
    .line 418
    :cond_15
    new-instance v1, Ljava/lang/IllegalAccessException;

    .line 419
    .line 420
    const-string v2, "Custom sticker data is null"

    .line 421
    .line 422
    invoke-direct {v1, v2}, Ljava/lang/IllegalAccessException;-><init>(Ljava/lang/String;)V

    .line 423
    .line 424
    .line 425
    throw v1

    .line 426
    :cond_16
    const/16 v2, 0x9

    .line 427
    .line 428
    if-ne v7, v2, :cond_19

    .line 429
    .line 430
    check-cast v1, Lsnj;

    .line 431
    .line 432
    iget-object v2, v1, Lsnj;->a:Lsyj;

    .line 433
    .line 434
    iget-object v3, v2, Lsyj;->p:Ljava/lang/String;

    .line 435
    .line 436
    if-eqz v3, :cond_18

    .line 437
    .line 438
    iget-object v2, v2, Lsyj;->j:Ljava/lang/String;

    .line 439
    .line 440
    if-eqz v2, :cond_17

    .line 441
    .line 442
    new-instance v4, Lhw9;

    .line 443
    .line 444
    iget-object v1, v1, Lsnj;->a:Lsyj;

    .line 445
    .line 446
    iget-object v5, v1, Lsyj;->b:Lk3m;

    .line 447
    .line 448
    new-instance v7, Lfw9;

    .line 449
    .line 450
    iget-object v1, v1, Lsyj;->w:Ljava/lang/String;

    .line 451
    .line 452
    invoke-direct {v7, v3, v2, v6, v1}, Lfw9;-><init>(Ljava/lang/String;Ljava/lang/String;ZLjava/lang/String;)V

    .line 453
    .line 454
    .line 455
    invoke-direct {v4, v5, v7}, Lhw9;-><init>(Lk3m;Lfw9;)V

    .line 456
    .line 457
    .line 458
    goto :goto_6

    .line 459
    :cond_17
    new-instance v1, Ljava/lang/IllegalArgumentException;

    .line 460
    .line 461
    invoke-direct {v1, v9}, Ljava/lang/IllegalArgumentException;-><init>(Ljava/lang/String;)V

    .line 462
    .line 463
    .line 464
    throw v1

    .line 465
    :cond_18
    new-instance v1, Ljava/lang/IllegalArgumentException;

    .line 466
    .line 467
    invoke-direct {v1, v5}, Ljava/lang/IllegalArgumentException;-><init>(Ljava/lang/String;)V

    .line 468
    .line 469
    .line 470
    throw v1

    .line 471
    :cond_19
    const/16 v2, 0xc

    .line 472
    .line 473
    if-ne v7, v2, :cond_1c

    .line 474
    .line 475
    check-cast v1, Lsnj;

    .line 476
    .line 477
    iget-object v2, v1, Lsnj;->a:Lsyj;

    .line 478
    .line 479
    iget-object v4, v2, Lsyj;->p:Ljava/lang/String;

    .line 480
    .line 481
    if-eqz v4, :cond_1b

    .line 482
    .line 483
    iget-object v2, v2, Lsyj;->j:Ljava/lang/String;

    .line 484
    .line 485
    if-eqz v2, :cond_1a

    .line 486
    .line 487
    new-instance v5, Lhg1;

    .line 488
    .line 489
    iget-object v1, v1, Lsnj;->a:Lsyj;

    .line 490
    .line 491
    iget-object v1, v1, Lsyj;->b:Lk3m;

    .line 492
    .line 493
    new-instance v6, Lh0f;

    .line 494
    .line 495
    invoke-direct {v6, v3, v4, v2}, Lh0f;-><init>(ILjava/lang/String;Ljava/lang/String;)V

    .line 496
    .line 497
    .line 498
    invoke-direct {v5, v1, v6}, Lhg1;-><init>(Lk3m;Lh0f;)V

    .line 499
    .line 500
    .line 501
    :goto_7
    move-object v3, v5

    .line 502
    goto/16 :goto_8

    .line 503
    .line 504
    :cond_1a
    new-instance v1, Ljava/lang/IllegalArgumentException;

    .line 505
    .line 506
    invoke-direct {v1, v9}, Ljava/lang/IllegalArgumentException;-><init>(Ljava/lang/String;)V

    .line 507
    .line 508
    .line 509
    throw v1

    .line 510
    :cond_1b
    new-instance v1, Ljava/lang/IllegalArgumentException;

    .line 511
    .line 512
    invoke-direct {v1, v5}, Ljava/lang/IllegalArgumentException;-><init>(Ljava/lang/String;)V

    .line 513
    .line 514
    .line 515
    throw v1

    .line 516
    :cond_1c
    const/16 v2, 0xd

    .line 517
    .line 518
    const-string v6, "Conversation Id is null"

    .line 519
    .line 520
    if-ne v7, v2, :cond_20

    .line 521
    .line 522
    check-cast v1, Lsnj;

    .line 523
    .line 524
    iget-object v2, v1, Lsnj;->a:Lsyj;

    .line 525
    .line 526
    iget-object v3, v2, Lsyj;->p:Ljava/lang/String;

    .line 527
    .line 528
    if-eqz v3, :cond_1f

    .line 529
    .line 530
    iget-object v4, v2, Lsyj;->j:Ljava/lang/String;

    .line 531
    .line 532
    if-eqz v4, :cond_1e

    .line 533
    .line 534
    iget-object v2, v2, Lsyj;->q:Ljava/lang/String;

    .line 535
    .line 536
    if-eqz v2, :cond_1d

    .line 537
    .line 538
    new-instance v5, LnGg;

    .line 539
    .line 540
    iget-object v1, v1, Lsnj;->a:Lsyj;

    .line 541
    .line 542
    iget-object v1, v1, Lsyj;->b:Lk3m;

    .line 543
    .line 544
    new-instance v6, LlGg;

    .line 545
    .line 546
    invoke-direct {v6, v3, v4, v2}, LlGg;-><init>(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V

    .line 547
    .line 548
    .line 549
    invoke-direct {v5, v1, v6}, LnGg;-><init>(Lk3m;LlGg;)V

    .line 550
    .line 551
    .line 552
    goto :goto_7

    .line 553
    :cond_1d
    new-instance v1, Ljava/lang/IllegalArgumentException;

    .line 554
    .line 555
    invoke-direct {v1, v6}, Ljava/lang/IllegalArgumentException;-><init>(Ljava/lang/String;)V

    .line 556
    .line 557
    .line 558
    throw v1

    .line 559
    :cond_1e
    new-instance v1, Ljava/lang/IllegalArgumentException;

    .line 560
    .line 561
    invoke-direct {v1, v9}, Ljava/lang/IllegalArgumentException;-><init>(Ljava/lang/String;)V

    .line 562
    .line 563
    .line 564
    throw v1

    .line 565
    :cond_1f
    new-instance v1, Ljava/lang/IllegalArgumentException;

    .line 566
    .line 567
    invoke-direct {v1, v5}, Ljava/lang/IllegalArgumentException;-><init>(Ljava/lang/String;)V

    .line 568
    .line 569
    .line 570
    throw v1

    .line 571
    :cond_20
    const/16 v2, 0xa

    .line 572
    .line 573
    if-ne v7, v2, :cond_24

    .line 574
    .line 575
    check-cast v1, Lsnj;

    .line 576
    .line 577
    iget-object v2, v1, Lsnj;->a:Lsyj;

    .line 578
    .line 579
    iget-object v11, v2, Lsyj;->p:Ljava/lang/String;

    .line 580
    .line 581
    if-eqz v11, :cond_23

    .line 582
    .line 583
    iget-object v3, v2, Lsyj;->j:Ljava/lang/String;

    .line 584
    .line 585
    if-eqz v3, :cond_22

    .line 586
    .line 587
    iget-object v2, v2, Lsyj;->u:Ljava/lang/String;

    .line 588
    .line 589
    if-nez v2, :cond_21

    .line 590
    .line 591
    const-string v2, ""

    .line 592
    .line 593
    :cond_21
    move-object/from16 v17, v2

    .line 594
    .line 595
    new-instance v2, LnF1;

    .line 596
    .line 597
    invoke-static {v3}, Landroid/net/Uri;->parse(Ljava/lang/String;)Landroid/net/Uri;

    .line 598
    .line 599
    .line 600
    move-result-object v12

    .line 601
    invoke-static {v3}, Landroid/net/Uri;->parse(Ljava/lang/String;)Landroid/net/Uri;

    .line 602
    .line 603
    .line 604
    move-result-object v13

    .line 605
    sget-object v18, Lw08;->a:Lw08;

    .line 606
    .line 607
    const/4 v15, 0x0

    .line 608
    const/16 v16, 0x0

    .line 609
    .line 610
    const/4 v14, 0x0

    .line 611
    move-object v10, v2

    .line 612
    invoke-direct/range {v10 .. v18}, LnF1;-><init>(Ljava/lang/String;Landroid/net/Uri;Landroid/net/Uri;LmF1;LoT4;[ILjava/lang/String;Ljava/util/List;)V

    .line 613
    .line 614
    .line 615
    new-instance v3, LtF1;

    .line 616
    .line 617
    iget-object v1, v1, Lsnj;->a:Lsyj;

    .line 618
    .line 619
    iget-object v1, v1, Lsyj;->b:Lk3m;

    .line 620
    .line 621
    invoke-direct {v3, v2, v1}, LtF1;-><init>(LnF1;Lk3m;)V

    .line 622
    .line 623
    .line 624
    goto/16 :goto_8

    .line 625
    .line 626
    :cond_22
    new-instance v1, Ljava/lang/IllegalArgumentException;

    .line 627
    .line 628
    invoke-direct {v1, v9}, Ljava/lang/IllegalArgumentException;-><init>(Ljava/lang/String;)V

    .line 629
    .line 630
    .line 631
    throw v1

    .line 632
    :cond_23
    new-instance v1, Ljava/lang/IllegalArgumentException;

    .line 633
    .line 634
    invoke-direct {v1, v5}, Ljava/lang/IllegalArgumentException;-><init>(Ljava/lang/String;)V

    .line 635
    .line 636
    .line 637
    throw v1

    .line 638
    :cond_24
    const/16 v2, 0xf

    .line 639
    .line 640
    if-ne v7, v2, :cond_28

    .line 641
    .line 642
    check-cast v1, Lsnj;

    .line 643
    .line 644
    iget-object v2, v1, Lsnj;->a:Lsyj;

    .line 645
    .line 646
    iget-object v3, v2, Lsyj;->p:Ljava/lang/String;

    .line 647
    .line 648
    if-eqz v3, :cond_27

    .line 649
    .line 650
    iget-object v4, v2, Lsyj;->j:Ljava/lang/String;

    .line 651
    .line 652
    if-eqz v4, :cond_26

    .line 653
    .line 654
    iget-object v2, v2, Lsyj;->z:Ljava/lang/String;

    .line 655
    .line 656
    if-eqz v2, :cond_25

    .line 657
    .line 658
    new-instance v5, LMvj;

    .line 659
    .line 660
    iget-object v1, v1, Lsnj;->a:Lsyj;

    .line 661
    .line 662
    iget-object v1, v1, Lsyj;->b:Lk3m;

    .line 663
    .line 664
    new-instance v6, LHvj;

    .line 665
    .line 666
    invoke-direct {v6, v3, v4, v2}, LHvj;-><init>(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V

    .line 667
    .line 668
    .line 669
    invoke-direct {v5, v1, v6}, LMvj;-><init>(Lk3m;LHvj;)V

    .line 670
    .line 671
    .line 672
    goto/16 :goto_7

    .line 673
    .line 674
    :cond_25
    new-instance v1, Ljava/lang/IllegalArgumentException;

    .line 675
    .line 676
    const-string v2, "Conversation id is null"

    .line 677
    .line 678
    invoke-direct {v1, v2}, Ljava/lang/IllegalArgumentException;-><init>(Ljava/lang/String;)V

    .line 679
    .line 680
    .line 681
    throw v1

    .line 682
    :cond_26
    new-instance v1, Ljava/lang/IllegalArgumentException;

    .line 683
    .line 684
    invoke-direct {v1, v9}, Ljava/lang/IllegalArgumentException;-><init>(Ljava/lang/String;)V

    .line 685
    .line 686
    .line 687
    throw v1

    .line 688
    :cond_27
    new-instance v1, Ljava/lang/IllegalArgumentException;

    .line 689
    .line 690
    invoke-direct {v1, v5}, Ljava/lang/IllegalArgumentException;-><init>(Ljava/lang/String;)V

    .line 691
    .line 692
    .line 693
    throw v1

    .line 694
    :cond_28
    const/16 v2, 0x10

    .line 695
    .line 696
    if-ne v7, v2, :cond_2b

    .line 697
    .line 698
    check-cast v1, Lsnj;

    .line 699
    .line 700
    iget-object v2, v1, Lsnj;->a:Lsyj;

    .line 701
    .line 702
    iget-object v6, v2, Lsyj;->p:Ljava/lang/String;

    .line 703
    .line 704
    if-eqz v6, :cond_2a

    .line 705
    .line 706
    iget-object v2, v2, Lsyj;->j:Ljava/lang/String;

    .line 707
    .line 708
    if-eqz v2, :cond_29

    .line 709
    .line 710
    new-instance v5, Lhg1;

    .line 711
    .line 712
    iget-object v1, v1, Lsnj;->a:Lsyj;

    .line 713
    .line 714
    iget-object v1, v1, Lsyj;->b:Lk3m;

    .line 715
    .line 716
    new-instance v7, Lh0f;

    .line 717
    .line 718
    invoke-direct {v7, v4, v6, v2}, Lh0f;-><init>(ILjava/lang/String;Ljava/lang/String;)V

    .line 719
    .line 720
    .line 721
    invoke-direct {v5, v1, v7, v3}, Lhg1;-><init>(Lk3m;Lh0f;I)V

    .line 722
    .line 723
    .line 724
    goto/16 :goto_7

    .line 725
    .line 726
    :cond_29
    new-instance v1, Ljava/lang/IllegalArgumentException;

    .line 727
    .line 728
    invoke-direct {v1, v9}, Ljava/lang/IllegalArgumentException;-><init>(Ljava/lang/String;)V

    .line 729
    .line 730
    .line 731
    throw v1

    .line 732
    :cond_2a
    new-instance v1, Ljava/lang/IllegalArgumentException;

    .line 733
    .line 734
    invoke-direct {v1, v5}, Ljava/lang/IllegalArgumentException;-><init>(Ljava/lang/String;)V

    .line 735
    .line 736
    .line 737
    throw v1

    .line 738
    :cond_2b
    const/16 v2, 0x13

    .line 739
    .line 740
    if-ne v7, v2, :cond_2f

    .line 741
    .line 742
    check-cast v1, Lsnj;

    .line 743
    .line 744
    iget-object v2, v1, Lsnj;->a:Lsyj;

    .line 745
    .line 746
    iget-object v3, v2, Lsyj;->p:Ljava/lang/String;

    .line 747
    .line 748
    if-eqz v3, :cond_2e

    .line 749
    .line 750
    iget-object v4, v2, Lsyj;->j:Ljava/lang/String;

    .line 751
    .line 752
    if-eqz v4, :cond_2d

    .line 753
    .line 754
    iget-object v2, v2, Lsyj;->q:Ljava/lang/String;

    .line 755
    .line 756
    if-eqz v2, :cond_2c

    .line 757
    .line 758
    new-instance v5, Lhg1;

    .line 759
    .line 760
    iget-object v1, v1, Lsnj;->a:Lsyj;

    .line 761
    .line 762
    iget-object v1, v1, Lsyj;->b:Lk3m;

    .line 763
    .line 764
    new-instance v6, LtDg;

    .line 765
    .line 766
    invoke-direct {v6, v3, v4, v2}, LtDg;-><init>(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V

    .line 767
    .line 768
    .line 769
    invoke-direct {v5, v1, v6}, Lhg1;-><init>(Lk3m;LtDg;)V

    .line 770
    .line 771
    .line 772
    goto/16 :goto_7

    .line 773
    .line 774
    :goto_8
    return-object v3

    .line 775
    :cond_2c
    new-instance v1, Ljava/lang/IllegalArgumentException;

    .line 776
    .line 777
    invoke-direct {v1, v6}, Ljava/lang/IllegalArgumentException;-><init>(Ljava/lang/String;)V

    .line 778
    .line 779
    .line 780
    throw v1

    .line 781
    :cond_2d
    new-instance v1, Ljava/lang/IllegalArgumentException;

    .line 782
    .line 783
    invoke-direct {v1, v9}, Ljava/lang/IllegalArgumentException;-><init>(Ljava/lang/String;)V

    .line 784
    .line 785
    .line 786
    throw v1

    .line 787
    :cond_2e
    new-instance v1, Ljava/lang/IllegalArgumentException;

    .line 788
    .line 789
    invoke-direct {v1, v5}, Ljava/lang/IllegalArgumentException;-><init>(Ljava/lang/String;)V

    .line 790
    .line 791
    .line 792
    throw v1

    .line 793
    :cond_2f
    new-instance v1, Ljava/lang/IllegalStateException;

    .line 794
    .line 795
    const-string v2, "This sticker type is not supported yet"

    .line 796
    .line 797
    invoke-direct {v1, v2}, Ljava/lang/IllegalStateException;-><init>(Ljava/lang/String;)V

    .line 798
    .line 799
    .line 800
    throw v1

    .line 801
    :pswitch_0
    iget-object v1, v0, Lcq4;->d:Ljava/lang/Object;

    .line 802
    .line 803
    check-cast v1, Lpq4;

    .line 804
    .line 805
    iget-object v7, v1, Lpq4;->v:Lbv4;

    .line 806
    .line 807
    if-eqz v7, :cond_30

    .line 808
    .line 809
    invoke-virtual {v7}, Lbv4;->t()Z

    .line 810
    .line 811
    .line 812
    move-result v7

    .line 813
    if-ne v7, v4, :cond_30

    .line 814
    .line 815
    iget-object v7, v1, Lpq4;->a:Landroidx/fragment/app/FragmentActivity;

    .line 816
    .line 817
    invoke-virtual {v7}, Landroid/content/Context;->getResources()Landroid/content/res/Resources;

    .line 818
    .line 819
    .line 820
    move-result-object v7

    .line 821
    invoke-virtual {v7}, Landroid/content/res/Resources;->getDisplayMetrics()Landroid/util/DisplayMetrics;

    .line 822
    .line 823
    .line 824
    move-result-object v7

    .line 825
    iget v7, v7, Landroid/util/DisplayMetrics;->widthPixels:I

    .line 826
    .line 827
    int-to-float v7, v7

    .line 828
    invoke-virtual {v1}, Lpq4;->e()Landroid/widget/FrameLayout;

    .line 829
    .line 830
    .line 831
    move-result-object v8

    .line 832
    invoke-virtual {v8, v7}, Landroid/view/View;->setTranslationX(F)V

    .line 833
    .line 834
    .line 835
    iget-object v7, v1, Lpq4;->u:LCbl;

    .line 836
    .line 837
    invoke-virtual {v7}, LCbl;->getValue()Ljava/lang/Object;

    .line 838
    .line 839
    .line 840
    move-result-object v7

    .line 841
    check-cast v7, Landroid/animation/ObjectAnimator;

    .line 842
    .line 843
    new-instance v8, Landroid/view/animation/AccelerateDecelerateInterpolator;

    .line 844
    .line 845
    invoke-direct {v8}, Landroid/view/animation/AccelerateDecelerateInterpolator;-><init>()V

    .line 846
    .line 847
    .line 848
    invoke-virtual {v7, v8}, Landroid/animation/Animator;->setInterpolator(Landroid/animation/TimeInterpolator;)V

    .line 849
    .line 850
    .line 851
    iget-object v7, v1, Lpq4;->u:LCbl;

    .line 852
    .line 853
    invoke-virtual {v7}, LCbl;->getValue()Ljava/lang/Object;

    .line 854
    .line 855
    .line 856
    move-result-object v7

    .line 857
    check-cast v7, Landroid/animation/ObjectAnimator;

    .line 858
    .line 859
    const-wide/16 v8, 0xfa

    .line 860
    .line 861
    invoke-virtual {v7, v8, v9}, Landroid/animation/ObjectAnimator;->setDuration(J)Landroid/animation/ObjectAnimator;

    .line 862
    .line 863
    .line 864
    iget-object v1, v1, Lpq4;->u:LCbl;

    .line 865
    .line 866
    invoke-virtual {v1}, LCbl;->getValue()Ljava/lang/Object;

    .line 867
    .line 868
    .line 869
    move-result-object v1

    .line 870
    check-cast v1, Landroid/animation/ObjectAnimator;

    .line 871
    .line 872
    invoke-virtual {v1}, Landroid/animation/ObjectAnimator;->start()V

    .line 873
    .line 874
    .line 875
    :cond_30
    iget-object v1, v0, Lcq4;->d:Ljava/lang/Object;

    .line 876
    .line 877
    check-cast v1, Lpq4;

    .line 878
    .line 879
    iget-object v1, v1, Lpq4;->L:LoZj;

    .line 880
    .line 881
    iget-object v7, v0, Lcq4;->e:Ljava/lang/Object;

    .line 882
    .line 883
    check-cast v7, Lbv4;

    .line 884
    .line 885
    invoke-virtual {v7}, Lbv4;->t()Z

    .line 886
    .line 887
    .line 888
    move-result v7

    .line 889
    if-eqz v7, :cond_31

    .line 890
    .line 891
    iget-object v7, v0, Lcq4;->d:Ljava/lang/Object;

    .line 892
    .line 893
    check-cast v7, Lpq4;

    .line 894
    .line 895
    invoke-virtual {v7}, Lpq4;->e()Landroid/widget/FrameLayout;

    .line 896
    .line 897
    .line 898
    move-result-object v7

    .line 899
    goto :goto_9

    .line 900
    :cond_31
    iget-object v7, v0, Lcq4;->d:Ljava/lang/Object;

    .line 901
    .line 902
    check-cast v7, Lpq4;

    .line 903
    .line 904
    iget-object v7, v7, Lpq4;->b:Landroid/widget/FrameLayout;

    .line 905
    .line 906
    :goto_9
    iget-object v8, v0, Lcq4;->e:Ljava/lang/Object;

    .line 907
    .line 908
    check-cast v8, Lbv4;

    .line 909
    .line 910
    iget-object v9, v0, Lcq4;->d:Ljava/lang/Object;

    .line 911
    .line 912
    check-cast v9, Lpq4;

    .line 913
    .line 914
    iget-object v10, v9, Lpq4;->c:LPSa;

    .line 915
    .line 916
    iget v11, v0, Lcq4;->b:I

    .line 917
    .line 918
    if-lez v11, :cond_32

    .line 919
    .line 920
    const/4 v15, 0x1

    .line 921
    goto :goto_a

    .line 922
    :cond_32
    const/4 v15, 0x0

    .line 923
    :goto_a
    invoke-virtual {v9}, Lpq4;->d()Lt8h;

    .line 924
    .line 925
    .line 926
    move-result-object v9

    .line 927
    iget-object v11, v0, Lcq4;->d:Ljava/lang/Object;

    .line 928
    .line 929
    check-cast v11, Lpq4;

    .line 930
    .line 931
    iget-object v12, v11, Lpq4;->s:Lvei;

    .line 932
    .line 933
    iget-object v11, v11, Lpq4;->d:LVq4;

    .line 934
    .line 935
    iget-boolean v14, v0, Lcq4;->c:Z

    .line 936
    .line 937
    invoke-virtual {v1}, Ljava/lang/Object;->getClass()Ljava/lang/Class;

    .line 938
    .line 939
    .line 940
    iget-object v13, v8, Lbv4;->d:LPu4;

    .line 941
    .line 942
    if-eqz v13, :cond_44

    .line 943
    .line 944
    iget-object v6, v8, Lbv4;->e:LYu4;

    .line 945
    .line 946
    if-eqz v6, :cond_43

    .line 947
    .line 948
    iget-object v5, v8, Lbv4;->f:LZu4;

    .line 949
    .line 950
    iget-object v3, v1, LoZj;->c:Ljava/lang/Object;

    .line 951
    .line 952
    check-cast v3, LMSa;

    .line 953
    .line 954
    sget-object v2, Ltq4;->d:Ltq4;

    .line 955
    .line 956
    if-nez v3, :cond_39

    .line 957
    .line 958
    iget-object v3, v1, LoZj;->b:Ljava/lang/Object;

    .line 959
    .line 960
    check-cast v3, LT7n;

    .line 961
    .line 962
    iget-object v3, v3, LT7n;->c:LJ7n;

    .line 963
    .line 964
    iput-object v3, v1, LoZj;->f:Ljava/lang/Object;

    .line 965
    .line 966
    iput-object v2, v1, LoZj;->e:Ljava/lang/Object;

    .line 967
    .line 968
    iget-object v3, v1, LoZj;->a:Ljava/lang/Object;

    .line 969
    .line 970
    check-cast v3, LVic;

    .line 971
    .line 972
    if-eqz v5, :cond_33

    .line 973
    .line 974
    iget-object v4, v5, LZu4;->p:Lb74;

    .line 975
    .line 976
    goto :goto_b

    .line 977
    :cond_33
    const/4 v4, 0x0

    .line 978
    :goto_b
    if-eqz v5, :cond_34

    .line 979
    .line 980
    iget-object v0, v5, LZu4;->q:Ljava/lang/String;

    .line 981
    .line 982
    move-object/from16 v17, v0

    .line 983
    .line 984
    goto :goto_c

    .line 985
    :cond_34
    const/16 v17, 0x0

    .line 986
    .line 987
    :goto_c
    if-eqz v5, :cond_35

    .line 988
    .line 989
    iget-object v0, v5, LZu4;->m:Ljava/lang/String;

    .line 990
    .line 991
    move-object/from16 v19, v0

    .line 992
    .line 993
    goto :goto_d

    .line 994
    :cond_35
    const/16 v19, 0x0

    .line 995
    .line 996
    :goto_d
    if-eqz v5, :cond_36

    .line 997
    .line 998
    iget-object v0, v5, LZu4;->b:Ljs4;

    .line 999
    .line 1000
    if-eqz v0, :cond_36

    .line 1001
    .line 1002
    iget-object v0, v0, Ljs4;->t:LXr4;

    .line 1003
    .line 1004
    if-eqz v0, :cond_36

    .line 1005
    .line 1006
    iget-boolean v0, v0, LXr4;->c:Z

    .line 1007
    .line 1008
    move/from16 v22, v0

    .line 1009
    .line 1010
    goto :goto_e

    .line 1011
    :cond_36
    const/16 v22, 0x0

    .line 1012
    .line 1013
    :goto_e
    iget-object v0, v8, Lbv4;->v:LJLj;

    .line 1014
    .line 1015
    sget-object v18, LcHe;->z0:LcHe;

    .line 1016
    .line 1017
    move-object/from16 v23, v10

    .line 1018
    .line 1019
    if-eqz v5, :cond_37

    .line 1020
    .line 1021
    iget-object v10, v5, LZu4;->j:Ljava/lang/String;

    .line 1022
    .line 1023
    move-object/from16 v26, v10

    .line 1024
    .line 1025
    goto :goto_f

    .line 1026
    :cond_37
    const/16 v26, 0x0

    .line 1027
    .line 1028
    :goto_f
    new-instance v10, Luq4;

    .line 1029
    .line 1030
    move/from16 v18, v14

    .line 1031
    .line 1032
    const/4 v14, 0x1

    .line 1033
    invoke-direct {v10, v1, v12, v11, v14}, Luq4;-><init>(LoZj;Lvei;LVq4;I)V

    .line 1034
    .line 1035
    .line 1036
    const/4 v11, 0x3

    .line 1037
    invoke-static {v11}, Ljava/lang/Byte;->valueOf(B)Ljava/lang/Byte;

    .line 1038
    .line 1039
    .line 1040
    move-result-object v29

    .line 1041
    if-eqz v5, :cond_38

    .line 1042
    .line 1043
    iget-object v5, v5, LZu4;->l:Ljava/lang/String;

    .line 1044
    .line 1045
    move-object/from16 v31, v5

    .line 1046
    .line 1047
    goto :goto_10

    .line 1048
    :cond_38
    const/16 v31, 0x0

    .line 1049
    .line 1050
    :goto_10
    iget-object v5, v8, Lbv4;->c:LRu4;

    .line 1051
    .line 1052
    iget-boolean v5, v5, LRu4;->e0:Z

    .line 1053
    .line 1054
    iget-object v11, v13, LPu4;->a:Ljava/lang/String;

    .line 1055
    .line 1056
    iget-boolean v12, v13, LPu4;->b:Z

    .line 1057
    .line 1058
    iget-object v14, v6, LYu4;->a:Ljava/lang/String;

    .line 1059
    .line 1060
    move-object/from16 v16, v10

    .line 1061
    .line 1062
    move-object v10, v13

    .line 1063
    move-object v13, v14

    .line 1064
    iget-object v14, v6, LYu4;->c:Ljava/lang/String;

    .line 1065
    .line 1066
    move-object/from16 v33, v2

    .line 1067
    .line 1068
    move/from16 v2, v18

    .line 1069
    .line 1070
    move/from16 v18, v15

    .line 1071
    .line 1072
    iget-object v15, v6, LYu4;->d:Ljava/lang/String;

    .line 1073
    .line 1074
    move/from16 v34, v2

    .line 1075
    .line 1076
    move/from16 v2, v18

    .line 1077
    .line 1078
    move-object/from16 v35, v8

    .line 1079
    .line 1080
    iget-object v8, v6, LYu4;->e:Ljava/lang/String;

    .line 1081
    .line 1082
    move-object/from16 v18, v8

    .line 1083
    .line 1084
    iget-boolean v6, v6, LYu4;->f:Z

    .line 1085
    .line 1086
    move/from16 v20, v6

    .line 1087
    .line 1088
    iget-object v6, v10, LPu4;->c:LQSa;

    .line 1089
    .line 1090
    move-object/from16 v21, v6

    .line 1091
    .line 1092
    iget-object v6, v10, LPu4;->d:Ljava/lang/String;

    .line 1093
    .line 1094
    move-object/from16 v28, v6

    .line 1095
    .line 1096
    iget-object v6, v10, LPu4;->e:Ljava/lang/String;

    .line 1097
    .line 1098
    move-object/from16 v30, v6

    .line 1099
    .line 1100
    const/16 v25, 0x1

    .line 1101
    .line 1102
    move-object/from16 v8, v16

    .line 1103
    .line 1104
    move-object/from16 v6, v23

    .line 1105
    .line 1106
    move-object v10, v3

    .line 1107
    move-object/from16 v16, v4

    .line 1108
    .line 1109
    move-object/from16 v23, v0

    .line 1110
    .line 1111
    move-object/from16 v24, v6

    .line 1112
    .line 1113
    move-object/from16 v27, v8

    .line 1114
    .line 1115
    move/from16 v32, v5

    .line 1116
    .line 1117
    invoke-virtual/range {v10 .. v32}, LVic;->b(Ljava/lang/String;ZLjava/lang/String;Ljava/lang/String;Ljava/lang/String;Lb74;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;ZLQSa;ZLJLj;LPSa;ZLjava/lang/String;Luq4;Ljava/lang/String;Ljava/lang/Byte;Ljava/lang/String;Ljava/lang/String;Z)LMSa;

    .line 1118
    .line 1119
    .line 1120
    move-result-object v0

    .line 1121
    iput-boolean v2, v0, LMSa;->V:Z

    .line 1122
    .line 1123
    invoke-virtual {v0}, LMSa;->a()Landroid/view/View;

    .line 1124
    .line 1125
    .line 1126
    move-result-object v3

    .line 1127
    const/4 v4, 0x0

    .line 1128
    invoke-virtual {v3, v4}, Landroid/view/View;->setBackgroundColor(I)V

    .line 1129
    .line 1130
    .line 1131
    invoke-virtual {v0}, LMSa;->c()V

    .line 1132
    .line 1133
    .line 1134
    invoke-virtual {v0}, LMSa;->a()Landroid/view/View;

    .line 1135
    .line 1136
    .line 1137
    move-result-object v3

    .line 1138
    invoke-virtual {v7, v3}, Landroid/view/ViewGroup;->addView(Landroid/view/View;)V

    .line 1139
    .line 1140
    .line 1141
    invoke-virtual {v0}, LMSa;->a()Landroid/view/View;

    .line 1142
    .line 1143
    .line 1144
    move-result-object v3

    .line 1145
    const/16 v4, 0x8

    .line 1146
    .line 1147
    invoke-virtual {v3, v4}, Landroid/view/View;->setVisibility(I)V

    .line 1148
    .line 1149
    .line 1150
    iput-object v0, v1, LoZj;->c:Ljava/lang/Object;

    .line 1151
    .line 1152
    iput-object v9, v1, LoZj;->g:Ljava/lang/Object;

    .line 1153
    .line 1154
    invoke-virtual/range {v35 .. v35}, Lbv4;->p()Z

    .line 1155
    .line 1156
    .line 1157
    move-result v0

    .line 1158
    if-eqz v0, :cond_3a

    .line 1159
    .line 1160
    iget-object v0, v1, LoZj;->g:Ljava/lang/Object;

    .line 1161
    .line 1162
    check-cast v0, Lt8h;

    .line 1163
    .line 1164
    if-eqz v0, :cond_3a

    .line 1165
    .line 1166
    iget-boolean v3, v0, Lt8h;->d:Z

    .line 1167
    .line 1168
    if-nez v3, :cond_3a

    .line 1169
    .line 1170
    iget-object v3, v0, Lt8h;->c:Lcom/snap/context_reply_all/ContextReplyAllView;

    .line 1171
    .line 1172
    if-eqz v3, :cond_3a

    .line 1173
    .line 1174
    invoke-virtual {v7, v3}, Landroid/view/ViewGroup;->addView(Landroid/view/View;)V

    .line 1175
    .line 1176
    .line 1177
    const/4 v3, 0x1

    .line 1178
    iput-boolean v3, v0, Lt8h;->d:Z

    .line 1179
    .line 1180
    goto :goto_11

    .line 1181
    :cond_39
    move-object/from16 v33, v2

    .line 1182
    .line 1183
    move/from16 v34, v14

    .line 1184
    .line 1185
    move v2, v15

    .line 1186
    :cond_3a
    :goto_11
    iget-object v0, v1, LoZj;->c:Ljava/lang/Object;

    .line 1187
    .line 1188
    move-object v3, v0

    .line 1189
    check-cast v3, LMSa;

    .line 1190
    .line 1191
    instance-of v4, v3, LMSa;

    .line 1192
    .line 1193
    if-eqz v4, :cond_3b

    .line 1194
    .line 1195
    move-object v4, v3

    .line 1196
    goto :goto_12

    .line 1197
    :cond_3b
    const/4 v4, 0x0

    .line 1198
    :goto_12
    if-eqz v4, :cond_3c

    .line 1199
    .line 1200
    move/from16 v5, v34

    .line 1201
    .line 1202
    iput-boolean v5, v4, LMSa;->F:Z

    .line 1203
    .line 1204
    :cond_3c
    if-nez v3, :cond_3d

    .line 1205
    .line 1206
    goto :goto_13

    .line 1207
    :cond_3d
    iput-boolean v2, v3, LMSa;->V:Z

    .line 1208
    .line 1209
    :goto_13
    if-nez v9, :cond_3e

    .line 1210
    .line 1211
    goto :goto_14

    .line 1212
    :cond_3e
    move-object v2, v0

    .line 1213
    check-cast v2, LMSa;

    .line 1214
    .line 1215
    iput-object v2, v9, Lt8h;->j:LMSa;

    .line 1216
    .line 1217
    :goto_14
    iget-object v2, v1, LoZj;->e:Ljava/lang/Object;

    .line 1218
    .line 1219
    check-cast v2, Ltq4;

    .line 1220
    .line 1221
    move-object/from16 v3, v33

    .line 1222
    .line 1223
    if-eq v2, v3, :cond_3f

    .line 1224
    .line 1225
    goto :goto_18

    .line 1226
    :cond_3f
    check-cast v0, LMSa;

    .line 1227
    .line 1228
    if-nez v0, :cond_40

    .line 1229
    .line 1230
    goto :goto_18

    .line 1231
    :cond_40
    invoke-virtual {v0}, LMSa;->a()Landroid/view/View;

    .line 1232
    .line 1233
    .line 1234
    move-result-object v2

    .line 1235
    const/4 v3, 0x0

    .line 1236
    invoke-virtual {v2, v3}, Landroid/view/View;->setVisibility(I)V

    .line 1237
    .line 1238
    .line 1239
    iget-object v2, v0, LMSa;->a:LLne;

    .line 1240
    .line 1241
    iget-object v3, v0, LMSa;->U:LrR0;

    .line 1242
    .line 1243
    invoke-virtual {v2, v3}, LLne;->d(Lfoe;)V

    .line 1244
    .line 1245
    .line 1246
    iget-boolean v2, v0, LMSa;->F:Z

    .line 1247
    .line 1248
    iget-object v0, v0, LMSa;->r:Lio/reactivex/rxjava3/subjects/PublishSubject;

    .line 1249
    .line 1250
    if-eqz v2, :cond_41

    .line 1251
    .line 1252
    new-instance v2, LSaf;

    .line 1253
    .line 1254
    sget-object v3, Ld9f;->i:Ld9f;

    .line 1255
    .line 1256
    const/4 v4, 0x0

    .line 1257
    invoke-direct {v2, v3, v4}, LSaf;-><init>(Ljava/lang/Object;Ljava/lang/Object;)V

    .line 1258
    .line 1259
    .line 1260
    :goto_15
    invoke-virtual {v0, v2}, Lio/reactivex/rxjava3/subjects/PublishSubject;->onNext(Ljava/lang/Object;)V

    .line 1261
    .line 1262
    .line 1263
    goto :goto_16

    .line 1264
    :cond_41
    const/4 v4, 0x0

    .line 1265
    new-instance v2, LSaf;

    .line 1266
    .line 1267
    sget-object v3, Ld9f;->h:Ld9f;

    .line 1268
    .line 1269
    invoke-direct {v2, v3, v4}, LSaf;-><init>(Ljava/lang/Object;Ljava/lang/Object;)V

    .line 1270
    .line 1271
    .line 1272
    goto :goto_15

    .line 1273
    :goto_16
    new-instance v2, LSaf;

    .line 1274
    .line 1275
    sget-object v3, Ld9f;->b:Ld9f;

    .line 1276
    .line 1277
    invoke-direct {v2, v3, v4}, LSaf;-><init>(Ljava/lang/Object;Ljava/lang/Object;)V

    .line 1278
    .line 1279
    .line 1280
    invoke-virtual {v0, v2}, Lio/reactivex/rxjava3/subjects/PublishSubject;->onNext(Ljava/lang/Object;)V

    .line 1281
    .line 1282
    .line 1283
    new-instance v2, LSaf;

    .line 1284
    .line 1285
    sget-object v3, Ld9f;->c:Ld9f;

    .line 1286
    .line 1287
    invoke-direct {v2, v3, v4}, LSaf;-><init>(Ljava/lang/Object;Ljava/lang/Object;)V

    .line 1288
    .line 1289
    .line 1290
    invoke-virtual {v0, v2}, Lio/reactivex/rxjava3/subjects/PublishSubject;->onNext(Ljava/lang/Object;)V

    .line 1291
    .line 1292
    .line 1293
    iget-object v0, v1, LoZj;->d:Ljava/lang/Object;

    .line 1294
    .line 1295
    check-cast v0, Landroid/widget/TextView;

    .line 1296
    .line 1297
    if-nez v0, :cond_42

    .line 1298
    .line 1299
    goto :goto_17

    .line 1300
    :cond_42
    const/4 v2, 0x0

    .line 1301
    invoke-virtual {v0, v2}, Landroid/view/View;->setVisibility(I)V

    .line 1302
    .line 1303
    .line 1304
    :goto_17
    sget-object v0, Ltq4;->a:Ltq4;

    .line 1305
    .line 1306
    iput-object v0, v1, LoZj;->e:Ljava/lang/Object;

    .line 1307
    .line 1308
    :goto_18
    invoke-virtual {v1}, LoZj;->r()V

    .line 1309
    .line 1310
    .line 1311
    sget-object v0, Lo8m;->a:Lo8m;

    .line 1312
    .line 1313
    return-object v0

    .line 1314
    :cond_43
    new-instance v0, Ljava/lang/IllegalArgumentException;

    .line 1315
    .line 1316
    const-string v1, "SnapContextParams is missing"

    .line 1317
    .line 1318
    invoke-direct {v0, v1}, Ljava/lang/IllegalArgumentException;-><init>(Ljava/lang/String;)V

    .line 1319
    .line 1320
    .line 1321
    throw v0

    .line 1322
    :cond_44
    new-instance v0, Ljava/lang/IllegalArgumentException;

    .line 1323
    .line 1324
    const-string v1, "ChatContextParams is missing"

    .line 1325
    .line 1326
    invoke-direct {v0, v1}, Ljava/lang/IllegalArgumentException;-><init>(Ljava/lang/String;)V

    .line 1327
    .line 1328
    .line 1329
    throw v0

    .line 1330
    nop

    .line 1331
    :pswitch_data_0
    .packed-switch 0x0
        :pswitch_0
    .end packed-switch
.end method
