package com.snapchat.client.content_manager;

/* loaded from: classes8.dex */
public enum StreamErrorReason {
    STREAMNETWORKERROR,
    STREAMCONTENTFORBIDDENERROR,
    STREAMCONTENTNOTFOUNDERROR,
    STREAMCACHEREADERROR,
    STREAMCACHEWRITEERROR,
    STREAMUNEXPECTEDDATAERROR,
    STREAMRANGEERROR,
    STREAMREFERENCECOUNTZEROERROR,
    STREAMCANCELLED
}
